### ISSUE TITLE
Cannot get final name for export 'default' of ./node_modules/.pnpm/jose@5.2.2/node_modules/jose/dist/node/esm/runtime/random.js

### ISSUE THREAD

**Issue by pjborowiecki** [nextauthjs/next-auth#10087] opened 2024-02-20 22:35 UTC
### Environment

System:
OS: macOS 14.1.2
CPU: (8) arm64 Apple M1
Memory: 30.41 MB / 8.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
Yarn: 1.22.21 - /opt/homebrew/bin/yarn
npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
pnpm: 8.15.3 - ~/Library/pnpm/pnpm
bun: 1.0.25 - ~/.bun/bin/bun
Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
Browsers:
Chrome: 121.0.6167.184
Edge: 121.0.2277.128
Safari: 17.1.2
npmPackages:
@auth/core: ^0.27.0 => 0.27.0
@auth/drizzle-adapter: ^0.7.0 => 0.7.0
next: 14.1.0 => 14.1.0
next-auth: 5.0.0-beta.11 => 5.0.0-beta.11
react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/pjborowiecki/JUBILER

### Describe the issue

I am getting the following error when building my project in Next.js with @auth/core@0.27 and next-auth@5.0.0-beta.11:

```
./node_modules/.pnpm/@auth+core@0.27.0/node_modules/@auth/core/index.js + 110 modules
Cannot get final name for export 'default' of ./node_modules/.pnpm/jose@5.2.2/node_modules/jose/dist/node/esm/runtime/random.js
```

Everything works fine in development, just doesn't build.

### How to reproduce

- create a .env file and fill in the values (can be random characters just to test `pnpm dev` and `pnpm build` commands; perhaps the `DATABASE_URL` only should start with `postgresql://` )
- run `pnpm install`
- run `pnpm build`

### Expected behavior

No build errors

**Comment by balazsorban44** [comment] 2024-02-23 00:47
You should not have `@auth/core` installed if you use a framework integration (like `next-auth`). Can you delete it? Also, can you bump, to `beta.13` that includes some fixes?

**Comment by pjborowiecki** [comment] 2024-02-23 18:42
> You should not have `@auth/core` installed if you use a framework integration (like `next-auth`). Can you delete it? Also, can you bump, to `beta.13` that includes some fixes?

Thank you for replying. I am using Drizzle ORM with Neon's Postgres, and pretty much the only thing I need @auth/core for is this:

```
import type { AdapterAccount } from "@auth/core/adapters"

export const accounts = pgTable(
  "account",
  {
    userId: text("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").$type<AdapterAccount["type"]>().notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("providerAccountId").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (account) => ({
    compoundKey: primaryKey({
      columns: [account.provider, account.providerAccountId],
    }),
  })
)
```

Is this not correct? 

Bumping to beta.13 did not solve the problem. Neither did removing node_modules and pnpm-lock.yaml, fresh installs, clearing caches (both pnpm and .next), restartings VS Code, etc.

I was able to solve it by literally copying the entire node_modules folder and pnpm-lock.yaml from [my other project](https://github.com/pjborowiecki/SAASY-LAND-Next-14-Starters-With-Authentication-And-Database-Implemented/tree/next-auth-drizzle-neon-postgres) with nearly identical set up, where everything works fine.

No idea what caused this problem, but either way - it has been resolved now. 
Thank you for your answer again. All best!

**Comment by pjborowiecki** [comment] 2024-02-23 18:46
Saying that, I still see this error in my console every now and then (when a project runs in dev mode for a few hours), which also seems to be related to jose and @auth/core:

```
[auth][warn][debug-enabled] Read more: https://warnings.authjs.dev#debug-enabled
[auth][error] JWTSessionError: Read more at https://errors.authjs.dev#jwtsessionerror
[auth][cause]: JWEDecryptionFailed: decryption operation failed
    at gcmDecrypt (webpack-internal:///(rsc)/./node_modules/.pnpm/jose@5.2.2/node_modules/jose/dist/node/esm/runtime/decrypt.js:81:15)
    at decrypt (webpack-internal:///(rsc)/./node_modules/.pnpm/jose@5.2.2/node_modules/jose/dist/node/esm/runtime/decrypt.js:110:20)
    at flattenedDecrypt (webpack-internal:///(rsc)/./node_modules/.pnpm/jose@5.2.2/node_modules/jose/dist/node/esm/jwe/flattened/decrypt.js:143:92)
    at async compactDecrypt (webpack-internal:///(rsc)/./node_modules/.pnpm/jose@5.2.2/node_modules/jose/dist/node/esm/jwe/compact/decrypt.js:22:23)
    at async jwtDecrypt (webpack-internal:///(rsc)/./node_modules/.pnpm/jose@5.2.2/node_modules/jose/dist/node/esm/jwt/decrypt.js:12:23)
    at async Object.decode (webpack-internal:///(rsc)/./node_modules/.pnpm/@auth+core@0.27.0_nodemailer@6.9.10/node_modules/@auth/core/jwt.js:80:25)
    at async Module.session (webpack-internal:///(rsc)/./node_modules/.pnpm/@auth+core@0.27.0_nodemailer@6.9.10/node_modules/@auth/core/lib/actions/session.js:23:29)
    at async AuthInternal (webpack-internal:///(rsc)/./node_modules/.pnpm/@auth+core@0.27.0_nodemailer@6.9.10/node_modules/@auth/core/lib/index.js:50:24)
    at async Auth (webpack-internal:///(rsc)/./node_modules/.pnpm/@auth+core@0.27.0_nodemailer@6.9.10/node_modules/@auth/core/index.js:126:29)
    at async Header (webpack-internal:///(rsc)/./src/components/nav/back-office/header.tsx:11:21)
[auth][details]: {}
```

Despite this error, authentication seems to work properly

**Comment by ThangHuuVu** [comment] 2024-02-24 02:53
I couldn't reproduce this issue with latest `beta`, so I'm closing it - feel free to file a new issue with a _minimal_ code reproduction if you are able to reproduce it again 🙌

**Closed by ThangHuuVu** 2024-02-24 02:53 UTC
Labels: bug, triage

**Comment by pjborowiecki** [comment] 2024-04-09 09:20
> I think I am having the same issue, did you resolve it? @pjborowiecki 

Not exactly. I ended up creating a new project with a fresh package.json, then moving my components and logic step by step, as nothing else seemed to help. The problem disappeared. Still not sure what causes it.

**Comment by tanapoln** [comment] 2024-05-27 16:20
I got this error and I'm able to reproduce this. Please check my repo https://github.com/tanapoln/nextjs-build-error

Still don't know how to fix it.

**Comment by M00nMission** [comment] 2024-06-09 22:12
@tonyabracadabra @tanapoln 

>go to your Vercel deployment dashboard tab
>find the commit hash of the last successful deployment
>checkout that specific commit hash `git checkout abc1234`
>test it with `pnpm build`
>if it bundles successfully, fork a new local branch of that detached HEAD `git checkout -b new-branch-name`
>now, manually go back and add all your new changes from your broken branch to your new one, making sure to test `pnpm build` to ensure nothing breaks
>now your new forked local branch should be identical to your broken local branch
>now create a new remote branch from your new local branch that isn't broken when you run `pnpm build`
>now delete the broken local branch
>go to GitHub, change your default branch from the broken remote one to the new one you just uploaded
>now delete the broken remote branch
>now rename both local and remote branch back (e.g. `main`)

**Comment by amitamrutiya** [comment] 2024-07-04 02:44
I got this same error in my turbo repo
