### ISSUE TITLE
next-auth Provider Icon svg's don't seem to point anywhere, returning 404

### ISSUE THREAD

**Issue by BenBab** [nextauthjs/next-auth#6372] opened 2023-01-11 23:56 UTC
### Environment

 System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
    Memory: 9.50 GB / 31.86 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)  
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next: 13.1.1 => 13.1.1
    next-auth: ^4.18.7 => 4.18.7
    react: 18.2.0 => 18.2.0

### Reproduction URL

N/a

### Describe the issue

Creating an auth portal using the standard providers with no customisation. 

![image](https://user-images.githubusercontent.com/15340395/211942132-93f08be3-0b65-427e-88b9-5d90295bee0f.png)

The Svg logos for the providers do not appear to be pointing anywhere.. 
It is broken for all the logos. Seems maybe where the svg's are stored is down?

Here is the file location of the google provider icon in the latest version of next-auth
[github google icon](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/google.ts#L41)

### How to reproduce

This is an example link to where the icon points to.. 
[https://raw.githubusercontent.com/nextauthjs/next-auth/main/packages/next-auth/provider-logos/google.svg](https://raw.githubusercontent.com/nextauthjs/next-auth/main/packages/next-auth/provider-logos/google.svg)

Which returns 
![image](https://user-images.githubusercontent.com/15340395/211942614-e7efcc64-8354-4970-949a-9217fab35929.png)

### Expected behavior

It should return the logo svg and not a 404 error

**Comment by balazsorban44** [comment] 2023-01-12 08:06
Duplicate of #6313

**Closed by balazsorban44** 2023-01-12 08:06 UTC
Labels: triage
