### ISSUE TITLE
[V4 Beta][TS] Unable to satisfy `signIn` type constraints in V4

### ISSUE THREAD

**Issue by TheoBr** [nextauthjs/next-auth#2673] opened 2021-09-06 00:35 UTC
### Description 🐜

![image](https://user-images.githubusercontent.com/6751787/132145851-dbfbd8ae-80c0-4d05-9fe8-d9d965a91fc2.png)

![image](https://user-images.githubusercontent.com/6751787/132145848-81117b88-c2f4-4b51-9584-0d5cc35e782d.png)

Source example:
https://github.com/TheoBr/next-auth-v4-prisma-demo/blob/signin-types-broken-demo/pages/index.tsx

### Is this a bug in your own project?

No

### How to reproduce ☕️

https://github.com/TheoBr/next-auth-v4-prisma-demo/blob/signin-types-broken-demo/pages/index.tsx

### Environment 🖥

Modern MacOS with node 16 lts

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment] 2021-09-06 06:46
Duplicate of #2654

**Closed** 2021-09-06 06:46 UTC
Labels: bug, duplicate
