### ISSUE TITLE
NEXTAUTH_URL in development makes the application crash.

### ISSUE THREAD

**Issue by Hardel-DW** [nextauthjs/next-auth#6003] opened 2022-12-09 07:29 UTC
### Environment

```
  System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 18.97 GB / 31.88 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.900.0), Chromium (108.0.1462.42)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    next: 13.0.5 => 13.0.5
    next-auth: ^4.18.4 => 4.18.4
    react: 18.2.0 => 18.2.0
```

### Reproduction URL

https://github.com/Hardel-DW/nextauth-bug

### Describe the issue

Add NEXTAUTH_URL in env file in development (localhost) makes the application crash.

"Error: This action with HTTP GET is not supported by NextAuth.js"

# Problem
Define "NEXTAUTH_URL" in developpement cause this error, if you remove this "env" entry the routes nextauth works.

# Note
The most surprising thing is that I have been working with this line in my .env file for two months
And only since I did "rm -rf ./node_modules/" with a clean reinstallation "yarn" or "npm i" I have this error.
![chrome_R6tMi9lZyb](https://user-images.githubusercontent.com/42413417/206645992-218d5fb5-4d2a-4e66-b93a-b7cf15ebdea0.png)
![image](https://user-images.githubusercontent.com/42413417/206646873-81391fc2-bf68-40c1-81b5-f3982763bae1.png)

### How to reproduce

# Setup : https://github.com/Hardel-DW/nextauth-bug
1. Rename exemple.env to .env file
2. Add Providers Client and Secret
3. use yarn
4. start the project with next dev

# Reproduce bug :
1. Setup project and start the project
2 (A) - Go to localhost:3000/api/auth/signin. See the error
2 (B) - Use unstable_getServerSession see the Json Parse error.

# Note
You can reproduce this bug in existing project just add this line in .env file
NEXTAUTH_URL='http://localhost:3000/'

### Expected behavior

Just that NextAuth works :)

**Comment by Flafi87** [comment] 2022-12-09 08:26
Have the same issue, but not only in development mode unfortunately. After rebuilding docker image without changing anything in repo, the problem appeared. Fixing the next-auth version to a previous one was fixing the problem.

**Comment by m-romandic-un1** [comment] 2022-12-09 08:37
same issue

**Comment by balazsorban44** [comment] 2022-12-09 09:27
Duplicate of #5953, at least the underlying issue is the same. Will track it there. FWIW, you don't need to set `NEXTAUTH_URL` locally, when using the default Next.js host/port of `localhost:3000`, so removing it should be fine. :+1:

**Closed by balazsorban44** 2022-12-09 09:27 UTC
Labels: triage

**Comment by Dav3rs** [comment] 2022-12-09 18:37
> The most surprising thing is that I have been working with this line in my .env file for two months
> And only since I did "rm -rf ./node_modules/" with a clean reinstallation "yarn" or "npm i" I have this error.

Having the same Issue, rebuilding a code that worked last week ,with a clean install result in the "Error: This action with HTTP GET is not supported by NextAuth.js"

Maybe is an indirect dependency, of next-auth the problem, some variation inside the lock file for new installs.
