### ISSUE TITLE
getSession on server side: calling the API is a huge design issue

### ISSUE THREAD

**Issue by fromi** [nextauthjs/next-auth#947] opened 2020-12-10 15:26 UTC
**Describe the bug**
[The code for `getSession`, on server side, is calling the API](https://github.com/nextauthjs/next-auth/blob/e031591468390936d816a073007571b23964b5d3/src/client/index.js#L107)

This a bad idea for a lot of reasons:
- maybe the server is not allowed to make such requests
- maybe the API is not available (at startup for instance?)
- it increases the process and bandwidth usage for no reason
- and the worst thing: if the API updates the cookie there, it will not be reflected in the browser as the request was originated by the server...

**Expected behavior**
getSession on server side should take request, response and options, and handle the job without any HTTP request.

**Comment by balazsorban44** [comment] 2020-12-10 17:19
Hi there! Do you maybe have a suggestion for improvement? If so, we welcome PRs 😊

**Comment by fromi** [comment] 2020-12-11 08:19
I bet you do :) Unfortunately I have 0 revenus as long as my personal projet does not land (https://game-park.com/), so for now I cannot afford to spend a couple of weeks on another project... but I hope I can do it later on.

Some thoughts though:
- in order to be able to keep a single function `getSession` that can be use on both side, we need a way to use runtime imports in the framework (using `require('...')` on another file). Without runtime imports, the client starts on depending on libraries only available on server side (like 'fs').
I tried it and it does not work after the build with current build configuration.
- The way the "options" object works on server side (injection in API routes only) makes it currently very hard to reuse elsewhere. This should also be refactored into something more reusable.

Also, if the Typescript migration pull request could be integrated, it would be great ;)

**Comment by balazsorban44** [comment] 2020-12-11 14:46
Please keep in mind that we are an open source organization, working on this project in our free time as well. We solely rely on the community to help us out where they can.

I am going to take up this topic the next time I chat with @iaincollins to figure out what we can do here. Thanks for the feedback, it's really helpful!

Regarding TypeScript, again we welcome eager community members to help out pushing stuff they need faster. 😊

**Comment by balazsorban44** [comment] 2021-01-16 01:21
So I had some thoughts on this.

Reusing the options is as simple as moving it into a different file and export it from there. 🙂

getSession is mostly designed to be used from `getServerSideProps`. I cannot remember which thread it was, but the problem is that we cannot access the cookies from there if I remember correctly, which makes it necessary to call the 

/api/auth/session

 endpoint.

You mentioned that maybe a server couldn't make such a request. 
I cannot guess in what scenario a web server could not make requests to itself, do you have an example maybe?


You can also check the implementation of the /api/auth/session handler https://www.github.com/nextauthjs/next-auth/tree/canary/src%2Fserver%2Froutes%2Fsession.js

In case you use a jwt session, and if req.cookies is actually available in `getServerSideProps`, it would be very easy to write a function that takes a req, and extracts/decrypts your session info. Keep in mind that you would loose features like the session expiry update, and at the end of the day, just to spare an extra call to a handler would not seem such a big "design flow" after all. Not to mention that it also handles if you have a database instead of a jwt session.

**Comment by balazsorban44** [comment] 2021-01-17 23:51
So after stumbling upon this tweet thread https://twitter.com/Design__Pattern/status/1350889333960568833?s=19

I think I finally understand your idea/proposal here, thanks! We'll have to rethink this again!

**Comment by fromi** [comment] 2021-01-18 08:36
> I cannot guess in what scenario a web server could not make requests to itself, do you have an example maybe?
I have an error from time to time in my logs indicating this scenario. It is quite rare though, mostly it happens during server startup.

The main issue really is the JWT cookie update, which will not be reflected in the browser when it happens inside the inner call.
Here is one scenario where it is really annoying:

- Put the username inside the JWT cookie, so that it can be displayed without any extra call to the database.
- User update his username, so we need to update the cookie. Unfortunately right now the only available strategy to update the cookie would be using "getSession" on server side. But it won't work because the new cookie will not be forwarded to the browser due to that intermediate API call.

Of course, it is not an easy issue to fix!

**Comment by iaincollins** [comment] 2021-01-18 10:27
> The code for getSession, on server side, is calling the API

This is not a bug, this is absolutely by design and there are a few reasons why it's like this. Pulling in NextAuth.js and database logic into every single route running server side is not desirable, especially on edge clients and on systems with more complex architecture. If we did this it would be impossible to deploy NextAuth.js in some contexts (e.g. edge networks).

> Also, if the Typescript migration pull request could be integrated, it would be great ;)

I have no plans to migrate this project to TypeScript.

> Of course, it is not an easy issue to fix!

If you update the session object it should update globally using events.

I think there is a bug the current event handling that is causing the window which triggers the session update to not receive the event (though any other windows and tabs do), but this is easy to fix - and easy to work around in the interim.

**Closed** 2021-01-19 09:07 UTC
Labels: enhancement, help wanted
