### ISSUE TITLE
Passing additional data and triggering actions after signup

### ISSUE THREAD

**Issue by benjam1n** [nextauthjs/next-auth#2961] opened 2021-10-15 06:55 UTC
### Question 💬

Hi! 

What would be the best way to pass a custom hidden input field value from custom sign in page when using EmailProvider? Just like the `csrfToken` is passed. I want to assign some relational data to the user after sign up. I tried customising the adapter and its createUser function but I was not able to access the extra data there. Also the callback for createUser doesn't exist?

Thanks!

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment] 2021-10-15 07:37
Duplicate of #1069, #1633

**Closed** 2021-10-15 07:38 UTC
Labels: duplicate, question
