### ISSUE TITLE
drizzle-adapter with custom user table?

### ISSUE THREAD

**Issue by socketopp** [nextauthjs/next-auth#9466] opened 2023-12-25 15:28 UTC
Currently when a user is created, adapter-drizzle uses default values `defaultSqliteTableFn` for `users, accounts, sessions, verificationTokens` tables which means if we use a custom oauth provider and extend what the profile function is returning to create a user, none of the data will be added to the users table.

My question is:
**How do we send data to DrizzleAdapter so it creates a custom user?** 

It would be nice to see the documentation updated with this info.

```
export function SQLiteDrizzleAdapter(
  client: InstanceType<typeof BaseSQLiteDatabase>,
  tableFn = defaultSqliteTableFn
): Adapter {
  const { users, accounts, sessions, verificationTokens } =
    createTables(tableFn)

  return {
    async createUser(data) {
      return await client
        .insert(users)
        .values({ ...data, id: crypto.randomUUID() })
        .returning()
        .get()
    },
```

**Update** I finally found a way to override the default tables now.

```
export const tableFn = (table: string) => {
	switch (table) {
		case 'user':
			return users;
		case 'account':
			return accounts;
		case 'session':
			return sessions;
		case 'verificationToken':
			return verificationTokens;
		default:
			throw new Error(`Table ${table} not found`);
	}
};
....
 // eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
adapter: DrizzleAdapter(locals?.D1, tableFn),
```

This was the only way I managed the DrizzleAdapter to override. 
Most solutions I've seen used `export const createTable = sqliteTableCreator((name) => name);` but that one didn't work for me. Any ideas why?

**Comment by riccardoperra** [comment] 2023-12-30 10:27
The issue seems that the adapter is querying from the table it defines (sqlite as example as i'm using that database, but it's the same for pg

https://github.com/nextauthjs/next-auth/blob/9c0de61a55288e7c4f6bdaebc160d033ac39d8f1/packages/adapter-drizzle/src/lib/sqlite.ts#L84

**Comment by gabrielgrover** [comment] 2024-01-13 19:17
> The issue seems that the adapter is querying from the table it defines (sqlite as example as i'm using that database, but it's the same for pg
> 
> https://github.com/nextauthjs/next-auth/blob/9c0de61a55288e7c4f6bdaebc160d033ac39d8f1/packages/adapter-drizzle/src/lib/sqlite.ts#L84

Ran into this today.  Seems to me you just have to copy the adapter and modify it yourself.

**Comment by socketopp** [comment] 2024-01-13 23:27
> > The issue seems that the adapter is querying from the table it defines (sqlite as example as i'm using that database, but it's the same for pg
> > https://github.com/nextauthjs/next-auth/blob/9c0de61a55288e7c4f6bdaebc160d033ac39d8f1/packages/adapter-drizzle/src/lib/sqlite.ts#L84
> 
> Ran into this today. Seems to me you just have to copy the adapter and modify it yourself. Unless I am missing something

That worked for me as well, or using the solution I updated.

**Comment by nahtnam** [comment] 2024-01-25 02:47
@socketopp Are you sure everything works?

https://github.com/nextauthjs/next-auth/blob/d85269d1169d068448b831d2ee9517e4673c78b8/packages/adapter-drizzle/src/lib/pg.ts#L161

This line specifically assumes that the table name is `user` and not `users`

**Comment by socketopp** [comment] 2024-01-25 08:16
> @socketopp Are you sure everything works?
> 
> https://github.com/nextauthjs/next-auth/blob/d85269d1169d068448b831d2ee9517e4673c78b8/packages/adapter-drizzle/src/lib/pg.ts#L161
> 
> This line specifically assumes that the table name is `user` and not `users`

I am not sure I follow. The name of the table is 'user' and the variable is named users.

**Comment by JavanFriedel** [comment] 2024-02-09 01:07
I ran into this today as well when attempting to attach a role to the user object. The problem is, that the drizzleAdapter uses default table definitions when accepting data to the tables to be inserted. 

**Example PG Adapter:**
```js
export function pgDrizzleAdapter(
  client: InstanceType<typeof PgDatabase>,
  tableFn = defaultPgTableFn
): Adapter {
  const { users, accounts, sessions, verificationTokens } =
    createTables(tableFn)

  return {
    async createUser(data) {
      return await client
        .insert(users)
        .values({ ...data, id: crypto.randomUUID() })
        .returning()
        .then((res) => res[0] ?? null)
    },
```

**createTables()**
```js
export function createTables(pgTable: PgTableFn) {
  const users = pgTable("user", {
    id: text("id").notNull().primaryKey(),
    name: text("name"),
    email: text("email").notNull(),
    emailVerified: timestamp("emailVerified", { mode: "date" }),
    image: text("image"),
  })
```
It looks like the function can take an optional pgTable function, but I fail to see how this can be used to motify the default table schema included. 

**My Solution**
```js
function customAdapter(): Adapter {
  const adapter = DrizzleAdapter(db);

  // Overwrite createUser method on adapter
  adapter.createUser = async (data): Promise<AdapterUser> => {

    const dataEntered = await db
      .insert(users)
      .values({ ...data, id: crypto.randomUUID() })
      .returning()
      .then((res) => res[0] ?? null);

    if (!dataEntered) {
      throw new Error("User Creation Failed");
    }

    return dataEntered;
  };

  return {
    ...adapter,
  };
}
```
I simply overwrite the existing createUser method on the adapter, with the exactly the same function, but I pass my own users schema into the db.insert(). I can then pass my own adapter into the next-auth config to have functional additional roles. 

It might be nice if we could pass an optional schema to the adapter to use instead, similair to the drizzle-kit config.

**Comment by adriangalilea** [comment] 2024-03-17 23:44
> I ran into this today as well when attempting to attach a role to the user object. The problem is, that the drizzleAdapter uses default table definitions when accepting data to the tables to be inserted.
> 
> **Example PG Adapter:**
> 
> ```js
> export function pgDrizzleAdapter(
>   client: InstanceType<typeof PgDatabase>,
>   tableFn = defaultPgTableFn
> ): Adapter {
>   const { users, accounts, sessions, verificationTokens } =
>     createTables(tableFn)
> 
>   return {
>     async createUser(data) {
>       return await client
>         .insert(users)
>         .values({ ...data, id: crypto.randomUUID() })
>         .returning()
>         .then((res) => res[0] ?? null)
>     },
> ```
> 
> **createTables()**
> 
> ```js
> export function createTables(pgTable: PgTableFn) {
>   const users = pgTable("user", {
>     id: text("id").notNull().primaryKey(),
>     name: text("name"),
>     email: text("email").notNull(),
>     emailVerified: timestamp("emailVerified", { mode: "date" }),
>     image: text("image"),
>   })
> ```
> 
> It looks like the function can take an optional pgTable function, but I fail to see how this can be used to motify the default table schema included.
> 
> **My Solution**
> 
> ```js
> function customAdapter(): Adapter {
>   const adapter = DrizzleAdapter(db);
> 
>   // Overwrite createUser method on adapter
>   adapter.createUser = async (data): Promise<AdapterUser> => {
> 
>     const dataEntered = await db
>       .insert(users)
>       .values({ ...data, id: crypto.randomUUID() })
>       .returning()
>       .then((res) => res[0] ?? null);
> 
>     if (!dataEntered) {
>       throw new Error("User Creation Failed");
>     }
> 
>     return dataEntered;
>   };
> 
>   return {
>     ...adapter,
>   };
> }
> ```
> 
> I simply overwrite the existing createUser method on the adapter, with the exactly the same function, but I pass my own users schema into the db.insert(). I can then pass my own adapter into the next-auth config to have functional additional roles.
> 
> It might be nice if we could pass an optional schema to the adapter to use instead, similair to the drizzle-kit config.

For whatever reason this does not work for me, despite creating an adapter that overrides createUser, I still get:
```
[auth][details]: {
  "name": "ResponseError",
  "code": "SQLITE_UNKNOWN",
  "proto": {
    "message": "SQLite error: no such table: user",
    "code": "SQLITE_UNKNOWN"
  }
  ```

**Comment by adriangalilea** [comment] 2024-03-18 19:20
@JavanFriedel 
If you do that then you can't do module augmentation on session.

> Adapter from next-auth/adapters is moved to @auth/core/adapters. If you are creating a custom adapter, use @auth/core instead of next-auth.

I ran into that issue while implementing your solution, had to create the adpater for all the methods, else it fails.

**Comment by JavanFriedel** [comment] 2024-03-18 20:12
@adriangalilea 
I believe I am importing directly from @auth for the types as well as the drizzle adapter directly. 
```js
import { DrizzleAdapter } from "@auth/drizzle-adapter";
import type { Adapter, AdapterUser } from "@auth/core/adapters";
```

Essentially the createUser is the only method I needed to modify for my use case, and the rest should be in-tact as I am spreading the methods available on the original adapter, and returning it. 

If I needed to modify any of the other methods like update etc, I would have to modify those as well. At some point it would make more sense to just write my own adapter from scratch as outlined in the auth.js docs.

**Comment by adriangalilea** [comment] 2024-03-18 21:04
@JavanFriedel Yeah, but what I'm saying is that if you both:
- use a custom adapter
- do module augmentation
You'll get problems like session not having the properties you want it to.
You can take a look at [this gist](https://gist.github.com/adriangalilea/6601f0fcde1a2225977054d79d2a0d4e)

If I remove the other methods or spread them, my printed session is:
```
{
  "user": {
    "id": "...",
    "name": "Adrian Galilea",
    "email": "adriangalilea@gmail.com",
    "emailVerified": null,
    "image": null
  },
  "sessionToken": "...",
  "userId": "...",
  "expires": "2024-04-17T21:00:15.584Z"
}
```

However if I copy paste them all, from the basic sqlite adapter, it works as expected.
```
{
  "user": {
    "id": "",
    "name": "Adrian Galilea",
    "email": "adriangalilea@gmail.com",
    "emailVerified": null,
    "image": null,
    "gh_username": "adriangalilea",
    "gh_id": "",
    "gh_image": "https://avatars.githubusercontent.com/u/90320947?v=4",
    "country_code": "XX",
    "avatar": null,
    "created_at": "2024-03-18 21:02:08",
    "updated_at": "2024-03-18 21:02:08",
    "bio": null,
    "website": null,
    "twitter": null,
    "github": null,
    "youtube": null
  },
  "sessionToken": "",
  "userId": "",
  "expires": "2024-04-17T21:02:08.645Z"
}
```

It took  me way too much time to figure that out, it makes no sense.

>Adapter from next-auth/adapters is moved to @auth/core/adapters. If you are creating a custom adapter, use @auth/core instead of next-auth.

This is the only relevant ambiguous docs I see, and I fail to understand how can I bypass having to copypaste all the methods I'm not using.

**Comment by ndom91** [comment] 2024-04-12 12:38
Hey folks, there is a rewrite of the drizzle-adapter in a [PR](https://github.com/nextauthjs/next-auth/pull/10479) which should be merged shortly. This one doesn't have the table names hardcoded and allows passing custom schemas :heart:

**Closed by ndom91** 2024-04-12 12:38 UTC
Labels: documentation, triage

**Comment by ldenblyd** [comment] 2024-07-28 19:35
for those who wondering if you just want to retrieve the whole user table content you can setup custom shema like that 


`import NextAuth from "next-auth"
import Google from "next-auth/providers/google"
import { DrizzleAdapter } from "@auth/drizzle-adapter"
import { db, accounts, sessions, users, verificationTokens } from "./schema"
 
export const { handlers, auth } = NextAuth({
  adapter: DrizzleAdapter(db, {
    usersTable: users,
    accountsTable: accounts,
    sessionsTable: sessions,
    verificationTokensTable: verificationTokens,
  }),
  providers: [Google],
})
`

see [https://authjs.dev/getting-started/adapters/drizzle](url)

**Comment by MikeLautensack** [comment] 2024-08-03 01:00
> for those who wondering if you just want to retrieve the whole user table content you can setup custom shema like that
> 
> ```js
> import NextAuth from "next-auth"
> import Google from "next-auth/providers/google"
> import { DrizzleAdapter } from "@auth/drizzle-adapter"
> import { db, accounts, sessions, users, verificationTokens } from "./schema"
>  
> export const { handlers, auth } = NextAuth({
>   adapter: DrizzleAdapter(db, {
>     usersTable: users,
>     accountsTable: accounts,
>     sessionsTable: sessions,
>     verificationTokensTable: verificationTokens,
>   }),
>   providers: [Google],
> })
> ```
> 
> see [https://authjs.dev/getting-started/adapters/drizzle](url)

This was working for me however it suddenly stopped working for me 

![image](https://github.com/user-attachments/assets/def94824-4ffd-4f2f-ace6-072b389a153f)

![image](https://github.com/user-attachments/assets/2faf0ef4-ec39-44a9-9ad6-b4181f0816af)


![image](https://github.com/user-attachments/assets/86dbb544-21a7-4d25-a73f-acbe0924a7ab)


Seems to have something to do with the id but not sure really.

**Comment by josephworks** [comment] 2024-08-06 08:38
> > for those who wondering if you just want to retrieve the whole user table content you can setup custom shema like that
> > ```js
> > import NextAuth from "next-auth"
> > import Google from "next-auth/providers/google"
> > import { DrizzleAdapter } from "@auth/drizzle-adapter"
> > import { db, accounts, sessions, users, verificationTokens } from "./schema"
> >  
> > export const { handlers, auth } = NextAuth({
> >   adapter: DrizzleAdapter(db, {
> >     usersTable: users,
> >     accountsTable: accounts,
> >     sessionsTable: sessions,
> >     verificationTokensTable: verificationTokens,
> >   }),
> >   providers: [Google],
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > see [https://authjs.dev/getting-started/adapters/drizzle](url)
> 
> This was working for me however it suddenly stopped working for me
> 
> ![image](https://private-user-images.githubusercontent.com/110644605/354776419-def94824-4ffd-4f2f-ace6-072b389a153f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzM4MDcsIm5iZiI6MTcyMjkzMzUwNywicGF0aCI6Ii8xMTA2NDQ2MDUvMzU0Nzc2NDE5LWRlZjk0ODI0LTRmZmQtNGYyZi1hY2U2LTA3MmIzODlhMTUzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwODM4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2JiZDU3YWQwZDc4NWU1YzY2MTk2ZGVkYzQ5MWIxNWVmOGZhZjU3Yzk3NDIwN2I1MzliMTIyZTc1MTcyZDU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jAQd7b8tMizV6WhwLcuzPw5Z5fEmfrTM3bfSKYBfXfw)
> 
> ![image](https://private-user-images.githubusercontent.com/110644605/354776636-2faf0ef4-ec39-44a9-9ad6-b4181f0816af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzM4MDcsIm5iZiI6MTcyMjkzMzUwNywicGF0aCI6Ii8xMTA2NDQ2MDUvMzU0Nzc2NjM2LTJmYWYwZWY0LWVjMzktNDRhOS05YWQ2LWI0MTgxZjA4MTZhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwODM4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzQ5ZDhlZDA2NjQ2MjlkMDBiNGVkMDExMWY0MThiODA0NjVkMGYyOTE5OGVkMDQ3MWZhZWU2ZjE1MGQwNGY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YIbtP7iFUpga6DgdS4vPkWVPhqtL6YzRZkRy_SD6IZc)
> 
> ![image](https://private-user-images.githubusercontent.com/110644605/354777126-86dbb544-21a7-4d25-a73f-acbe0924a7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzM4MDcsIm5iZiI6MTcyMjkzMzUwNywicGF0aCI6Ii8xMTA2NDQ2MDUvMzU0Nzc3MTI2LTg2ZGJiNTQ0LTIxYTctNGQyNS1hNzNmLWFjYmUwOTI0YTdhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwODM4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDA1NDFhZTgwNDNlMzI5ZTBiMGQzNzMxYTQ5ZDdmMmE0MWI2YmMxNjQ5Mzg4ZTMyNmIzOTIwM2Q4NjU0MzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uKu3iTZWB3f3pH0nIlfnXRKPltrAEBRgbOWFRWSmweA)
> 
> Seems to have something to do with the id but not sure really.

Yes after updating dependencies I had the same issue.
