### ISSUE TITLE
Getting "Error: Cannot find module 'next/headers'" on building the app

### ISSUE THREAD

**Issue by nike1v** [nextauthjs/next-auth#6559] opened 2023-01-30 01:08 UTC
### Question 💬

I have updated the next-auth to the latext version (4.19.0) and still get this error when tying to build the app with next 12.
I have tried to use this when the next-auth version was 4.16.0 and I saw this issue for the first time. I saw the issue here that it should be fixed, but I assume that it is not and to use next-auth 4.16+ I should use next13, am I right?
Hope on your help.

### How to reproduce ☕️

run  - npm install next-auth@latest next@12.x.x and try to build the application

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment] 2023-01-30 01:32
FWIW, this is a duplicate of #5743, but it seems like multiple people are reporting issues, so I'll leave this open until someone gives us a reproduction.

**Comment by AliHoussein** [comment] 2023-01-30 06:27
I have the same issue and seem to have pinpointed the culprit in my case.
It seems the middleware does not work properly.

`package.json`
```
    "jsonwebtoken": "^9.0.0",
    "next": "^12.3.4",
    "next-auth": "^4.19.0",
```

I use a custom encode/decode functions in `[...nextauth].ts`
```
import jwt from 'jsonwebtoken';
import NextAuth, { NextAuthOptions } from 'next-auth';
import { JWTDecodeParams, JWTEncodeParams } from 'next-auth/jwt';

jwt: {
    // You can define your own encode/decode functions for signing and encryption
    async encode({ secret, token }: JWTEncodeParams): Promise<String> {
      const jwtClaims = {
        id: token?.id,
        sub: token?.sub,
        name: token?.name,
        email: token?.email,
        picture: token?.picture,
        iat: Math.floor(Date.now() / 1000),
        exp: Math.floor(Date.now() / 1000) + 24 * 60 * 60, //1 day
        'https://hasura.io/jwt/claims': {
          'x-hasura-allowed-roles': ['user'],
          'x-hasura-default-role': 'user',
          'x-hasura-role': 'user',
          'x-hasura-user-id': token?.id,
        },
      };
      const encodedToken = jwt.sign(jwtClaims, secret, { algorithm: 'HS256' });
      return encodedToken;
    },
    async decode({ secret, token }: JWTDecodeParams) {
      const decodedToken = jwt.verify(token, secret, { algorithms: ['HS256'] });
      return decodedToken as any;
    },
  },
```

Also have a middleware in `middleware.ts`
```
import { withAuth } from 'next-auth/middleware';

import { authOptions } from './pages/api/auth/[...nextauth]';

// More on how NextAuth.js middleware works: https://next-auth.js.org/configuration/nextjs#middleware
export default withAuth({
  jwt: { decode: authOptions.jwt?.decode },
  callbacks: {
    authorized({ req, token }) {
      console.log(req, token);
      // `/admin` requires admin role
      if (req.nextUrl.pathname === '/backoffice') {
        return token?.userRole === 'admin';
      }
      return !!token;
    },
  },
});

export const config = { matcher: ['/backoffice', '/profile'] };
```

If I remove `export const config = { matcher: ['/admin', '/me'] };` OR try to go through a protected URL it crashes the server with the following error

```
error - ./node_modules/next-auth/next/index.js:90:6
Module not found: Can't resolve 'next/headers'

Import trace for requested module:
./node_modules/next-auth/index.js
./pages/api/auth/[...nextauth].ts
./middleware.ts
```

Also I have few type issues for encode and decode (if I remove `as any`) in `[...nextauth].ts`

```
Type '({ secret, token }: JWTEncodeParams) => Promise<String>' is not assignable to type '(params: JWTEncodeParams) => Awaitable<string>'.
  Type 'Promise<String>' is not assignable to type 'Awaitable<string>'.
    Type 'Promise<String>' is not assignable to type 'PromiseLike<string>'.
      Types of property 'then' are incompatible.
        Type '<TResult1 = String, TResult2 = never>(onfulfilled?: (value: String) => TResult1 | PromiseLike<TResult1>, onrejected?: (reason: any) => TResult2 | PromiseLike<...>) => Promise<...>' is not assignable to type '<TResult1 = string, TResult2 = never>(onfulfilled?: (value: string) => TResult1 | PromiseLike<TResult1>, onrejected?: (reason: any) => TResult2 | PromiseLike<TResult2>) => PromiseLike<...>'.
          Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
            Types of parameters 'value' and 'value' are incompatible.
              Type 'String' is not assignable to type 'string'.
                'string' is a primitive, but 'String' is a wrapper object. Prefer using 'string' when possible.
```
```
Type '({ secret, token }: JWTDecodeParams) => Promise<string | JwtPayload>' is not assignable to type '(params: JWTDecodeParams) => Awaitable<JWT>'.
  Type 'Promise<string | JwtPayload>' is not assignable to type 'Awaitable<JWT>'.
    Type 'Promise<string | JwtPayload>' is not assignable to type 'JWT'.
      Index signature for type 'string' is missing in type 'Promise<string | JwtPayload>'.
```

It feels also that the documentation would be more helpful if a bit more detailed:
* withAuth doesn't call the decode function https://next-auth.js.org/configuration/nextjs#custom-jwt-decode-method and 
* how to get this JWT object? https://next-auth.js.org/configuration/options#override-jwt-encode-and-decode-methods

**Comment by balazsorban44** [comment] 2023-01-30 10:47
please add a full (but minimal reproduction), preferably a public github repository, not just snippets.

**Closed** 2023-02-28 11:49 UTC
Labels: question, incomplete

**Comment by moo2u2** [comment] 2023-03-28 00:52
I have created a minimal reproduction of my current project's setup which can reproduce the issue both on build and run.
https://github.com/moo2u2/next-auth-issue-6559.
If anyone can assist I would be extremely grateful, as this is currently blocking us.

**Comment by mayank1513** [comment] 2024-02-23 09:41
I am trying to deploy https://github.com/mayank1513/nextjs-themes-ultralight to Vercel.

All the examples and the library are built very well locally. However, on Vercel it throws this error - "Type error: Cannot find module 'next/headers' or its corresponding type declarations."

at ../../lib/nthul/src/server/server-target/server-target.tsx:2:25
