### ISSUE TITLE
CallbackRouteError on Credentials when following docs

### ISSUE THREAD

**Issue by theswampire** [nextauthjs/next-auth#11074] opened 2024-06-04 17:50 UTC
### Provider type

Credentials

### Environment

```
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-1360P
    Memory: 10.10 GB / 15.47 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
    pnpm: 9.1.4 - ~/.nvm/versions/node/v20.14.0/bin/pnpm
  npmPackages:
    next: 14.2.3 => 14.2.3 
    next-auth: 5.0.0-beta.19 => 5.0.0-beta.19 
    react: ^18 => 18.3.1 

```

### Reproduction URL

https://github.com/theswampire/authjs-bug-reproduction

### Describe the issue

When using the Credentials Provider, submitting a wrong password throws an CallbackRouteError. I tested it on 5.0.0-beta.18, 17 and 16 too but they throw CredentialsSignIn instead. 
I followed the v5 docs for setting up Nextjs and the Credentials Provider step by step thus this should be unexpected behaviour.

This is the `auth.ts` file:
```typescript
// auth.ts
import NextAuth from "next-auth";
import Credentials from "next-auth/providers/credentials";

export const { handlers, signIn, signOut, auth } = NextAuth({
  providers: [
    Credentials({
      credentials: {
        password: {},
      },

      authorize: async (credentials) => {
        if (credentials.password !== "password") {
          return null;
        }
        return { id: "admin", name: "admin" };
      },
    }),
  ],

  pages: {
    signIn: "/signin",
  },
});
```

The SignIn page looks like this:
```tsx
import { signIn } from "@/auth";

export default function SignIn() {
  return (
    <form
      className="flex flex-col max-w-sm gap-2"
      action={async (formData) => {
        "use server";
        await signIn("credentials", formData);
      }}
    >
      <label>
        Password
        <input name="password" type="password" className="border" />
        <input name="redirectTo" type="hidden" value="/secure" />
      </label>
      <span>Password is &quot;password&quot;</span>
      <button className="bg-neutral-300">Sign In</button>
    </form>
  );
}
```
I tried to wrap the signIn call in a try-catch like in #11010 but that obviously didn't fix the underlying issue.

According to the documentation, the CallbackRouteError using the Credentials Provider means that either the `authorize` or another callback throws but I didn't overwrite any callbacks nor should `authorize` throw anything. Furthermore, if I remember correctly, when setting `redirect` to false, the `SignInResponse` contained `ok: true` and a Configuration error which I find odd.

### How to reproduce

Enter anything but the correct password "password" and then the exception should be thrown.
Using the correct password works just fine.

### Expected behavior

Don't throw an exception.

**Comment by aptof** [comment] 2024-06-05 08:11
**Version 5.0.0-beta.19** is causing the same problem to me.
To resolve this issue, you can try utilizing version **5.0.0-beta.18** as a temporary solution till the developers fix it.

**Comment by shunkica** [comment] 2024-06-07 08:12
For me, just returning null from `authorize()` throws the `CallbackRouteError`

**Comment by trulysinclair** [comment] 2024-06-07 23:34
Same here, either returning `null` or throwing the error per the example will break

**Comment by bibaswan7** [comment] 2024-06-08 17:01
i am facing the exact same issue

**Comment by ondery** [comment] 2024-06-09 07:03
me too... :(

**Comment by bibaswan7** [comment] 2024-06-09 08:49
I am not sure if its done intentionally but I went through the next-auth code and figured out that, even though CredentialsSignin error is being thrown, it is then passed to CallbackRouteError, which is why we are getting CallbackRouteError.
`
catch (e) {
        if (e instanceof AuthError)
            throw e;
        const error = new CallbackRouteError(e, { provider: provider.id });
        logger.debug("callback route error details", { method, query, body });
        throw error;
    }
`

here as you can see, catch recieves CredentialsSignin error. Since it is an instance of Error and not of AuthError, it skips the conditional, then rest is pretty much self explanatory.

In order to solve this issue, if its an CredentialsSignin error, then instead of checking error.type === 'CredentialsSignin', what you can do is 
`
error.cause.err.code === 'credentials'
`

**Comment by jessethomson** [comment] 2024-06-11 05:33
Experiencing the same issue as others: If I return null from authorize, it throws this error.

This issue only started happening after upgrading to the latest beta. I went from `5.0.0-beta.4` to `5.0.0-beta.19` so I'm not sure which version in between those specifically causes this issue.

**Comment by nprdservice3** [comment] 2024-06-11 07:43
> I am not sure if its done intentionally but I went through the next-auth code and figured out that, even though CredentialsSignin error is being thrown, it is then passed to CallbackRouteError, which is why we are getting CallbackRouteError. `catch (e) { if (e instanceof AuthError) throw e; const error = new CallbackRouteError(e, { provider: provider.id }); logger.debug("callback route error details", { method, query, body }); throw error; }`
> 
> here as you can see, catch recieves CredentialsSignin error. Since it is an instance of Error and not of AuthError, it skips the conditional, then rest is pretty much self explanatory.
> 
> In order to solve this issue, if its an CredentialsSignin error, then instead of checking error.type === 'CredentialsSignin', what you can do is `error.cause.err.code === 'credentials'`

thanks it worked

**Comment by ondery** [comment] 2024-06-11 09:57
> I am not sure if its done intentionally but I went through the next-auth code and figured out that, even though CredentialsSignin error is being thrown, it is then passed to CallbackRouteError, which is why we are getting CallbackRouteError. `catch (e) { if (e instanceof AuthError) throw e; const error = new CallbackRouteError(e, { provider: provider.id }); logger.debug("callback route error details", { method, query, body }); throw error; }`
> 
> here as you can see, catch recieves CredentialsSignin error. Since it is an instance of Error and not of AuthError, it skips the conditional, then rest is pretty much self explanatory.
> 
> In order to solve this issue, if its an CredentialsSignin error, then instead of checking error.type === 'CredentialsSignin', what you can do is `error.cause.err.code === 'credentials'`

When done this way, it will give the same error again if there is a connection problem with the database.

**Comment by danbeo95** [comment] 2024-06-12 03:39
The same issue with 5.0.0-beta.19

**Comment by azizali** [comment] 2024-06-13 02:26
same issue for me.

**Comment by ondery** [comment] 2024-06-13 04:31
> @ondery what error are you getting? mind sharing the code snippets?

@bibaswan7 error.cause.err.code === 'credentials' will give true in case of database connection problems too unfortunately.

**Comment by yukinoyuu** [comment] 2024-06-14 16:23
@bibaswan7 I came to the same conclusion, but since I'm using typescript, it screams at me saying that property of code does not exist on type Error.  Does anyone know a way to do typing properly with this weird wrapping, as well as @ondery mentioned, a way to disambiguate this error further?

I looked into the typing issue a bit more and found commit ```d089923``` by , where the typing of CredentialsSignin is changed from extending SignInError to extending Error. This further ambiguities the typing on the error. I found the issue for it in #11155

**Comment by Ali-Raza764** [comment] 2024-06-15 04:42
I think I have a fix of just signing in and handling an error if the password is incorrect. Instead of using signIn() function from the @/auth.js file we can do somthing like this in the signinForm:
```"use client";
import { signIn } from "next-auth/react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import Providers from "../components/Providers";

const SignInForm = () => {
  const [loading, setLoading] = useState(false);
  const router = useRouter();
  const [error, setError] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();
    const email = e.target.email.value;
    const password = e.target.password.value;

    try {
      setLoading(true);
      setError("");
      const res = await signIn("credentials", {
        redirect: false,
        email,
        password,
      });

      //* The res here has no credentials data only error:true or error:null so we can manage the state based on that
      //* Next auth does not send the data due to security reasons
      if (res.error === null) {
        router.push("/protected");
      }
      if (res.error) {
        setError("Check Your Email Or Password");
      }
    } catch (error) {
      console.error(error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="shadow bg-gray-400 p-4 rounded-md m-2 min-w-[20rem]">
      <form onSubmit={handleSubmit} className="flex flex-col gap-4">
        <input
          type="text"
          name="email"
          placeholder="Email"
          className="border-b-2 border-gray-400 focus:border-red-500 outline-none  p-2 transition disabled:border-none disabled:bg-gray-400"
          required
          disabled={loading}
        />
        <input
          type="password"
          name="password"
          placeholder="Password"
          className="border-b-2 border-gray-400 focus:border-red-500 outline-none  p-2 transition disabled:border-none disabled:bg-gray-400"
          required
          disabled={loading}
        />
        <p className="text-red-500">{error}</p>
        <button
          type="submit"
          className="p-2 px-4 bg-gray-800 rounded-md text-white disabled:border-none disabled:bg-gray-600"
          disabled={loading}
        >
          Submit
        </button>
      </form>
      <div className="my-2 w-full text-center"> Or</div>
      <div className="w-full">
        <Providers />
      </div>
      <Link href="/auth/signup">SignUp</Link>
    </div>
  );
};

export default SignInForm;
```
If the signIn() functions throws an error Then it means that The credentials are invalid...
And If you are storing your user credentials in a database you can handle that authentication from the auth.js file using a server action:
```import NextAuth from "next-auth";
import GitHub from "next-auth/providers/github";
import Google from "next-auth/providers/google";
import CredentialsProvider from "next-auth/providers/credentials";
import {
  SignInWithEmailAndPassword,
  oauthSignIn,
} from "@/actions/user/user.actions";

const providers = [
  Google,
  GitHub,
  CredentialsProvider({
    name: "Credentials",
    credentials: {
      email: { label: "Email", type: "email" },
      password: { label: "Password", type: "password" },
    },
    async authorize(credentials) {
      const user = await SignInWithEmailAndPassword(credentials); // User verification logic
      if (user.status === 400) {
        return null;
      }
      return user.data;
    },
  }),
];

export const providerMap = providers.map((provider) => {
  if (typeof provider === "function") {
    const providerData = provider();
    return { id: providerData.id, name: providerData.name };
  } else {
    return { id: provider.id, name: provider.name };
  }
});

export const { handlers, auth, signIn, signOut, unstable_update } = NextAuth({
  providers,
  pages: {
    signIn: "/auth/sign-in",
  },
  callbacks: {
    async signIn({ user, account }) {
      if (account.provider === "google" || account.provider === "github") {
        const { name, email, image } = user;
        const payload = {
          name,
          email,
          avatar: image,
          authType: "Oauth",
        };

        const res = await oauthSignIn(payload);
        user.id = res.data._id.toString();
        user.isVerified = res.data.isVerified;
        user.image = res.data.avatar;

        return user;
      }
      // Default to allow sign-in
      return user;
    },
    async jwt({ trigger, token, user }) {
      // Add user information to the token during sign-in
      if (trigger === "update") {
        token.isVerified = session.user.isVerified;
      }
      if (user) {
        console.log(user);
        const id = user._id?.toString() || user.id;
        token.id = id;
        token.email = user.email;
        token.name = user.name;
        token.isVerified = user.isVerified;
        token.picture = user.avatar || user.image;
      }
      return token;
    },
    async session({ session, token }) {
      session.user.id = token.id;
      session.user.email = token.email;
      session.user.name = token.name;
      session.user.image = token.picture;
      session.user.isVerified = token.isVerified;
      return session;
    },
  },
});```
I think this pretty much works for now. If you want to see detailed implementation for this you can checkout this [repo](https://github.com/Ali-Raza764/next-auth-tookit)

**Comment by yukinoyuu** [comment] 2024-06-15 14:20
Yeah @Ali-Raza764 That's exactly what I do currently, but I just want a bit more fine grain control over the error, and it is supposed to work, but just doesn't. For example, what if my API endpoint became unreachable and just timed out.. It would still say to check the credentials on the client side, even if they are correct. That would lead the user to try a bunch of times and then try to reset the password, which is not something I would want. Instead I want to distinguish whether it's because of the credentials (user does not exist on the token in the Callback). I think this could just be fixed with the typing, as @bibaswan7 said.

The issue for the broken types is #11155.

The types are broken in #11050

<img width="852" alt="Screenshot 2024-06-14 at 11 31 09 AM" src="https://github.com/nextauthjs/next-auth/assets/56956339/f36c53e6-185a-4837-ac8a-ed0ea8b8b917">

**Comment by Ali-Raza764** [comment] 2024-06-16 03:35
Ok  I do understand that. So we can wait until the new release makes a fix ?

**Comment by riky-on-devcra** [comment] 2024-06-19 02:29
any updates?

**Comment by sambecker** [comment] 2024-06-21 00:52
In case it's helpful, can confirm that Credentials-based error handling broke for me when switching to from `beta.18` to `beta.19`.

Errors previously classified `CredentialsSignin` became classified `CallbackRouteError`.

**Comment by Ali-Raza764** [comment] 2024-06-21 06:13
What if we can customize the authorize() function to return custom errors like this issue https://github.com/nextauthjs/next-auth/pull/9871

**Comment by TheRealSageKing** [comment] 2024-06-23 01:44
I rolled back from 5.0.0-beta.19 to 5.0.0-beta.18 and it worked for me. Clearly its a bug on 5.0.0-beta.19 so until a new update comes I ll stick to the previous version

**Comment by ethanforvest** [comment] 2024-06-24 20:51
> I rolled back from 5.0.0-beta.19 to 5.0.0-beta.18 and it worked for me. Clearly its a bug on 5.0.0-beta.19 so until a new update comes I ll stick to the previous version

Yeah, downgrading fixed the issue for me too

**Comment by cherylli** [comment] 2024-06-28 14:51
> I tested it on 5.0.0-beta.18, 17 and 16 too but they throw CredentialsSignIn instead.
Exactly same issue as OP, downgrading to beta.18 didn't work

```
"next": "^14.2.4",
"next-auth": "^5.0.0-beta.19",
```

**Comment by TheRealSageKing** [comment] 2024-07-01 02:29
use `npm install next-auth@5.0.0-beta.18` that should help. make sure your provider authorize returns null or user data

**Comment by SasquatchLV** [comment] 2024-07-01 07:42
> use `npm install next-auth@5.0.0-beta.18` that should help. make sure your provider authorize returns null or user data

So which version of the code is working for you now?? Can you show an example how you got the custom errors?

**Comment by stephendewyer** [comment] 2024-07-01 15:50
I am facing a similar issue with @auth/core:0.31.0 and @auth/sveltekit:1.1.0.  The response object for signIn is always returning no error when user submits invalid credentials.
The issue in more detail: https://github.com/nextauthjs/next-auth/issues/10931.

**Comment by NitanJana** [comment] 2024-07-03 05:53
> use `npm install next-auth@5.0.0-beta.18` that should help. make sure your provider authorize returns null or user data

this fixed it for me, thanks.

**Comment by cherylli** [comment] 2024-07-07 04:51
> > I tested it on 5.0.0-beta.18, 17 and 16 too but they throw CredentialsSignIn instead.
> 
> Exactly same issue as OP, downgrading to beta.18 didn't work
> 
> ```
> "next": "^14.2.4",
> "next-auth": "^5.0.0-beta.19",
> ```

Tried again a week later with the same code and `yarn add next-auth@5.0.0-beta.18` worked for me. 

Also don't throw any other errors except `CredentialSignin` error, it gives configuration error 

so either `null` or `CredentialSignin` error will work for `next-auth@5.0.0-beta.18`

**Comment by dynamiclynk** [comment] 2024-07-07 12:53
downgrading from  "next-auth": "^5.0.0-beta.19" to 18 allows a custom error responses to throw and handled in the client. Can't understand abstracting this away from the developer 😕, at least default it to off and allow us to specify an process env var to enable throwing core authorize response and any auth life cycle hook.

**Comment by nkghis** [comment] 2024-07-09 12:18
> use `npm install next-auth@5.0.0-beta.18` or `yarn add next-auth@5.0.0-beta.18` that should help. make sure your provider authorize returns null or user data
> 
> edit: I forgot to add yarn for yarn users. my bad

thanks that is work well now

**Comment by mehrwarz** [comment] 2024-07-09 23:04
I was able to throw my custom error in server side and send message to client. here it is: https://stackoverflow.com/questions/78627862/next-auth-signin-return-errorconfiguration-in-responce-for-invalid-credenti/78723173#78723173

**Comment by Lucifer472** [comment] 2024-07-10 05:26
just downgrade to `"next-auth": "^5.0.0-beta.18"` it will fix the issue i was having the same problem.

To fix it first remove next-auth from package json then run npm i then install `npm install next-auth@5.0.0-beta.18` 
and make sure to return null with authorize function or if you want use custom error msg like this

```
import { CredentialsSignin } from "next-auth";

class WrongPassword extends CredentialsSignin {
  code = "Wrong_Password";
}

const isMatch = await bcrypt.compare(password, user.password);
if (!isMatch) throw new WrongPassword();
```

inside of the login function

```
 try {
    await signIn("credentials", {
      redirect: true,
      redirectTo: defaultRedirect,
      email,
      password,
    });
  } catch (error) {
    if (error instanceof AuthError) {
      switch (error.type) {
        case "CredentialsSignin":
          return "Invalid credentials";
        case "CallbackRouteError":
          return "Something went Wrong!";
        default:
          return "Something went wrong";
      }
    }
    throw error;
  }
```

i hope this helps

**Comment by liamicy3aaa** [comment] 2024-07-17 21:51
Was also seeing this issue and thought it was me! Downgrading to 5.0.0-beta.18 resolved the issue for me!

Thanks.

**Comment by mehrwarz** [comment] 2024-07-19 01:47
I had the same error in Version of 5.00-beta 18 and 5.0.0-beta 19
Finaly i was able to handle my custom error here and i test it out in both versions.
https://stackoverflow.com/questions/78627862/next-auth-signin-return-errorconfiguration-in-responce-for-invalid-credenti/78673275#78673275

Please let me know if you have any comments.

Thanks and regards
Emran

________________________________

**Comment by ThangHuuVu** [comment] 2024-07-27 06:32
hi all, 🙇‍♂️ so I think it would be best to revert #11050 and fix this regression issue first, and revisit the issue that @ndom91 attempted to fix on that PR later on - please expect a release to be cut soon, thanks for your patience 🙏

**Closed** 2024-07-27 13:54 UTC
Labels: bug, providers, triage

**Comment by Ashraful-Mijan** [comment] 2024-08-22 07:15
> > use `npm install next-auth@5.0.0-beta.18` that should help. make sure your provider authorize returns null or user data
> 
> this fixed it for me, thanks.

Can you show  how you got the  errors?

**Comment by luco** [comment] 2024-10-08 14:57
For anyone coming here, just follow this one, as mentioned by others:

https://stackoverflow.com/questions/78627862/next-auth-signin-return-errorconfiguration-in-responce-for-invalid-credenti/78673275#78673275

**Comment by maxpaleo** [comment] 2024-12-22 00:04
I've been working with Next auth for about a week now, and at this point, I wonder why people actually even use this library. I mean, I am guessing that everyone starts using it to integrate auth in their apps quickly, and then end up on spending hours working around the countless issues? 

Next, auth seems to be written by a team that believes their definite opinions on handling auth are the only way to handle it. The library is the exact opposite of "Flexible." 

I guess it makes sense if you only want to use some Oauth login with 0 interactions with the DB, but for anything else, why on earth do we keep working around their "single opinion auth flow" to be able to implement authentication in our apps? 

And if only the docs actually mentioned the hundreds of roadblocks they've implemented to allow for custom behavior, but no, absolutely nothing. 

It's a shame Lucia has been deprecated. I can't wait for someone to release a complete, unopinionated auth lib that is actually built around the idea of a lib, not some single team's opinionated piece of code that seriously lacks documentation.

For anyone reading this, if you haven't spend more than a few hours on resolving next auth issues: I'd recommend staying away, and simply build auth from scratch. You'll spend less time implementing a single JWT flow, interactions with your db, and error handling.

**Comment by cool3rain** [comment] 2024-12-22 01:07
> I've been working with Next auth for about a week now, and at this point, I wonder why people actually even use this library. I mean, I am guessing that everyone starts using it to integrate auth in their apps quickly, and then end up on spending hours working around the countless issues?
> 
> Next, auth seems to be written by a team that believes their definite opinions on handling auth are the only way to handle it. The library is the exact opposite of "Flexible."
> 
> I guess it makes sense if you only want to use some Oauth login with 0 interactions with the DB, but for anything else, why on earth do we keep working around their "single opinion auth flow" to be able to implement authentication in our apps?
> 
> And if only the docs actually mentioned the hundreds of roadblocks they've implemented to allow for custom behavior, but no, absolutely nothing.
> 
> It's a shame Lucia has been deprecated. I can't wait for someone to release a complete, unopinionated auth lib that is actually built around the idea of a lib, not some single team's opinionated piece of code that seriously lacks documentation.
> 
> For anyone reading this, if you haven't spend more than a few hours on resolving next auth issues: I'd recommend staying away, and simply build auth from scratch. You'll spend less time implementing a single JWT flow, interactions with your db, and error handling.

I couldn't agree more! next-auth@5.0.0-beta is a complete waste of time.

**Comment by tapz** [comment] 2025-01-03 10:04
> I've been working with Next auth for about a week now, and at this point, I wonder why people actually even use this library. I mean, I am guessing that everyone starts using it to integrate auth in their apps quickly, and then end up on spending hours working around the countless issues?

Could not agree more. The only reason I use Next auth is that it provides the Facebook, Google etc authentications. Though, the time I have used solving weird issues and non-flexibility could have been used to write 20 integrations to different providers' services.

**Comment by QingjiaTsang** [comment] 2025-02-22 20:00
https://github.com/nextauthjs/next-auth/discussions/12495#discussioncomment-12213749

for someone using React and Honojs/expressjs, this is the way that can customize the login error.

**Comment by emezeske** [comment] 2025-03-18 16:06
> I've been working with Next auth for about a week now, and at this point, I wonder why people actually even use this library. I mean, I am guessing that everyone starts using it to integrate auth in their apps quickly, and then end up on spending hours working around the countless issues?
> 
> Next, auth seems to be written by a team that believes their definite opinions on handling auth are the only way to handle it. The library is the exact opposite of "Flexible."
> 
> I guess it makes sense if you only want to use some Oauth login with 0 interactions with the DB, but for anything else, why on earth do we keep working around their "single opinion auth flow" to be able to implement authentication in our apps?
> 
> And if only the docs actually mentioned the hundreds of roadblocks they've implemented to allow for custom behavior, but no, absolutely nothing.
> 
> It's a shame Lucia has been deprecated. I can't wait for someone to release a complete, unopinionated auth lib that is actually built around the idea of a lib, not some single team's opinionated piece of code that seriously lacks documentation.
> 
> For anyone reading this, if you haven't spend more than a few hours on resolving next auth issues: I'd recommend staying away, and simply build auth from scratch. You'll spend less time implementing a single JWT flow, interactions with your db, and error handling.

The hugely ironic thing is that by making password-based auth so difficult inside next-auth, the next-auth folks are actually *damaging* app security for apps that for whatever reason are going to use password auth regardless of the hurdles. The security is damaged for two reasons:

1. Next auth doesn't provide certain password auth features that are difficult to implement correctly, such as password hashing, and thus users have to implement those themselves, and are more likely to get the subtle details wrong.
2. By making password auth hard to use and deprioritizing documentation for how to do it, etc, it makes it much more likely for apps that use password auth to use the next auth APIs incorrectly.

And sure, it's great to recommend Oauth or email-token over passwords. But there are always going to be apps that can't/won't do this. For example, migrating an old app that used passwords, with a large user base with saved passwords, it may not be desirable to make all existing users change their auth mechanism. And so on.

**Comment by Not-Minimal** [comment] 2025-04-17 03:48
Hi guys, this works for me:
`try {
  console.log("Login values:", values);
  await signIn("credentials", {
    email: values.email,
    password: values.password,
    redirect: false,
  });
  return { success: true };
} catch (error: unknown) {
  console.log("Login error:", error);

  // Verificación segura del tipo de error
  if (error instanceof AuthError) {
    const cause = error.cause as { err?: { code?: string } };
    if (cause?.err?.code === "credentials") {
      return { error: true };
    }
  }

  return { error: "Error de autenticación 500" };
}`
• error: unknown: Indicates that the error can be anything.
• A check is made to see if error is an instance of AuthError.
• A safe cast is made to error.cause to access cause.err.code.

**Comment by kelixirr** [comment] 2025-04-20 00:06
Hey guys, It took me 4 hours to fix this issue as I was working with Auth Js for the first time. I am going to share my solutions so that anyone can understand. I am using the their latest `npm install next-auth@beta`. Let's go with the basic credentials providers in your `auth.ts` file. This is how your code looks like: 

```Javascript
export const { handlers, signIn, signOut, auth } = NextAuth({
  providers: [
    Credentials({
      credentials: {
        email: { label: "Email" },
        password: { label: "Password" },
      },

// Rest of the code below ......
```

In the same file in authorize function 

```Javascript
   authorize: async (credentials) => {
        if (!credentials.email || !credentials.password) {
          return null;
        }
    
      // Step1. Here you can check your user in database. if not found return null.  
     
     // Step 2. Here you can compare the password using bcryptjs if failed return null. 

    // step3.  Finally you can return the user object. 

// Rest of the code below ......
```

Now let say you have login page. The idea is to deal with things like incorrect email format or password using zod before you send details to signIn method.  

```Javascript
const [state, formAction, isPending] = useActionState(loginUser, {
    error: null,
    success: null,
  });

<form id="login" action={formAction}>

// Rest of the code below ......
```


In your `loginUser` function or in your case it will be something else, Make sure to first validate the formData using zod then proceed with anything. This will save you!!

Now my approach is very simple. I am using try catch block to handle the error. And I am checking for the two errors that are frequently happening `CredentialsSignin` and `CallbackRouteError`. I am checking the error type and handling them using switch case. And I am also taking into account unexpected cases. 

Additonally, note that when you use try catch block, and if you are using the login to redirect user then you need to keep in mind that nextjs throws `NEXT_REDIRECT` error for redirection purpose, but using the try catch, you can't redirect as you are catching that error you need to find that error and re-throw it for the redirection to work. Additionally, you can do that using the router from the fronted side but I went with the server action logic but you need to single it in the front-end to do so. 
_____

```Javascript
export async function loginUser(
  prevState: { error: string | null; success: string | null },
  formData: FormData
): Promise<{ error: string | null; success: string | null }> {
  const email = formData.get("email")?.toString();
  const password = formData.get("password")?.toString();

// Here you can validate the formData using zod and sendi errors......

// zod validation logic......

// ......

try {

  // Once you have verified the expected schema of your formData use signIn method. 

    await signIn("credentials", {
      email,
      password,
      redirectTo: "/dashboard",
    });

    return {
      error: null,
      success: "Login successful! Redirecting...",
    };
  } catch (error) {
   

   // Here I am checking the error type to pass the signal to client.

    if (error instanceof AuthError) {
      switch (error.type) {
        case "CredentialsSignin":
        case "CallbackRouteError":
          return {
            error: "Invalid email or password. Try again!",
            success: null,
          };
        default:
          return { error: "An authentication error occurred.", success: null };
      }
    }
  
   // Here I need to rethrow the "Next_DIRECT" error so that redirection can work inside the server action, otherwise catch block will prevent it, and you will see another error. You can use useRouter if not this.

    if (
      error &&
      typeof error === "object" &&
      "message" in error &&
      typeof error.message === "string" &&
      error.message.includes("NEXT_REDIRECT")
    ) {
      throw error;
    }
   
 // For something unexpected
    return {
      error: "An unexpected error occurred. Please try again.",
      success: null,
    };
  }
}
```
Anyway this fixed my issue. And I hope this will help you as well. Honestly speaking I hope they will soon implement some ways to deal with this situation because I don't think it is a good practice at the moment. It's too complex and authorize method need to have some way to show some user friendly error on the front end. I hope this helps.

**Comment by explaingarlic** [comment] 2025-05-20 22:35
> Once you have verified the expected schema of your formData use signIn method.

You didn't mention *which* signin method to use.
