### ISSUE TITLE
Opague Google Provider OPError: expected 200 OK, got: 400 Bad Request

### ISSUE THREAD

**Issue by rewnad** [nextauthjs/next-auth#7335] opened 2023-04-23 07:31 UTC
### Environment

  System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M2
    Memory: 448.16 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 112.0.1
    Safari: 16.1

### Reproduction URL

n/a

### Describe the issue

Getting the following only production. `GOOGLE_CLIENT_ID`, `GOOGLE_CLIENT_SECRET` and `NEXTAUTH_URL` configured. 

```
[next-auth][error][OAUTH_CALLBACK_ERROR]  https://next-auth.js.org/errors#oauth_callback_error expected 200 OK, got: 
400 Bad Request {   error: OPError: expected 200 OK, got: 400 Bad Request       at processResponse 
(/var/task/node_modules/openid-client/lib/helpers/process_response.js:41:11)       at Client.grant (/var/task/node_modules/openid-client/lib/client.js:1327:22)       at processTicksAndRejections 
(node:internal/process/task_queues:96:5)       at async Client.callback (/var/task/node_modules/openid-
client/lib/client.js:476:24)       at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:109:16)       at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:52:11)       at async AuthHandler 
(/var/task/node_modules/next-auth/core/index.js:208:28)       at async NextAuthApiHandler (/var/task/node_modules/next-auth/next/index.js:22:19)       at async NextAuth._args$ (/var/task/node_modules/next-auth/next/index.js:106:14)       at async 
/var/task/node_modules/@sentry/nextjs/cjs/config/wrappers/withSentryAPI.js:132:31 {     name: 'OAuthCallbackError',     code: 
undefined   },   providerId: 'google',   message: 'expected 200 OK, got: 400 Bad Request' }

--
```

### How to reproduce

I can't reproduce this locally...

### Expected behavior

Should be able to authenticate on production with google.

**Comment by pdpwebsecurify** [comment] 2023-04-23 12:30
We are seeing the same issue. Production only!

**Comment by QuiiBz** [comment] 2023-04-23 12:42
Getting the same issue, only in production. Are you also using Vercel? I haven't been able to make a proper minimal reproduction yet, still digging into it.

**Comment by pdpwebsecurify** [comment] 2023-04-23 12:51
Even production builds are working fine under local circumstances. It is most definitely vercel related issue.

**Comment by pdparchitect** [comment] 2023-04-23 13:04
I don't think it is related but strangely the VERCEL_URL is not taken into consideration when getting the basePath. This could be just another bug. https://github.com/nextauthjs/next-auth/blob/7c44d916eda921aad68923841d6c1689c00f94d3/packages/next-auth/src/react/index.tsx#L51

**Comment by pdparchitect** [comment] 2023-04-23 13:58
Just to add more colour here - rolling back to a version from 2 days ago resolved the problem 100%. The thing is that there were no package changes. This is Vercel mangling their builds again. Something similar happened about a month ago - un planned weekend borked builds.

**Comment by dlvx** [comment] 2023-04-23 14:43
I started having this problem during the weekend (only in production). As pointed out by @pdparchitect rolling back to a deployment from a couple of days ago fixes the issue. Come on Vercel...I probably lost tens of new users due to this.

**Comment by CardanoDur** [comment] 2023-04-23 15:10
I'm getting the same issue with Discord, runs great locally. Same stack trace, different providerId. Happening for us in preview, but I suspect only b/c we haven't pushed to prod yet

**Comment by QuiiBz** [comment] 2023-04-23 16:50
Could you guys try to trigger a new production deployment? [Vercel has made a rollback](https://twitter.com/galstar/status/1650177942083760128) and it's working again on my side (just to make sure we all had the same issue).

**Comment by pdparchitect** [comment] 2023-04-23 16:57
It works!

**Comment by Cl3arglass** [comment] 2023-04-23 17:03
Hello, as mentioned above we reverted a change that we believe should fix the problem. Please try and redeploy your project, and let us know if the issue persists: https://vercel.com/help

**Comment by baptisteArno** [comment] 2023-04-24 06:06
Yep, it works now!

**Comment by balazsorban44** [comment] 2023-04-24 07:19
Based on the comments above, I'm closing this as it was not a bug in the library. If you see a similar issue but think it _is_ a bug, please open a new issue with a reproduction. Thanks!

**Closed by balazsorban44** 2023-04-24 07:19 UTC
Labels: triage
