### ISSUE TITLE
Configuring Okta base url

### ISSUE THREAD

**Issue by brandonchinn178** [nextauthjs/next-auth#1345] opened 2021-02-21 02:41 UTC
**Describe the bug**
Following the normal instructions, I get redirected to `https://dev-${my_app_id}.okta.com/v1/authorize`, which shows a 404 error. Changing `OKTA_DOMAIN` to `dev-${my_app_id}.okta.com/oauth2` fixes it. Should the Okta provider add the `/oauth2` path?

**Steps to reproduce**
Follow instructions for Okta provider

**Expected behavior**
Login should work

**Screenshots or error logs**
If applicable add screenshots or error logs to help explain the problem.

**Additional context**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment] 2021-02-21 09:27
Thanks for this. So there was a change in https://github.com/nextauthjs/next-auth/pull/763. Are you suggesting it was wrong?

**Comment by vmptk** [comment] 2021-02-21 09:54
I can also confirm that by adding the oauth2 to the domain is working as well.

**Comment by balazsorban44** [comment] 2021-02-21 14:43
huh. should we revert #763 then?

**Comment by brandon-leapyear** [comment] 2021-02-21 17:08
Maybe instead of `domain`, just ask for `baseUrl`? That would make it more consistent with the docs

https://developer.okta.com/docs/reference/api/oidc/#composing-your-base-url

**Comment by brandonchinn178** [comment] 2021-02-21 19:13
Maybe instead of `domain`, just ask for `baseUrl`? That would make it more consistent with the docs

https://developer.okta.com/docs/reference/api/oidc/#composing-your-base-url

This would also make it consistent with `@okta/jwt-verifier`, where I explicitly specify `issuer` as `https://$DOMAIN/oauth2/default`

**Comment by brandonchinn178** [comment] 2021-02-21 19:45
https://github.com/nextauthjs/next-auth/discussions/1287

**Comment by htunnicliff** [comment] 2021-03-15 17:22
Just wanted to chime in that this also broke our Okta sign in. Okta expects the authorize URL to be `/oauth2/v1/authorize`. This should definitely remain the default, since next-auth lets users completely override those urls in individual configurations.

**Comment by kamerondotcom** [comment] 2021-03-18 04:33
Any updates here? Our implemented Okta auth is no longer working.

**Comment by miguelguadarrama** [comment] 2021-04-13 09:06
Just wanted to give my two cents here... also affected. The current version is not working by default. As other suggested you could make OKTA_DOMAIN something like okta.com/oauth2 but it's feels definitely hackish...

**Comment by piotrzaborow** [comment] 2021-07-07 14:20
I did change the domain url, but still has problem to get it working.

New Okta tenant with newly created application gives me error:
```
https://next-auth.js.org/errors#oauth_callback_error {
  statusCode: 400,
  data: '{"error":"invalid_grant","error_description":"The authorization code is invalid or has expired."}'
}
```

**Comment by temaput** [comment] 2021-07-27 12:38
> I did change the domain url, but still has problem to get it working.
> 
> New Okta tenant with newly created application gives me error:
> 
> ```
> https://next-auth.js.org/errors#oauth_callback_error {
>   statusCode: 400,
>   data: '{"error":"invalid_grant","error_description":"The authorization code is invalid or has expired."}'
> }
> ```

I had a similar issue with Okta. Turns out it was due to improperly assigned user: Okta was returning user back with an error code instead of authCode, but next-auth still tried to get the token (with authorization code equal to null), which in turn caused the Okta's complain.

**Comment by balazsorban44** [comment] 2023-03-25 20:33
Closing as this issue is kinda old. Let's open a new one with a fresh, minimal reproduction, if it still exists.

**Closed by balazsorban44** 2023-03-25 20:33 UTC
Labels: bug, help needed, incomplete, good first issue
