### ISSUE TITLE
How to share session information between two next.js apps? (SSO)

### ISSUE THREAD

**Issue by jjmendozabdev** [nextauthjs/next-auth#1668] opened 2021-04-07 20:28 UTC
I'm having an issue trying to share the session information between two next.js apps that are in different subdomains. This is the configuration that I have in the [...nextauth].ts file:

```ts
import NextAuth, { InitOptions } from 'next-auth';
import { NextApiRequest, NextApiResponse, SessionBase } from 'next-auth/_utils';

const useSecureCookies = process.env.NEXTAUTH_URL.startsWith('https://');
const cookiePrefix = useSecureCookies ? '__Secure-' : '';
const hostName = new URL(process.env.NEXTAUTH_URL).hostname;
const domain =
    hostName === 'localhost'
        ? hostName
        : hostName.substring(hostName.indexOf('.'));
const options: InitOptions = {
    cookies: {
        sessionToken: {
            name: `${cookiePrefix}next-auth.session-token`,
            options: {
                httpOnly: true,
                sameSite: 'lax',
                path: '/',
                secure: useSecureCookies,
                domain,
            },
        },
    },
    providers: [
        {
            ...
        },
    ],
};

export default (req: NextApiRequest, res: NextApiResponse<any>) =>
    NextAuth(req, res, options);
```

app 1 running on https://abc.mydomain.com:

I successfully log in and can see the profile information. The cookie "__Secure-next-auth.session-token" is set to the domain ".mydomain.com"

app 2 running on https://xyz.mydomain.com:

The cookie is not present and even gets removed from "abc.mydomain.com" as soon as I enter to this app.

So, why the cookie is removed as soon as I enter to this subdomain?
What is the proper configuration to have this SSO across subdomains implemented? I have the next-auth library in both apps and the same configuration with the pages/api/auth/[...nextauth].ts. Is this correct?

**Comment by balazsorban44** [comment] 2021-04-07 22:28
Duplicate of #794

**Closed by balazsorban44** 2021-04-07 22:28 UTC
Labels: question

**Comment by jjmendozabdev** [comment] 2021-04-08 13:51
@balazsorban44 The post that you are indicating doesn't explain why the cookie is deleted or how implement the configuration to share the sessions between the apps. Any idea of how to get it working? Thanks in advance

**Comment by balazsorban44** [comment] 2021-04-08 14:12
Didn't say I had a solution, just that this issue was a duplicate. For easier maintenance, when an issue has already been opened before, we try to point to the oldest one and close any other

**Comment by jjmendozabdev** [comment] 2021-04-08 14:14
I have read that post that you mentioned and doesn't answer my question. So closing this issue doesn't help me much :s

**Comment by balazsorban44** [comment] 2021-04-08 20:54
I understand. I haven't said either that someone there solved your problem, but as a maintainer of a popular library, it is easier to keep track of fewer issues with a single source of truth, in case we have feedback or new information related to one. That we we don't have tro track down multiple related issues that are already reported.

**Comment by WebmasterClickPanda** [comment] 2024-01-31 19:45
Im using google Oauth, I just tested 2 local environments on port 3000 and 3001, and adding the same credentials to both applications and also authorizing the redirect URIs at google, seems to be working, imma test later in my own public subdomais, cause that would do the trick
