### ISSUE TITLE
Make `NEXTAUTH_URL` bypass for `preview` deployment on vercel

### ISSUE THREAD

**Issue by typedashutosh** [nextauthjs/next-auth#1854] opened 2021-04-25 17:05 UTC
**Summary of proposed feature**
When I push a commit to GitHub repo, Vercel automatically deploy it as preview build **BUT** the build is available at a unique URL which contain random characters e.g. `https://blog-app-nextjs-lzocgllwx-typedashutosh.vercel.app/signin`
![image](https://user-images.githubusercontent.com/68853189/116002012-2ded9100-a615-11eb-8558-8997659b150a.png)

Which leads to this 
![image](https://user-images.githubusercontent.com/68853189/116002053-5b3a3f00-a615-11eb-8c98-08c21a86e793.png)

CORS Policy always block my request.
So the only way to check my Builds for errors, is when it is deployed to `Production`.
Even if I add `Access-Control-Allow-Origin` somehow, it still makes problem sometime or other.
Changing environment variables at every PR is not what I will do, ever.
So, If we could have a way to skip NEXTAUTH_URL check just for preview build it will solve a great amount of mess.

**Comment by balazsorban44** [comment] 2021-04-25 17:12
duplicate of #969

**Closed by balazsorban44** 2021-04-25 17:12 UTC
Labels: enhancement
