### ISSUE TITLE
Infinite redirect with middleware and basePath

### ISSUE THREAD

**Issue by nicks6853** [nextauthjs/next-auth#4234] opened 2022-03-22 16:08 UTC
### Question 💬

I have a NextJS app setup to run under the `/admin` basepath. Whenever I use the middleware, I am having problems with it sending me to the wrong url for the login page. If I try passing a custom sign in page to the options, it redirects me infinitely. Can anyone point me in the right direction? Is this even possible?

### How to reproduce ☕️

I am running `next-auth@4.3.1`, `next@12.1.0`

`_app.js`

```javascript
import { SessionProvider } from 'next-auth/react';
import '../styles/globals.css';

function App({ Component, pageProps: { session, ...pageProps } }) {
  return (
    <SessionProvider
      session={session}
      basePath="/admin/api/auth"
    >
      <Component {...pageProps} session={session} />
    </SessionProvider>
  );
}

export default App;
```

`_middleware.js `

> Note that without the custom signin page, the app redirects me to `/api/auth/signin` which does not exists (I can see the page if I manually go to `/admin/api/auth/signin`) and with the custom signin page I get an infinite redirect error.

```javascript
import withAuth from 'next-auth/middleware';

export default withAuth({
  pages: {
    signIn: '/admin/signin',
  },
});
```

`next.config.js`
```javascript
/** @type {import('next').NextConfig} */

const nextConfig = {
  reactStrictMode: true,
  env: {
    COGNITO_CLIENT_ID: '<removed>',
    COGNITO_CLIENT_SECRET: '<removed>',
    COGNITO_ISSUER: '<removed>',
    COGNITO_DOMAIN: '<removed>',
    NEXTAUTH_URL: 'http://localhost:3000/admin/api/auth',
    NEXTAUTH_SECRET: '<removed>',
  },
  basePath: '/admin',
};

module.exports = nextConfig;
```

`pages/signin.js`

```javascript
import { Button } from '@mantine/core';
import { signIn } from 'next-auth/react';

export default function SignIn({ providers }) {
  return (
    <Button onClick={() => signIn('cognito')}>
      Sign in with Cognito
    </Button>
  );
}
```

`pages/api/auth`

```javascript
import NextAuth from 'next-auth/next';
import CognitoProvider from 'next-auth/providers/cognito';

export default NextAuth({
  providers: [
    CognitoProvider({
      clientId: process.env.COGNITO_CLIENT_ID,
      clientSecret: process.env.COGNITO_CLIENT_SECRET,
      issuer: process.env.COGNITO_ISSUER,
      domain: process.env.COGNITO_DOMAIN,
    }),
  ],
  secret: process.env.NEXTAUTH_SECRET,
  debug: true,
});
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by ndom91** [comment] 2022-03-22 23:00
@nicks6853 thanks for reaching out. So this should theoretically be possible. I was successfully able to recreate and reproduce your infinite refresh / forwarding problem. 

I think I've boiled it down to `packages/next-auth/src/next/middleware.ts:L65-L68` - this check isn't being hit and so its not early returning. Therefore its containing on until a few lines further down it appends another copy of the `callbackUrl` query param and redirect's to the `signInUrl` over and over again..

Unfortunately I haven't been abel to get any further tonight. I'll take another look at this tomorrow :+1:

**Comment by ndom91** [comment] 2022-03-29 08:40
@nicks6853 sorry I haven't had the bandwidth to take another look at this yet. Its on my todo list though!

**Comment by nicks6853** [comment] 2022-03-29 20:50
No worries, I was just curious. I'll be on the lookout!

**Comment by kingschool9** [comment] 2022-04-14 02:21
If you pass parameters to withAuth, the execution would pass without an infinite redirect even though both non parameter and parameters call the handleMiddleware function. That may be something to look at.

```js
import type { NextRequest } from "next/server"
import type { JWT } from "next-auth/jwt"

import { withAuth } from "next-auth/middleware"

export default withAuth(
  function middleware(req: NextRequest & { nextauth: { token: JWT } }) {
    console.log(req.nextauth.token)
  },
  {
    callbacks: {
      authorized: ({ token }) => token?.role === "admin",
    },
  }
)
```
this would work correctly

**Comment by ndom91** [comment] 2022-04-19 16:47
@nicks6853 I just realized (thanks to @ThangHuuVu in #4366) that you also have to pass the `callbackUrl` as a param to the `signin()` function in the custom login page.

i.e.

`pages/signin.js`

```js
import { Button } from '@mantine/core';
import { signIn } from 'next-auth/react';
import { useRouter } from 'next';

export default function SignIn({ providers }) {
  const { callbackUrl }  = useRouter().query
  return (
    <div className='max-w-2xl mx-auto'>
      <div className='flex items-center justify-center px-8 py-8 mt-4 rounded bg-content bg-base-200'>
        {Object.values(providers).map((provider) => (
          <div key={provider.name}>
            <button className='btn' onClick={() => signIn(provider.id, { callbackUrl })}>
              Sign in with {provider.name}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
```

**Comment by TheBorsuk** [comment] 2022-06-03 11:44
Hey, any updates on this?

**Comment by drewgillen** [comment] 2022-08-05 00:14
1+

**Comment by Angeschossen** [comment] 2022-10-06 06:34
I have the same issue by just using `export { default } from "next-auth/middleware"` in my middleware.

**Comment by jporcelli1120** [comment] 2022-12-16 01:32
any update on this?

**Comment by pencilcheck** [comment] 2023-01-07 12:49
Still having issues with default `export { default } from "next-auth/middleware"`

**Comment by AbrahamX3** [comment] 2023-01-09 12:41
Currently, on `next@13.1.1` and `next-auth@4.18.8`, I am having this issue as well using only `export { default } from "next-auth/middleware"`, it makes my app break, and it gets into a cycle of “localhost redirected you too many times” error.

Using the matcher config for example `export const config = { matcher: ["/dashboard"] }`, makes it semi work, I can go to `/` with no issue since it wasn't defined but going to the `/dashboard` directory with a successful login brings me back to the sign in.

**Comment by ashiishme** [comment] 2023-01-09 23:41
I am facing the same issue, after defining the middleware with a protected route, I am no longer able to access it even though the sing in is successful. The app goes in a sign in loop again and again.

**Comment by patrykczubek** [comment] 2023-01-10 04:56
When can we expect this to work :(

**Comment by one-moonman** [comment] 2023-01-10 20:15
Same as @AbrahamX3. Any workarounds so far?

**Comment by AbrahamX3** [comment] 2023-01-10 21:11
@one-moonman I have not found any workarounds to make it work, unfortunately. I gave up and protected routes the usual way without middleware.

**Comment by mononoke-choi** [comment] 2023-01-24 08:05
I have the same issue, i'm using latest next and next-auth modules and then just write `export { default } from "next-auth/middleware"` in my middleware file :(

**Comment by one-moonman** [comment] 2023-01-24 12:05
Maybe try using an adapter like prisma or mongodb. I suppose that this might have fixed something for me.

**Comment by Tigatok** [comment] 2023-01-26 00:18
> I have the same issue, i'm using latest next and next-auth modules and then just write `export { default } from "next-auth/middleware"` in my middleware file :(

Same issue on my end. I am using DynamoDB adapter with Email provider. My other instance of this exact same middleware running google Auth has no problems.

**Comment by rusiaaman** [comment] 2023-02-05 16:05
> I have the same issue, i'm using latest next and next-auth modules and then just write export { default } from "next-auth/middleware" in my middleware file :(

I faced the same issue. Overriding the session strategy to "jwt" in the authOptions solved the issue.

**Comment by nickparkin** [comment] 2023-02-06 10:03
Is there a work around here? I am also running into the same issue (no config options, just exporting default, with the Email provide) and have explored defining paths explicitly. However, as I just want to protect all routes - not sure how to achieve this.

**Comment by nickparkin** [comment] 2023-02-06 10:22
> > I have the same issue, i'm using latest next and next-auth modules and then just write export { default } from "next-auth/middleware" in my middleware file :(
> 
> I faced the same issue. Overriding the session strategy to "jwt" in the authOptions solved the issue.

This solved my issue (I think I glanced over with the explicit mention that JWT needs to be enabled for this to work (I understood its just withAuth.

I have created a PR on the docs to be more explicit that this should be added.

**Comment by mononoke-choi** [comment] 2023-02-06 11:52
oh, i missed [caveats section](https://next-auth.js.org/configuration/nextjs#middleware:~:text=Only%20supports%20the%20%22jwt%22%20session%20strategy.) ....!
yeah, i'm using database strategy with mongodb adapter.
no wonder i tried to use edge function with mongodb driver but it couldn't work at all.
i didn't know what exactly happened, but I just though it is immature to use both of them together yet.
anyway, thanks for sharing your experience

**Comment by jonasrdm** [comment] 2023-02-22 19:27
I'm explicitly using "JWT" as the session strategy but facing the same infinite redirection issue.
Is there any known workaround for this issue? I'm on the brink of abandoning the middleware to try another approach.

I'm using an auth0 provider,
My current versions are:
```
"next": "13.1.6",
"next-auth": "^4.19.2",
```

**Comment by Eagl9Eye** [comment] 2023-03-18 16:54
for anyone stumbling on this, i've created a custom adapter for google firestore following [this implementation](https://github.com/lowfront/next-auth-firestore-adapter-example/). After configuration i was at the point, where a user session would be created after sign-in, but the callback url would keep me on the sign-in route (because the session could not be retrieved). After i changed the session-strategy (as described [here](https://next-auth.js.org/configuration/options#session)) to `jwt` everything was working fine, apart from custom properties in my session (coming from the firestore user object). Adding a custom `api/token` endpoint [like so](https://github.com/lowfront/next-auth-firestore-adapter-example/blob/master/pages/api/auth/token.ts) finally made the stone drop. 

Hope that helps!

**Comment by balazsorban44** [comment] 2023-03-25 20:32
Closing as this issue is kinda old. Let's open a new one with a fresh, minimal reproduction, if it still exists.

**Closed by balazsorban44** 2023-03-25 20:32 UTC
Labels: bug, incomplete, middleware
