### ISSUE TITLE
next-auth v5: Property 'user' does not exist on type '({ session: Session; user: AdapterUser; }'

### ISSUE THREAD

**Issue by donlair** [nextauthjs/next-auth#9908] opened 2024-02-05 13:28 UTC
### Environment

 System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 152.13 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  Browsers:
    Chrome: 121.0.6167.139
    Edge: 114.0.1823.37
    Safari: 17.2.1
  npmPackages:
    @auth/prisma-adapter: ^1.2.1 => 1.2.1 
    next: ^14.1.0 => 14.1.0 
    next-auth: ^5.0.0-beta.5 => 5.0.0-beta.5 
    react: ^18.2.0 => 18.2.0 

### Reproduction URL

https://github.com/donlair/nextauthbug/blob/main/auth.ts

### Describe the issue

Context: I'm in the process of migrating to next-auth v5. 

I'm using the Prisma adapter and creating a session callback but getting a type warning that "'user' does not exist on type '({ session: Session; user: AdapterUser; }".

Related discussion [here](https://github.com/nextauthjs/next-auth/discussions/9899)

Per [this comment](https://github.com/nextauthjs/next-auth/discussions/9899#discussioncomment-8361272), reverting to beta 4 fixes the issue but I haven't confirmed that yet.

```
declare module '@auth/prisma-adapter' {
	interface Session extends DefaultSession {
		user: {
			id: string;
			role: string;
		} & DefaultSession['user'];
	}

	interface User {
		role: UserRole;
	} 
}

const authConfig = {
	session: {
		strategy: 'database',
	},

	callbacks: {
		session({ session, user }) {
			session.user.id = user.id;
			session.user.role = user.role;
			return session;
		},
	},
	adapter: PrismaAdapter(prisma),
	providers: [
		DiscordProvider({
			clientId: env.DISCORD_CLIENT_ID,
			clientSecret: env.DISCORD_CLIENT_SECRET,
		}),

	],
} satisfies NextAuthConfig;
```

### How to reproduce

Create a custom session callback while using a database adapter.

### Expected behavior

The user parameter should be properly typed and not throw TS warnings.

**Comment by balazsorban44** [comment] 2024-02-05 23:39
Duplicate of https://github.com/nextauthjs/next-auth/issues/9802

**Closed by balazsorban44** 2024-02-05 23:39 UTC
Labels: bug, triage

**Comment by dev-shajid** [comment] 2024-07-31 05:49
Create a next-auth.d.ts file and add this or you can past this in auth.ts file as well

```ts
import { DefaultSession, User } from "next-auth";

declare module "next-auth" {
  interface User {
    role: 'USER' | 'ADMIN';
    emailVerified: Date | null;
  }
}
```

**Comment by Cisco0911** [comment] 2024-10-12 14:50
Why is `emailVerified: Date | null;` required on `session.user` ?
