### ISSUE TITLE
Respect `NEXTAUTH_URL` in `next-auth` v5

### ISSUE THREAD

**Issue by markdagraca** [nextauthjs/next-auth#8281] opened 2023-08-10 08:58 UTC
### Environment

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 30.15 GB / 63.94 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 115.0.5790.171
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.200)
    Internet Explorer: 11.0.19041.1566

### Reproduction URL

https://cityfone-test.web.app/

### Describe the issue

When utilizing the @auth/core providers like Google in conjunction with Firebase hosting with the Next.js framework, a Google Compute Engine is created to serve up the server-side content. However, during the generation of the login page, the system is not recognizing the full URL path. Instead of using the defined `NEXTAUTH_URL` environment variables or the `redirectProxyUrl` defined in the code, the buttons point to `localhost:443`.

This behavior seems to be traced back to the file `packages\core\src\lib\init.ts` at line 49, where the `reqURL` origin is used to create the link, instead of the environment variable. like next_auth does

### How to reproduce

1. Set up a project using the Next.js framework in conjunction with @auth/core providers like Google and Firebase hosting.
2. Configure the `NEXTAUTH_URL`  environment variables.
3. Navigate to the login page where the issue appears, and observe that all the buttons point to `localhost:443`.
4. Investigate the code in `packages\core\src\lib\init.ts` at line 49 to see the problematic implementation.

## Code Sample
```typescript
import Google from "@auth/core/providers/google";
import { Auth, AuthConfig } from "@auth/core";

const { GOOGLE_ID, GOOGLE_SECRET } = process.env;
// check if GOOGLE_ID and GOOGLE_SECRET exist and is not undefined
if (!GOOGLE_ID || !GOOGLE_SECRET) {
  throw new Error(
    "Missing GOOGLE_ID and GOOGLE_SECRET environment variables. Did you forget to run your script?",
  );
}

const authOptions: AuthConfig = {
  secret: process.env.NEXTAUTH_SECRET,
  redirectProxyUrl: `${process.env.NEXTAUTH_URL_INTERNAL}/api/auth/callback`,
  trustHost: true,
  providers: [
    Google({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET,
    }),
  ],
  logger: {
    debug: console.log,
    error: console.error,
    warn: console.warn,
  },
  debug: true,
  callbacks: {
    signIn: async ({
      user, account, profile, email, credentials,
    }) => {
      console.log("Sign in callback:", user, account, profile, email, credentials);
      return true;
    },
    redirect: async ({ url, baseUrl }) => process.env.NEXTAUTH_URL || "",
  },
};

const handler = (req: Request) => Auth(req, authOptions);

const wrappedHandler = (req: Request) => {
  console.log("Request received:", req);
  console.log("NextURL:", process.env.NEXTAUTH_URL);

  const response = handler(req);
  console.log("Handler response:", response);
  return response;
};

export const GET = wrappedHandler;
export const POST = wrappedHandler;
```

### Expected behavior

The expected behavior is that the login page should recognize the full URL path, including any environment variables such as `NEXTAUTH_URL`, and use them correctly to create the link. The buttons on the login page should not be pointing to `localhost:443`, but instead, should follow the proper URL path as defined in the environment variables and code.

**Comment by balazsorban44** [comment] 2023-08-10 09:05
Hi, could you link to a full - but **minimal** (please remove all code/dependencies unnecessary) - reproduction?

FWIW if you are using Next.js, we recommend using `next-auth`. There is an upcoming new version that you can try out at #7443 which uses Auth.js under the hood.

**Comment by balazsorban44** [comment] 2023-08-10 09:07
> This behavior seems to be traced back to the file packages\core\src\lib\init.ts at line 49, where the reqURL origin is used to create the link, instead of the environment variable. like next_auth does

I wonder if Firebase Hosting is safe to assume that the headers are trustable. In that case, you can just drop `NEXTAUTH_URL` all .together

**Comment by markdagraca** [comment] 2023-08-10 09:55
Thanks for the quick reply @balazsorban44! I'll try V5; I tried V4 and got this issue https://github.com/firebase/firebase-tools/issues/6225.

From what I read, it seems Firebase hosting strips the headers.

Please check your Twitter DM; I just sent you a message.

**Comment by markdagraca** [comment] 2023-08-10 09:57
It also looks like @auth/core dosnet make use of NEXTAUTH_URL

**Comment by balazsorban44** [comment] 2023-08-10 10:00
Right. I think we can look into that.

As a side note, I recommend always adding a full (but minimal) reproduction to help maintainers, without being asked for it. The more time you spend polishing/simplifying your reproduction, the less time a maintainer have to decipher things and effectively fix the issue. It's a very nice gesture if you don't just link to your project with potentially many dependencies and added complexity. This is true for https://github.com/firebase/firebase-tools/issues/6225. I assume not everyone at Firebase even know what NextAuth.js is, or maybe even Next.js. Give them a minimal code they can run in a few minutes.

**Comment by balazsorban44** [comment] 2023-08-10 10:03
Hmm.. On a second thougt, since `@auth/core` is runtime agnostic, we cannot make it respect anything else than the incoming Request's headers. I can implement this in `next-auth` in #7443 though. I'll close this issue for now, since v5 is still experimental and don't need to be publicly tracked as issues. You can comment on the PR instead.

**Closed by balazsorban44** 2023-08-10 10:03 UTC
Labels: core

**Comment by markdagraca** [comment] 2023-08-10 10:15
how about the AUTH_REDIRECT_PROXY env variable I see it mentioned in the @auth/core guide but it is not used anywhere in the code `@auth/core` code.

I was trying to follow this guide https://authjs.dev/guides/basics/deployment#securing-a-preview-deployment

**Comment by balazsorban44** [comment] 2023-08-10 10:42
It's being passed as a config option https://github.com/nextauthjs/next-auth/blob/fe20b943aecc73d3ba8c4e6d93b81a0d7b24caab/packages/core/src/index.ts#L371

Again, `@auth/core` cannot infer environment variables, since there is no web standard for this (`process.env` is a convention only, used by eg. Next.js. Other frameworks might have other opinions).

`@auth/core` is aimed at being a foundation for framework authors/experienced users, and you should likely not interact with it directly.

**Comment by balazsorban44** [comment] 2023-08-10 11:25
Landed `NEXTAUTH_URL` (alias for `AUTH_URL` for name consistency with other variables, preferred) in `next-auth@0.0.0-manual.024ba3e6`
