### ISSUE TITLE
Package subpath './providers/github' is not defined by "exports" in package.json

### ISSUE THREAD

**Issue by laurenzhonauer** [nextauthjs/next-auth#3675] opened 2022-01-19 16:59 UTC
### Description 🐜

When creating a next.js typescript project and using next-auth v4. The Login via github `signIn("github");` causes following error:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './providers/github' is not defined by "exports" in /home/workspace/trubudget-aas-frontend/node_modules/next-auth/package.json
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error invalid json response body at http://localhost:3000/api/auth/providers reason: Unexpected token < in JSON at position 0 {
  error: {
    message: 'invalid json response body at http://localhost:3000/api/auth/providers reason: Unexpected token < in JSON at position 0',
    stack: 'FetchError: invalid json response body at http://localhost:3000/api/auth/providers reason: Unexpected token < in JSON at position 0\n' +
      '    at /home/workspace/trubudget-aas-frontend/node_modules/next/node_modules/node-fetch/lib/index.js:272:32\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
    name: 'FetchError'
  },
  path: 'providers',
  message: 'invalid json response body at http://localhost:3000/api/auth/providers reason: Unexpected token < in JSON at position 0'
}
``` 

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

1. Create a new next typescript project `npx create-next-app@latest --ts`
2. Add next-auth version >4
3. Configure Github Provider
4. Trigger signIn("github")

Error will occur

### Environment 🖥

 ```
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (5) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 1.25 GB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
  npmPackages:
    next: ^12.0.8 => 12.0.8 
    next-auth: ^4.1.2 => 4.1.2 
    react: 17.0.2 => 17.0.2 
```

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment] 2022-01-20 00:50
Duplicate of #3652

https://github.com/nextauthjs/next-auth/issues/3652#issuecomment-1015592025

**Closed by balazsorban44** 2022-01-20 00:50 UTC
Labels: bug
