### ISSUE TITLE
Using NextAuth in a container behind a proxy

### ISSUE THREAD

**Issue by Djiit** [nextauthjs/next-auth#1422] opened 2021-03-03 16:57 UTC
**Your question**

I use NextAuth in a container (listing on :3000). NEXTAUTH_URL is **https://myservice.local**
This container is exposed to the outside world via another container, e.g. a Caddy instance (listening on :443), and the server name on the Caddy configuration is **myservice.local**.

When I reach https://myservice.local, I can see my Next App. But when I try to login, I'm getting this error :

```
[next-auth][error][client_fetch_error]
https://next-auth.js.org/errors#client_fetch_error https://myservice.local/api/auth/session FetchError: request to https://myservice.local/api/auth/session failed, reason: getaddrinfo EAI_AGAIN myservice.local
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/next/dist/compiled/node-fetch/index.js:1:66404)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}
```
Note: To be able to reach my service, I added an entry in my /etc/hosts.

**What are you trying to do**

I'm trying to containerize my NextJS app behind a reverse proxy.

**Reproduction**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by balazsorban44** [comment] 2021-03-03 17:04
would this be a duplicate of https://github.com/nextauthjs/next-auth/issues/1121?

**Comment by Djiit** [comment] 2021-03-03 17:17
Totally 🤦 I was searching for "container" and "docker" keywords. Close at will, I'll subscribe to this one.

**Closed** 2021-03-03 17:30 UTC
Labels: question

**Comment by ALEXTANGXIAO** [comment] 2021-03-03 17:32
1



发自我的iPhone


------------------ Original ------------------
