### ISSUE TITLE
Do Not Require profileUrl For Providers

### ISSUE THREAD

**Issue by theGOTOguy** [nextauthjs/next-auth#1722] opened 2021-04-14 15:30 UTC
**Describe the bug**
`next-auth` fails ungracefully if no profileUrl endpoint is provided.  While most providers do indeed provide a profileUrl endpoint, this is not an [official part of the OAuth2 spec](https://tools.ietf.org/html/rfc6749).

**Steps to reproduce**
Try to connect to a custom Provider that does not provide a profile URL endpoint, such as [Epic on FHIR](https://fhir.epic.com/Documentation?docId=oauth2) or omit the profileUrl in a provider that does have it.  Likewise, a profile URL is optional in any [SMART on FHIR](https://github.com/smart-on-fhir/smart-on-fhir.github.io/issues/135) application.  A suitable example for testing follows below.

```
import NextAuth from 'next-auth'

export default NextAuth({
  // Configure one or more authentication providers
  providers: [
    {
      id: 'ReproNoProfile',
      name: 'ReproNoProfile',
      type: 'oauth',
      version: '2.0',
      scope: '',
      params: { grant_type: 'authorization_code' },
      accessTokenUrl: 'https://oauth.mocklab.io/oauth/token',
      requestTokenUrl: 'https://oauth.mocklab.io/oauth/authorize',
      authorizationUrl: 'https://oauth.mocklab.io/oauth/authorize',
      profileUrl: '',  // Normally https://oauth.mocklab.io/userinfo
      profile: (profile) => {
        return {
          id: profile.sub,
          name: profile.name,
          email: profile.email,
        }
      },
      clientId: 'ANYTHING_WILL_WORK_HERE',
      clientSecret: 'ANYTHING_WILL_WORK_HERE'
    },
  debug: true
})

```

It is [clear in the callback here](https://github.com/nextauthjs/next-auth/blob/782482b9f475ca19019e5bc37f3053718d472cb2/src/server/lib/oauth/callback.js#L50) that there is no way that the code could possibly succeed without a profile URL.

This is [at odds with the documentation](https://next-auth.js.org/configuration/providers) which claims that the profileUrl is indeed not required.

**Expected behavior**
If no profile URL is provided, the profile should either be left empty or populated with some other default part of the token to identify the user.  If desired, I can provide a pull request to fix this issue.

**Screenshots or error logs**
Redacted log outputs follow.

```
[next-auth][debug][oauth_callback_protection] Added state to authorization params {
  state: 'e2d2ab253c168258259c6a9eb9ad49cafc59d5c5db951de9bc9823312f1a7321'
}
[next-auth][debug][get_authorization_url] https://oauth.mocklab.io/oauth/authorize?state=e2d2ab253c168258259c6a9eb9ad49cafc59d5c5db951de9bc9823312f1a7321&redirect_uri=REDACTED&scope=&client_id=YOUR_CLIENT_ID
[next-auth][debug][oauth_callback_protection] Comparing received and expected state {
  state: 'e2d2ab253c168258259c6a9eb9ad49cafc59d5c5db951de9bc9823312f1a7321',
  expectedState: 'e2d2ab253c168258259c6a9eb9ad49cafc59d5c5db951de9bc9823312f1a7321'
}
[next-auth][error][oauth_get_access_token_error] 
https://next-auth.js.org/errors#oauth_get_access_token_error {
  statusCode: 400,
  data: '<html>\r\n' +
    '<head><title>400 Bad Request</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>400 Bad Request</h1></center>\r\n' +
    '<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n'
} LocalFHIR REDACTED
[next-auth][error][oauth_callback_error] 
https://next-auth.js.org/errors#oauth_callback_error {
  statusCode: 400,
  data: '<html>\r\n' +
    '<head><title>400 Bad Request</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>400 Bad Request</h1></center>\r\n' +
    '<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n'
}
```
**Feedback**

* [x] Found the documentation helpful
* [x] Found documentation but was <s>incomplete</s> incorrect
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment] 2021-04-14 16:32
Duplicate of #1065

**Closed** 2021-04-14 16:32 UTC
Labels: bug
