### ISSUE TITLE
How to use nextAuth's [...nextauth] dynamic route in the new version next js 13.2 app dir api route?

### ISSUE THREAD

**Issue by Seyid-cmd** [nextauthjs/next-auth#6950] opened 2023-03-15 09:11 UTC
### Question 💬

Currently, the […nextauth].ts file in the pages/api/auth directory is working properly. However, I want to migrate to Next.js 13.2’s app directory API route but can’t find a way to migrate my nextAuth route. I have tried moving /pages/api/auth/[…nextauth].ts to app/api/auth/[…nextauth].ts but it’s not working.

I have this question on [stackoverflow link](https://stackoverflow.com/questions/75735001/how-to-use-nextauths-nextauth-dynamic-route-in-the-new-version-next-js-13).

Further I have tries creating moving from /pages/api/auth/[…nextauth].ts to app/api/auth/[…nextauth]/.route.ts , where the content of route.ts the content of [...nextAuth].ts(when it was in pages dir)

### How to reproduce ☕️

here is the [...nextAuth].ts
```
import NextAuth, { NextAuthOptions } from "next-auth";
import CredentialsProvider from "next-auth/providers/credentials";
import { NextApiRequest, NextApiResponse } from "next";
type NextAuthOptionsCallback = (
  req: NextApiRequest,
  res: NextApiResponse
) => NextAuthOptions;

const authOptions: NextAuthOptionsCallback = (req, res) => {
  const BACKEND_URL = process.env.BACKEND_URL;
  return {
    providers: [
      CredentialsProvider({
        credentials: {},
        async authorize(credentials) {
          const { password, username } = credentials as {
            password: string;
            username: string;
          };
          const authResponse = await fetch(`${BACKEND_URL}/auth/signin`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({ password, username }),
          });

          if (!authResponse.ok) {
            return null;
          }
          const user = await authResponse.json();
          const cookies = authResponse.headers.get("Set-Cookie");

          //@ts-ignore
          res.setHeader("Set-Cookie", cookies);
          return user;
        },
      }),
    ],
    callbacks: {
      async jwt({ token, user }) {
        return { ...token, ...user };
      },
      async session({ session, token, user }) {
        session.user = token as any;
        return session;
      },
    },

    pages: {
      signIn: "/login",
    },
    session: { strategy: "jwt" },
  };
};
export default (req: any, res: any) => {
  return NextAuth(req, res, authOptions(req, res));
};

```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by olivierlesnicki** [comment] 2023-03-15 09:24
+1

**Comment by olivierlesnicki** [comment] 2023-03-15 09:33
Also, I wonder if the auth.js solid start package could work with the new route handlers since they both rely on the same specifications.

**Comment by balazsorban44** [comment] 2023-03-16 00:52
Duplicate of #6792

**Closed by balazsorban44** 2023-03-16 00:52 UTC
Labels: question
