### ISSUE TITLE
FirebaseAdapter is not a function?

### ISSUE THREAD

**Issue by RonAlmog** [nextauthjs/next-auth#5635] opened 2022-10-24 18:53 UTC
### Environment

next, react, next-auth, @next-auth/firebase-adapter

### Reproduction URL

nope

### Describe the issue

using the latest version of @next-auth/firebase-adapter (1.0.2) is producing an error:
export const authOptions = {
providers: [
GoogleProvider({
clientId: process.env.GOOGLE_CLIENT_ID,
clientSecret: process.env.GOOGLE_CLIENT_SECRET,
})
],
adapter: FirebaseAdapter({ db, ...firestoreFunctions }),
}
...
export default NextAuth(authOptions);

and the error is:
error - (api)/pages/api/auth/[...nextauth].js (43:27) @ eval
error - TypeError: (0 , next_auth_firebase_adapter__WEBPACK_IMPORTED_MODULE_6_.FirebaseAdapter) is not a function
at eval (webpack-internal:///(api)/./pages/api/auth/[...nextauth].js:64:90)

going back to the @experimental version, works. but I want to use the latest, of course.

### How to reproduce

normal nextjs installation.
[...nextauth].js in the normal place, /pages/api/auth

separate file for all firebase stuff (firebase.config.ts), ending with :

const app = getApps.length > 0 ? getApp() : initializeApp(firebaseConfig);
const db = getFirestore(app);
const storage = getStorage(app);

export { app, db, storage };

in [...nextauth].js you can see:
providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
      // ... add more providers here
  ],
  adapter: FirebaseAdapter({ db, ...firestoreFunctions }),
  ...

### Expected behavior

should show the google login button, and when logged in, to store the user's info in firebase.
instead i'm getting the error about FirebaseAdaptor being 'not a function'. which is weird,  because i checked the code, and it definitely is...

**Comment by balazsorban44** [comment] 2022-10-31 06:56
duplicate of #5551

**Closed by balazsorban44** 2022-10-31 06:56 UTC
Labels: firebase, triage
