### ISSUE TITLE
Providers.Credentials not work

### ISSUE THREAD

**Issue by Otoru** [nextauthjs/next-auth#1470] opened 2021-03-07 21:06 UTC
**Describe the bug**
The Providers.Credentials not work.

**Steps to reproduce**
 - Create a next.js project.
 - Follow [next-auth example code](https://next-auth.js.org/getting-started/example).
 - Change provider to: 
 ```
    Providers.Credentials({
      name: 'Credentials',
      credentials: {
        username: { label: "Username", type: "text", placeholder: "jsmith" },
        password: {  label: "Password", type: "password" }
      },
      async authorize(credentials) {
        const user = { id: 1, name: 'J Smith', email: 'jsmith@example.com' }
  
        if (user) {
          return user
        } else {
          return null
        }
      }
    }),
 ```
- click in `signin button on home`
 
**Expected behavior**
Let the project work

**Screenshots or error logs**
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Users/vitor/Documents/projetos/project/.env
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
event - build page: /api/auth/[...nextauth]
wait  - compiling...
event - compiled successfully
(node:6567) UnhandledPromiseRejectionWarning: TypeError: (0 , _preactRenderToString.default) is not a function
    at signin (/Users/vitor/Documents/projetos/project/node_modules/next-auth/dist/server/pages/signin.js:46:44)
    at Object.signin (/Users/vitor/Documents/projetos/project/node_modules/next-auth/dist/server/pages/index.js:48:35)
    at /Users/vitor/Documents/projetos/project/node_modules/next-auth/dist/server/index.js:188:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/vitor/Documents/projetos/project/node_modules/next-auth/dist/server/index.js:52:103)
    at _next (/Users/vitor/Documents/projetos/project/node_modules/next-auth/dist/server/index.js:54:194)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6567) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:6567) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Additional context**
I created a blank project and followed the documentation, but the code simply doesn't work :(

**Comment by balazsorban44** [comment] 2021-03-07 21:12
when you say change provider to... do you mean it looks like `providers: Providers.Credentials...` or `providers: [ Providers.Credentials...`? My point here is that your providers option should still be an array. Is that the case? Could you maybe show the exact configuration you have?

**Comment by kennethvandenberghe** [comment] 2021-03-07 21:24
I've had the same problem. Made a small repo to reproduce the problem: https://codesandbox.io/s/inspiring-glade-pjbhu

**Comment by jaaneh** [comment] 2021-03-07 21:44
I realize this isn't related to the above error, but I've had a similar error pop up in 3.11.1 on my end. My sessions are always null now as well. 

Just thought I'd drop a comment to see if it's the release causing problems or what.

**Comment by jtwebb** [comment] 2021-03-07 21:47
I'll add another clue. The error is basically saying that `render` from `preact-render-to-string` isn't a function. If I change `_preactRenderToString.default` to `_preactRenderToString.default.default` in `dist/server/pages/signin` everything works. I'm not sure what that means exactly, but thought it might help narrowing it down.

<img width="575" alt="Screen Shot 2021-03-07 at 3 44 13 PM" src="https://user-images.githubusercontent.com/1922539/110256061-73b6a300-7f5c-11eb-92a2-2a5cbc32e6fc.png">

**Comment by Otoru** [comment] 2021-03-07 22:45
hello @balazsorban44 ,

As I put it in "Follow next-auth example code", I followed the project documentation so yes, I'm using an array of providers and I call the sign with `() => signIn()` on a button on my home page.

My project is basically what @balazsorban44 put as an example there.

**Comment by balazsorban44** [comment] 2021-03-07 23:21
Just so I understand it correctly, you simply copied the example project repo from https://github.com/nextauthjs/next-auth-example, added your above-mentioned provider and it did not work?

**Comment by jtwebb** [comment] 2021-03-07 23:26
An easy fix for this is to deconstruct the `render` function on the [signin page](https://github.com/nextauthjs/next-auth/blob/main/src/server/pages/signin.js#L2). I just gave it a try and built the project and it fixed the issue.

```js
import { render } from 'preact-render-to-string'
```

**Comment by balazsorban44** [comment] 2021-03-07 23:36
@jtwebb appreciate your help, but it would be nice to know why this suddenly broke for some. 

I did some digging, and I suspect it is something to do with this https://github.com/preactjs/preact-render-to-string/pull/173

**Comment by nk9** [comment] 2021-03-07 23:49
I am following [these steps from Vercel](https://vercel.com/guides/nextjs-prisma-postgres) and have run into this error as well. (I did change to use Google OAuth instead of GitHub.) Very new to Next.js, so I'm not sure if I can help narrow this down at all, but happy to try anything if it would help.

I tried putting the suggestion from @jtwebb on line 2 of the specified file in node_modules, but I got `SyntaxError: Cannot use import statement outside a module` for my trouble.

**Comment by jtwebb** [comment] 2021-03-07 23:49
@balazsorban44 I bet you're right. The package-lock.json file for this repo has preact-render-to-string resolved to version 5.1.7 and mine was resolved to 5.1.13. I forced mine to be 5.1.7 and it started working.

**Comment by balazsorban44** [comment] 2021-03-07 23:54
@nk9 they did it in the uncompiled/src version and built the module. You cannot use import statements in certain node versions (yet). Thanks for trying to help out, but I think we are on track here, thanks for the useful info @jtwebb!

So a temporary solution is then to edit `package-lock.json` to a version probably earlier than `5.1.12`.

The final solution might be that we just update our import statement to restructure `render, but I still want to know the reason.

**Comment by kennethvandenberghe** [comment] 2021-03-08 06:49
I've been trying each version of preact-render-to-string, it all keeps working up to and including v5.1.12. When I switch to v5.1.13 it breaks with this `not a function` error.

**Comment by marvinhagemeister** [comment] 2021-03-08 08:27
FYI: I've just released `v5.1.14` which reverts back to the previous commonjs behaviour. Regardless of whether the new behaviour is more correct, we shouldn't do such breaking changes in a patch release on our end. Sorry for the trouble caused by that. It should be all resolved now with `v5.1.14` 👍

**Comment by kennethvandenberghe** [comment] 2021-03-08 08:30
I can't reproduce the problem anymore when on preact-render-to-string@5.1.4 🎉  
thanks @marvinhagemeister

**Comment by balazsorban44** [comment] 2021-03-08 08:48
So nothing to do in our end then! Thanks so much for those involved that got to this so quickly! :)

Anyone discovering this, update your packages and make sure that you use at least `preact-render-to-string@5.1.14`! (check your lock files/node_modules)

See explanation above.

**Closed** 2021-03-08 08:49 UTC
Labels: bug, upstream

**Comment by condinoaljoseph** [comment] 2021-03-08 09:07
> So nothing to do in our end then! Thanks so much for those involved that got to this so quickly! :)
> 
> Anyone discovering this, update your packages and make sure that you use at least `preact-render-to-string@5.1.14`! (check your lock files/node_modules)
> 
> See explanation above.

Hi just a noob question. How do i update my package `preact-render-to-string@5.1.14` on my lock files? it is still 5.1.7 after i ran `npm update`

**Comment by condinoaljoseph** [comment] 2021-03-08 09:13
ow it worked i thought it stil `5.1.7` but when i use `npm ls preact-render-to-string` it state `5.1.14`. Thanks

**Comment by balazsorban44** [comment] 2021-03-08 09:47
Just an FYI, I updated our example repo and pushed a new release https://github.com/nextauthjs/next-auth/releases/tag/v3.11.2 that will use `5.1.14`, so anyone installing `next-auth@latest`, this issue shouldn't be possible anymore.

**Comment by jtwebb** [comment] 2021-03-08 10:18
Thank you @marvinhagemeister and @balazsorban44 for working so quickly to fix this!

**Comment by Otoru** [comment] 2021-03-08 12:28
Thank you to everyone involved. I managed to get on with the project here :)
