### ISSUE TITLE
Module '"next-auth/jwt"' has no exported member 'getToken'.ts(2305)

### ISSUE THREAD

**Issue by deadcoder0904** [nextauthjs/next-auth#2896] opened 2021-10-05 07:33 UTC
### Description 🐜

When I import `getToken` from `next-auth.jwt` like: 

```ts
import { getToken } from 'next-auth/jwt'
```

it gives a TS error:

> Module '"next-auth/jwt"' has no exported member 'getToken'.ts(2305)

It should be available as said in the docs → https://next-auth.js.org/configuration/options#jwt-helper

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Clone `next-auth-with-twitter-api-v2` branch & run the code → https://github.com/deadcoder0904/twitter-api-v2-3-legged-login-using-next-connect/tree/next-auth-with-twitter-api-v2

### Screenshots / Logs 📽

Nope.

### Environment 🖥

```
  System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 62.66 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.21.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 79.1.1.23
    Chrome: 94.0.4606.71
    Firefox Developer Edition: 88.0
    Safari: 14.1.2
  npmPackages:
    next: latest => 11.1.2
    next-auth: ^4.0.0-beta.2 => 4.0.0-beta.2
    react: ^17.0.2 => 17.0.2
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by deadcoder0904** [comment] 2021-10-05 07:39
It looks like it is exported indeed:

https://github.com/nextauthjs/next-auth/blob/eed0001524d67537c95ed6c5025766f17b93c2ef/types/jwt.d.ts#L56

And the examples in this repo suggest that it is working:

https://github.com/nextauthjs/next-auth/blob/885b02ca953456355552cc27eebd7931d97e1786/app/pages/api/examples/jwt.js#L7

But not sure why it isn't working in mine.

**Comment by balazsorban44** [comment] 2021-10-05 08:05
The default import might not work anymore, it has been removed:

```ts
import jwt from "next-auth/jwt" // this won't work
```

The closest you can get is:
```ts
import * as jwt from "next-auth/jwt"
```

We should probably mention it in the migration guide, and update references in the docs. Opened this issue: https://github.com/nextauthjs/docs/issues/61

**Comment by balazsorban44** [comment] 2021-10-05 08:13
After checking your repo, the problem seems to be related to this file:

https://github.com/deadcoder0904/twitter-api-v2-3-legged-login-using-next-connect/blob/next-auth-with-twitter-api-v2/declaration.d.ts

For some reason, this declaration is not merged correctly together with our built-in types, but it somehow overrides them.

I'll check what's happening, as I have the exact setup at work, and it works nicely. I suspect there might be a `tsconfig.json` option.

**Comment by balazsorban44** [comment] 2021-10-05 08:21
I found the solution! Adding this:
```ts
import "next-auth/jwt"
```

To the top of your `declaration.d.ts` makes the TS issue go away. I'll have to do some research as to why this is actually necessary.

**Comment by deadcoder0904** [comment] 2021-10-05 08:29
I added it at the top but it didn't make the error go away:

```ts
declare module 'next-auth/jwt' {
  import { JWT } from 'next-auth/jwt'

  interface JWT {
    [key: string]: {
      accessToken: string
      refreshToken: string
    }
  }
}
```

If I add it above `declare module` it gives error on `accessToken` & `refreshToken` saying:

> Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.ts(2322)
declaration.d.ts(5, 7): The expected type comes from property 'accessToken' which is declared here on type '{ accessToken: string; refreshToken: string; }'

**Comment by balazsorban44** [comment] 2021-10-05 08:29
Same with the other linked module augmentation post:

https://www.digitalocean.com/community/tutorials/typescript-module-augmentation#:~:text=First%2C%20we%20import%20our%20Pet%20class%20into%20our%20index.ts%20file.

So this is a documentation problem. I'll quickly fix this there and close this issue. Thanks for making this problem visible to us!

**Comment by deadcoder0904** [comment] 2021-10-05 08:31
@balazsorban44 So how do I fix this? Are you releasing a new beta version?

**Comment by balazsorban44** [comment] 2021-10-05 08:31
Nothing to do on our side. See https://github.com/nextauthjs/next-auth/issues/2896#issuecomment-934179656

**Comment by deadcoder0904** [comment] 2021-10-05 08:33
FYI, [this](https://github.com/nextauthjs/docs/commit/c9100056bf9f4a4536370c580508104c3b7c6b06) doesn't fix it for me.

It gives error like [this discussion](https://github.com/nextauthjs/next-auth/discussions/2886#discussioncomment-1423068)

See [the bottom error](https://github.com/nextauthjs/next-auth/issues/2896#issuecomment-934185771)

**Comment by balazsorban44** [comment] 2021-10-05 08:33
This has to be at the **top** of the file, so:

```ts
import { JWT } from "next-auth/jwt"

declare module "next-auth/jwt" {
  interface JWT {
    [key: string]: {
      accessToken: string
      refreshToken: string
    }
  }
}
```

**Comment by deadcoder0904** [comment] 2021-10-05 08:35
I even restarted the TS server in VSCode but still get the same error :(

**Comment by balazsorban44** [comment] 2021-10-05 08:36
For me:

Without:
![image](https://user-images.githubusercontent.com/18369201/135989324-82bc1e8d-dd34-45bb-9d8b-4d574b38076d.png)

With:
![image](https://user-images.githubusercontent.com/18369201/135989372-7cc58f70-bd2e-4ecd-b6c0-449919613359.png)

**Comment by balazsorban44** [comment] 2021-10-05 08:38
Not sure what else can cause this. It did fix on my machine, so there might be another element to it I cannot see.

Could you commit your changes to the reproduction repo so I can pull it and check again?

**Comment by deadcoder0904** [comment] 2021-10-05 08:45
Just pushed

**Comment by balazsorban44** [comment] 2021-10-05 08:51
Huh... It immediately makes the error go away on my side... :shrug:

**Comment by deadcoder0904** [comment] 2021-10-05 09:49
VSCode has TS v4.4.3 as I always install latest update. Wonder what's the error huh 🤔

**Comment by deadcoder0904** [comment] 2021-10-05 11:15
Alright, this fixed it:

```ts
import { JWT } from 'next-auth/jwt'

declare module 'next-auth/jwt' {
  interface JWT {
    [key: string]: {
      accessToken: string | undefined
      refreshToken: string | undefined
    }
  }
}
```

Just had to read the error 😂

Although I do think importing `JWT` at the top shouldn't be required as a user to me. The rest of it is user-specific stuff so that makes sense but `getToken` isn't!

**Comment by balazsorban44** [comment] 2021-10-05 13:51
This has nothing to do with `next-auth`, it's an upstream (TypeScript) thing and is related to how module augmentation works, sorry. Glad that you managed to fix the problem!

**Closed by balazsorban44** 2021-10-05 13:51 UTC
Labels: bug

**Comment by serg06** [comment] 2023-01-14 00:03
2023 answer - follow [their guide](https://next-auth.js.org/getting-started/typescript):

```ts
// IMPORTANT LINE, DO NOT REMOVE
import { JWT } from "next-auth/jwt"

declare module "next-auth/jwt" {
  /** Returned by the `jwt` callback and `getToken`, when using JWT sessions */
  interface JWT {
    /** OpenID ID Token */
    idToken?: string
  }
}
```

**Comment by kashyapro** [comment] 2023-07-18 16:38
> ```ts
> declare module 'next-auth/jwt' {
>   interface JWT {
>     [key: string]: {
>       accessToken: string | undefined
>       refreshToken: string | undefined
>     }
>   }
> }
> ```

Hey @serg06 , can you guide me how to resolve the getToken error? I am stuck.
