### ISSUE TITLE
Cannot scroll on page with table of contents (chrome)

### ISSUE THREAD

**Issue by thgh** [nextauthjs/next-auth#4054] opened 2022-02-23 10:57 UTC
### What is the improvement or update you wish to see?

I would like to scroll like before.

### Is there any context that might help us understand?

I also encountered this issue about a week ago.

It only happens when a table of contents (on the right) is visible. Removing that from DOM resolves the issue.

The first 100px is scrollable, after that any scroll position jumps back up immediately.

Device: Macbook with M1
Chrome: Version 98.0.4758.102 (Official Build) (arm64)
Chrome: Version 98.0.4758.109 (Official Build) (arm64)

Doesn't happen on Safari.

Video: 

https://user-images.githubusercontent.com/1109982/155306696-c5165c3b-bda7-4a03-8084-90cb9a88257c.mov

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/getting-started/introduction

**Comment by balazsorban44** [comment] 2022-02-23 13:38
I've had the same issue, but none of the others could reproduce, so I thought it was only me. Thanks! We'll look into this!

I somehow suspect it was due to an upgrade on Docusaurus.

**Comment by a-type** [comment] 2022-02-23 20:04
Temporary workaround: open console and run `window.addEventListener('scroll', ev => { ev.stopPropagation(); }, true);`.

**Comment by a-type** [comment] 2022-02-24 16:40
Happens in a fresh Guest window (no extensions), Chrome, 98.0.4758.102 (Official Build) (x86_64), on Mac. Does not occur in Firefox or Safari on the same platform.

**Comment by balazsorban44** [comment] 2022-02-28 00:58
OK, so it looks like Docusaurus identified the problem as a Chrome bug, and the workaround, for now, is to make sure that `chrome://flags/#enable-experimental-web-platform-features` is disabled. :+1:

I can confirm this fixed it for me.

More info on this issue: https://github.com/facebook/docusaurus/issues/6587

It looks like there is not much for us to do right now, so I'll close this. We are trying to be on the latest Docusaurus version at all times, so if there will be a fix for this, we will update anyway :+1:

**Closed by balazsorban44** 2022-02-28 00:58 UTC
Labels: bug, documentation

**Comment by tiagorangel2011** [comment] 2022-05-08 13:10
> OK, so it looks like Docusaurus identified the problem as a Chrome bug, and the workaround, for now, is to make sure that `chrome://flags/#enable-experimental-web-platform-features` is disabled. 👍
> 
> I can confirm this fixed it for me.
> 
> More info on this issue: [facebook/docusaurus#6587](https://github.com/facebook/docusaurus/issues/6587)
> 
> It looks like there is not much for us to do right now, so I'll close this. We are trying to be on the latest Docusaurus version at all times, so if there will be a fix for this, we will update anyway 👍

Thank you!!!!!
