### ISSUE TITLE
invalid dependency tree when updating to next@12.3.1

### ISSUE THREAD

**Issue by Yan-vibeit** [nextauthjs/next-auth#5436] opened 2022-09-27 18:53 UTC
### Environment

System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 22.18 GB / 31.91 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.50)    
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next: ^12.3.1 => 12.3.1
    next-auth: ^4.12.0 => 4.12.0
    react: 18.2.0 => 18.2.0

### Reproduction URL

/

### Describe the issue

├─┬ next-auth@4.12.0
│ └── next@12.3.1 deduped invalid: "12.2.5" from node_modules/next-auth
└── next@12.3.1 invalid: "12.2.5" from node_modules/next-auth

npm ERR! code ELSPROBLEMS
npm ERR! invalid: next@12.3.1 C:\Users\yancr\Documents\vibewavs\node_modules\next

### How to reproduce

update to latest next and next-auth.

### Expected behavior

When updating i expected both to remain in sync but it resulted in the next-auth install no longer functioning as intended.

**Comment by HotCustard** [comment] 2022-09-27 19:26
Same

unable to resolve dependency tree
npm ERR! Found: next@12.3.1
npm ERR! node_modules/next
npm ERR!   next@"12.3.1" from the root project
npm ERR! Could not resolve dependency:
npm ERR! peer next@"12.2.5" from next-auth@4.12.0

**Comment by TomFreudenberg** [comment] 2022-09-28 00:31
Duplicate: see #5427

solved but not yet released - waiting for next-auth@4.12.1

**Comment by balazsorban44** [comment] 2022-09-28 08:47
Duplicate of #5432

**Closed by balazsorban44** 2022-09-28 08:47 UTC
Labels: triage
