### ISSUE TITLE
502: BAD_GATEWAY from Vercel

### ISSUE THREAD

**Issue by dasveloper** [nextauthjs/next-auth#825] opened 2020-11-03 01:21 UTC
**Your question**
I'm getting sent to a Vercel error page showing "502: BAD_GATEWAY" on the callback from Google auth and Auth0. Both are working fine locally. I've checked the env variables multiple times to ensure they're correct. I tired creating new Google OAuth credentials and Auth0 credentials, a new Vercel app, a new Git repository, and a new Mongo Atlas DB, all of which still work locally but not on Vercel. 

```The error logs are correctly reading out all of my Google auth info followed by the error:
[next-auth][debug][typeorm_get_user_by_provider_account_id] [ 'google', '115431037803995017525' ]
[next-auth][debug][typeorm_get_user_by_provider_account_id] [ 'google', '115431037803995017525' ]
2020-11-03T01:15:57.090Z	c966b832-993e-4ed3-afe8-c18c37b39d37	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"","promise":{},"stack":["Runtime.UnhandledPromiseRejection","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
Unknown application error occurred
```
I've run out of ways to troubleshoot this error, it seems as if the callback URL `https://{domain}.com/api/auth/callback/google` just doesn't exist.

**What are you trying to do**
I'm trying to just get authentication to work, similar to how it is on my local copy.
**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment] 2020-11-03 09:27
> I've run out of ways to troubleshoot this error, it seems as if the callback URL https://{domain}.com/api/auth/callback/google just doesn't exist.

Like https://next-auth-example.now.sh/api/auth/callback/google I'd expected to return https://next-auth-example.now.sh/api/auth/error?error=oAuthCallback if visited in the browser as the request will be incomplete.

This should return all configured providers and their callback URLs:
https://next-auth-example.now.sh/api/auth/providers

It would be interesting to know if another provider (e.g. GitHub) works to understand if the issue is specific to Google (e.g. is it an OAuth callback problem or a database connection problem).

As I cannot replicate this issue with the example project, we will probably need access to the repo to delve into this.

**Comment by dasveloper** [comment] 2020-11-03 22:03
I think I've figured it out, I started fresh with a new cloned repo of the example project. Installed mongodb from Atlas, added Google oAuth credentials, ran yarn install, and ran yarn dev and my authentication failed because of a failed DB connection.  It was getting the same error found in this [typeorm issue](https://github.com/typeorm/typeorm/issues/7009). 

I added this to the end of my package.json
```
  "resolutions": {
    "next-auth/typeorm": "0.2.25"
  }
```
Deleted my .next, node_modules, and yarn.lock and then re-ran yarn install and yarn dev again and the connection and authentication worked fine. I then tried removing that code from my package.json and deleting and reinstalling everything again and it was broken again confirming to me that the typeorm version was the issue.

**Comment by iaincollins** [comment] 2020-11-04 09:53
Thanks for the follow up! This is really helpful.

While we have good coverage for database errors, debugging bugs elsewhere is currently difficult as there currently isn't much support for debugging or error handling outside of the database adapter logic (just something that hasn't been got round to yet)

I'm happy to leave this open until we have created an issue to capture improving the debugging for callbacks like this.

Did you find a way to do what you wanted (e.g. select by email address in this function) / is "reject if not in database" an option that would be useful? (There are some caveats to doing that, but I can see a good case for it...)

**Comment by abcd-ca** [comment] 2020-12-07 17:57
I figured it out! I was using the Email provider and the same thing was happening. Vercel apparently doesn't like JS uncaught exceptions. We were marking our callback as `async` and throwing from within it without a `catch`. We were doing this because the docs say we should do this (whether throw or Promise.reject(new Error) – either way, same result). 

@dasveloper Your code should work if it's rewritten like this:

```javascript
signIn: (user) => {
  if (!user.id) {
    return Promise.reject(new Error("Sorry, I couldn't find that user");
  }
  return Promise.resolve(true);
},
```

Note, I removed `async` and am returning all promise calls. In my code I make a call to the database to see if my user is on the whitelist. My function returns true if it succeeds and throws a new error if it fails. I was using async and await for my function call but now mine looks like this:

```javascript
signIn: (user, account, profile) => {
  openDBConnection()
  return userIsOnWhitelist(user.email)
    .finally(() => {
      return knex.destroy()
    })
},
```

Here again, I removed the `async`. Instead of doing a try/catch/finally in the callback, and putting `await` in front of the `userIsOnWhitelist` call, I `return userIsOnWhitelist` because it already returns a promise (`userIsOnWhitelist is itself defined as an `async` function that returns a boolean on success or throws on error. Reminder, `async` compiles as a resolving/rejecting promises). In my case I also wanted to make sure I closed the db connection so using traditional promise syntax I add a `.finally` callback too.

I will make a PR to update the docs.

**Comment by balazsorban44** [comment] 2020-12-07 19:38
@abcd-ca @dasveloper
This should work:

```js
async signIn​(​user​)​​ ​{​
  ​if​ ​(​!​user​.​id​)​ ​{​
    ​throw new​ ​Error​(​"Sorry, I couldn't find that user"​)​;​
  ​}​
  ​return​ ​true​)​
​}
```
Or if you really want an arrow function:
```js
signIn​: async (​user​)​​ ​=> {​
  ​if​ ​(​!​user​.​id​)​ ​{​
    ​throw new​ ​Error​(​"Sorry, I couldn't find that user"​)​;​
  ​}​
  ​return​ ​true​)​
​}
```

**Closed** 2020-12-07 20:08 UTC
Labels: question
