### ISSUE TITLE
V4 Error: HTTP POST is not supported for /api/auth/callback/credentials 

### ISSUE THREAD

**Issue by madeinspace** [nextauthjs/next-auth#2858] opened 2021-09-29 08:31 UTC
### Description 🐜

Just upgraded to v4 and I'm getting the error in the title when I set the id of the CredentialsProvider

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

  CredentialsProvider({
      id: "username-login", // <- add this line

### Environment 🖥

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
    Memory: 22.92 GB / 31.81 GB
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 94.0.4606.61
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.31)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    next: 9.4.4 => 9.4.4
    next-auth: ^4.0.0-beta.2 => 4.0.0-beta.2
    react: ^17.0.2 => 17.0.2

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment] 2021-09-29 09:00
Will need a reproduction.

**Comment by madeinspace** [comment] 2021-09-29 09:52
My project is way too involved to provide a repro unfortunately, can I attach a video ?

**Comment by balazsorban44** [comment] 2021-09-29 10:04
Seeing your `[...nextauth].js` file and the way you call `signIn` would be a good start.

**Comment by madeinspace** [comment] 2021-09-30 04:12
Yep sure my [...nextauth].js looks like this:

`import NextAuth from 'next-auth';
import CredentialsProvider from 'next-auth/providers/credentials'

const isAuthorised = async (credentials, req) => {
  const { cosmosdb } = req;
  const client_collection = await cosmosdb.collection('Clients');
  const client = await client_collection.findOne({ clientAlias: credentials.handle });
  const {
    clientID,
    clientAlias,
    login: { username, password },
  } = client;
  const isValid = credentials.username === username && credentials.password === password;
  const user = isValid ? { id: clientID, name: clientAlias, handle: clientAlias } : null;
  return user;
}


const options = {
  debug: true,
  providers: [
    CredentialsProvider({
      name: 'Credentials',
      credentials: {
        handle: { type: 'hidden', label: "handle", type: "text" },
        username: { label: "Username", type: "text" },
        password: { label: "Password", type: "password" }
      },
      async authorize(credentials, req) {
        const user = await isAuthorised(credentials, req)
        if (user) {
          return user
        }
        return null
      }
    })
  ],
  pages: {
    signIn: '/auth/credentials-signin',
  },

}

export default (req, res) => NextAuth(req, res, options);`


an d my custom signing component:

`import { getCsrfToken } from 'next-auth/react';
import React from 'react';
import styled from 'styled-components';
import { SigninButton } from '../../styles/MainContentStyles';
import { getParameterByName } from '../../utils';

export default function SignIn({ csrfToken, client }) {
  const { clientAlias } = client;
  const clientLogoUrl = `https://econext-cdn.azureedge.net/eco-assets/client-logos/${clientAlias}.png`;
  const errorMessage = process.browser
    ? getParameterByName('error') === 'CredentialsSignin'
      ? 'Invalid user - please try again.'
      : ''
    : '';
  return (
    <Limiter>
      <LoginContainer>
        <LoginWrapper>
          <LoginForm method="post" action="/api/auth/callback/credentials">
            <Spacer>
              <input name="csrfToken" type="hidden" defaultValue={csrfToken} />
              <input name="handle" type="hidden" value={clientAlias} />
              <LoginTitle>
                <img src={clientLogoUrl} />
              </LoginTitle>
              <InputWrapper>
                <InputText required name="username" type="text" />
                <FloatingLabel>username</FloatingLabel>
              </InputWrapper>
              <InputWrapper>
                <InputText required name="password" type="password" />
                <FloatingLabel>password</FloatingLabel>
              </InputWrapper>
              {errorMessage && <ErrorMessage>{errorMessage}</ErrorMessage>}
            </Spacer>
            <SigninButton type="submit">Sign into Economy.id</SigninButton>
          </LoginForm>
        </LoginWrapper>
      </LoginContainer>
    </Limiter>
  );
}

export async function getServerSideProps(context) {
  const {
    req: { query, cosmosdb },
  } = context;
  let url = new URL(query.callbackUrl);

  const client_collection = await cosmosdb.collection('Clients');
  const clientAlias = url.pathname.split('/')[1];
  const client: any = await client_collection.findOne({ clientAlias: clientAlias });

  return {
    props: {
      csrfToken: await getCsrfToken(context),
      client,
    },
  };
}`

**Comment by balazsorban44** [comment] 2021-09-30 07:27
your code doesn't seem to have the id you set in your original post. which one is the right? 🤔

**Comment by madeinspace** [comment] 2021-09-30 07:42
Yes I removed it because it breaks when I open the sign-in form with the error above

**Comment by balazsorban44** [comment] 2021-09-30 07:49
So the error is gone, then? :sweat_smile:

Remember when you set a custom id, your callback URL also has to change.

Eg.:

```js
CredentialsProvider({
id: "username-login", // <- add this line
```
will need

`/api/auth/callback/username-login`

If that does not resolve your issue, please come back. But for now, I'll close this. I tested it locally, and could not reproduce, and your reproduction also differs from the code that caused you the issue. :shrug:

**Closed by balazsorban44** 2021-09-30 07:49 UTC
Labels: bug, incomplete
