### ISSUE TITLE
There is no exhaustive guide for setting up auth. 

### ISSUE THREAD

**Issue by 0pankajkumar** [nextauthjs/next-auth#10052] opened 2024-02-17 05:18 UTC
### What is the improvement or update you wish to see?

I would like to see a guide starting from scratch to set it up and get it working

### Is there any context that might help us understand?

There are scattered docs available for everything but no one page read and implement type guide

**Comment by m-muiznieks** [comment] 2024-02-17 17:34
For me was really helpful this video tutorial: https://youtu.be/1MTyCvS05V4 
Guy goes through from social login to email auth - I think it will give a good understanding of core functionalities. 

(Just trying to help)

**Comment by bwheeele** [comment] 2024-02-17 18:59
I agree it's very confusing. It says one thing on auth.js docs and then another things on the github, and then something else different somewhere else. The video is super helpful. Funny enough I found it today too but I am getting an error for missing module for next/server and completely lost what to do.

**Comment by m-muiznieks** [comment] 2024-02-17 19:13
Yes, I know what you're talking about. 

Currently I am sitting on 5.0.0-beta.4 version. I found out that slightly changing the module imports solves this issue. 

For example: import NextAuth from "node_modules/next-auth";

I am not a specialist, but a total novice but I understood, that the issue somehow is related to next-auth.d.ts file (?). As it in one moment just started everything to point to that exact file instead of module. 

But I am reserving the rights to be totally wrong about that - the only thing is important, that quick fix is possible with adding node_modules before the next-auth related paths.

**Comment by bwheeele** [comment] 2024-02-17 19:17
@m-muiznieks Is yours like this too? ⨯ Error [ERR_MODULE_NOT_FOUND]: Cannot find module '//node_modules/next/server' imported from //node_modules/next-auth/lib/env.js
Did you mean to import "next/server.js"?

**Comment by zhaozhonglei** [comment] 2024-02-22 21:30
I also got this error,  Cannot find module 'node_modules/next/server' imported from node_modules/next-auth/lib/env.js .
"next": "14.1.0",
"next-auth": "^5.0.0-beta.13",

**Comment by tedkalaw** [comment] 2024-03-06 00:27
i got the same error on `next@14.1.1` and `next-auth@5.0.0-beta.15`

i was able to get it going setting `esmExternals` to `false` but that seems not ideal. i'm guessing it has something to do with my project configuration

**Comment by tedkalaw** [comment] 2024-03-06 00:28
> @m-muiznieks Is yours like this too? ⨯ Error [ERR_MODULE_NOT_FOUND]: Cannot find module '//node_modules/next/server' imported from //node_modules/next-auth/lib/env.js Did you mean to import "next/server.js"?
> 
> Any time I hit api/auth anything I get this error.

i got the same error on `next@14.1.1` and `next-auth@5.0.0-beta.15`

i was able to get it going setting `esmExternals` to `false` but that seems not ideal. i'm guessing it has something to do with my project configuration

**Comment by bwheeele** [comment] 2024-03-06 13:06
I was able to fix it by adding .js to end of all the files with server/navigation. I don't understand why I have to do this though and this is not a proper fix. I have auth.js and next same versions in a separate app and don't have this issue. The other was created from scratch and the one I am getting the error on was added into existing code. Really disappointing to not here any feedback yet as to what the issue is or how to fix it.

**Comment by ndom91** [comment] 2024-04-12 12:56
Hey sorry for the confusion folks, we've released a whole new docs website which includes some nice walkthroughs for all the authentication types.

For example for OAuth: https://authjs.dev/getting-started/authentication/oauth

I'm going to close this issue, but feel free to open a new one if you still have a specific issue :pray:

**Closed by ndom91** 2024-04-12 12:56 UTC
Labels: documentation, triage

**Comment by sKopheK** [comment] 2024-10-31 15:12
migration from v4 when you have a lot of custom code is hell too. searching for a simple keyword in the website is very rusty, for example "middleware" gives you this load of everything and you need to search in the search results to get your search results. some filtering, ordering by importance would help for sure
![{AA06B73D-BBFD-40C4-BAD9-81736EA52FE6}](https://github.com/user-attachments/assets/77015e43-887a-4ebf-a3c9-2e0bd9ec1345)
