### ISSUE TITLE
Unable to log in with Google as provider on iOS devices - ERROR 403: disallowed_useragent

### ISSUE THREAD

**Issue by nwinger** [nextauthjs/next-auth#7044] opened 2023-03-24 11:35 UTC
### Provider type

Google

### Environment

Latest version running on https://next-auth-example.vercel.app/

### Reproduction URL

https://next-auth-example.vercel.app/

### Describe the issue

Unable to use Google as an authentication provider on any iOS device. 
Prompted with login selection, and when I select Google, I'm presented with an error screen

`Error 403: disallowed_useragent
Request details: response_type=code redirect_uri=https://next-auth-example.vercel.app/api/auth/callback/google state=HAO-mlt2PWGmZlwmvGazFwRhySgXEOyUC4SlqYNIccA code_challenge_method=S256 client_id=28021217629-k9er4jcd6lec0vkj9uvadeat9emko120.apps.googleusercontent.com code_challenge=7n7tlU9nPJwkpKUxLKFaYAHf4zibmAk6XOUCHj4yl9Q access_type=online scope=openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
`

### How to reproduce

Can be reproduced both on native iOS devices and in browser, emulating an iOS device.

Native:
- Open Chrome, Edge or similar on iOS device.
- Navigate to https://next-auth-example.vercel.app/ and login with Google as the selected provider.
- Start the login flow

Desktop
- Open Chrome, Edge or similar
- Toggle developer mode
- Toggle device simulation
- Select an iOS device
- Navigate to https://next-auth-example.vercel.app/ and login with Google as the selected provider.
- Start the login flow

### Expected behavior

Should be able to login without error.

**Comment by balazsorban44** [comment] 2023-03-24 12:19
Actually, I could not reproduce this. I realized I have access to a simulator (running on an actual iPhone), and it logs in fine. :thinking:

![image](https://user-images.githubusercontent.com/18369201/227519424-1039fd1e-b34c-48e4-82bf-a8da05d7f1d4.png)

**Comment by balazsorban44** [comment] 2023-03-24 13:15
Closing, as I talked to @nwinger, and it seems that this was an isolated edge-case which now seems to work. :tada:

**Closed by balazsorban44** 2023-03-24 13:15 UTC
Labels: providers, triage

**Comment by muhaimincs** [comment] 2023-06-29 05:27
I'm still having this issue if my user try to open the link from facebook apps. How do you guys solve it

**Comment by leandrovi** [comment] 2023-07-05 19:03
This always happens inside a webview (e.g., when trying to log in inside Instagram's webview). This issue is still there, is there any way to avoid the error `Error 403: disallowed_useragent` in this case?

**Comment by balazsorban44** [comment] 2023-07-05 19:11
Unfortunately, there's nothing we can do here as a library. Google apparently deems Instagram's WebView insecure.

https://support.google.com/accounts/answer/12917337?hl=en#403disallowed

**Comment by adam-binks** [comment] 2023-07-10 13:48
A workaround using [is-ua-webview](github.com/atomantic/is-ua-webview):

```js
export async function signInToMyApp() {
  if (isWebview(window.navigator.userAgent)) {
    toast("Open Fatebook in Safari or Chrome to sign in.\n\nGoogle does not support this browser.", {
      duration: 10000,
    })
    return
  }
  await signIn()
}
```

**Comment by CyrusVorwald** [comment] 2024-03-15 04:27
Couldn't the button that initiates the signIn, or an intermediary page, use _blank noopener noreferrer? I am having this issue myself and am unsure how to handle it.

**Comment by felixcarmona** [comment] 2024-09-14 20:46
> A workaround using [is-ua-webview](https://github.com/atomantic/is-ua-webview):
> 
> ```js
> export async function signInToMyApp() {
>   if (isWebview(window.navigator.userAgent)) {
>     toast("Open Fatebook in Safari or Chrome to sign in.\n\nGoogle does not support this browser.", {
>       duration: 10000,
>     })
>     return
>   }
>   await signIn("google")
> }
> ```

Starting with iOS 17, you can use the Safari URL scheme (`x-safari-https://example.com` or `x-safari-http://example.com`) to directly open the correct browser. You can do the same on Android using an intent. For a more detailed explanation about this issue, you may find the following link useful: https://felixcarmona.com/solving-google-login-issues-linkedin-ios/.
