### ISSUE TITLE
SessionContext always reloads session after populating it from getServerSession()

### ISSUE THREAD

**Issue by Thinkscape** [nextauthjs/next-auth#7399] opened 2023-04-29 00:39 UTC
### Environment

```
  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 87.27 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 104.0.2
    Safari: 16.4

dependencies:
next 13.3.1
next-auth 4.22.1
react 18.2.0
```

### Reproduction URL

...

### Describe the issue

When `<SessionProvider>` is fed a session from `getServerSession()` it will always re-load it in client context, which defeats the purpose of the hydration.

### How to reproduce

1. Use next.js app directory.
2. Have a `<SessionProvider>` pre-filled with session obtained from RSC

```tsx
export default async function RootLayout({children} : { children: ReactNode }) {
  const session = await getServerSession(authOptions); // gets session from db or cookie

  return 
    <MySessionProvider session={session}>
      {children}
    </MySessionProvider>;
}
```
```tsx
"use client"
import { SessionProvider } from 'next-auth';

export default function MySessionProvider({ session: Session, children: ReactNode }) {
  return 
    <SessionProvider session={session} refetchInterval={99999} refetchOnWindowFocus={false} refetchWhenOffline={false}>
      {children}
    </Session>
  ;
}
```
3. Run in browser

### Expected

1. Using `console.log` or React inspector look at the contents of session context
2. The session context is equal to `{ data: { whatever-came-from-server } }`
3. No additional network requests happen in browser.

### Actual

1. Using `console.log` or React inspector look at the contents of session context
2. The initial session context is `{ data: { whatever-came-from-server } }`
3. `next-auth` sends a network request to `/api/auth/session`
4. The session context values changes to `{ expires: '...', data: { same-value } }`

### Why?

Because `expires` is removed here:

https://github.com/nextauthjs/next-auth/blob/5da6549c48952b2a720342c5dbb555bc4c2cd39f/packages/next-auth/src/next/index.ts#L224-L229

### Workaround

Appending the missing `session.expires` manually fixes the problem, i.e. 

```
  const session = await getServerSession(authOptions); // gets session from db or cookie
  session.expires = new Date(new Date().getTime() + 10000000).toISOString();
```

**Comment by Thinkscape** [comment] 2023-04-29 00:42
Could it be the lack of `expires` field emitted from `getServerSession()`?
That could be an easy fix 🤔

**Comment by Thinkscape** [comment] 2023-04-29 00:54
To quote Han Solo, I've got a bad feeling about this ... 
I feel like @balazsorban44 is going to close it as question in 3... 2... 1... 🤣 

I imagine the reasoning there is that `getServerSession()` could also be used in api routes and such, where it's supposed to be treated as snapshot, short-lived data, with server-side session refreshing not being implemented.

**Comment by balazsorban44** [comment] 2023-04-29 06:08
Hi, so in App Router you don't actually need `SessionProvider`. As you mentioned, you can just use `getServerSession` instead, which can be used in any server component, and then, if you need to, just pass the session down as a prop to any client component.

The reason why `expires` is stripped is mentioned in our [docs](https://next-auth.js.org/configuration/nextjs#in-app-directory).

Im working on a solution to handle automatic refreshing, even via the App Router.

**Comment by Thinkscape** [comment] 2023-04-29 11:19
> you don't actually need SessionProvider [...] which can be used in any server component, and then, if you need to, just pass the session down as a prop to any client component.

While it is true that you can pass it down, that only works if you've got simplistic component structure or you're fine with prop drilling (like it's 2016 😄 ), as context doesn't work in RSC. Usually an app would consist of mixture of server and client components, in which case you don't want to be passing down session everywhere. 
Alternatively you `getServerSession` in multiple layers in RSC right above the client components, but then you're doing a lot of additional processing for getting the exact same result (unless you memoize it, which is another step)

**Comment by JasperAlexander** [comment] 2023-04-29 19:18
> Hi, so in App Router you don't actually need `SessionProvider`. As you mentioned, you can just use `getServerSession` instead, which can be used in any server component, and then, if you need to, just pass the session down as a prop to any client component.

You can't use a custom session object with `getServerSession` without a `SessionProvider`.

**Comment by balazsorban44** [comment] 2023-04-30 07:48
@Thinkscape 

> Alternatively you call getServerSession several times, in multiple layers of RSC (right above the client components), but then you're doing a lot of additional processing for getting the exact same result (unless you memoize it, which is another step)

This is the preferred method in RSC. If you are worried about perf., check out https://beta.nextjs.org/docs/data-fetching/caching#per-request-caching but based on if you are using a JWT or database strategy, it _might_ be unnecessary.

Re: prop drilling, it depends on your architecture, but I cannot give suggestions as you did not attach a reproduction. Most likely, you could just render the session-dependent components via a server component anyway instead of a client component.

@JasperAlexander

> You can't use a custom session object with getServerSession without a SessionProvider.

Not sure what this refers to.


Anyway, I do think we should close this, because of the explained reasons from the documentation. https://github.com/nextauthjs/next-auth/issues/7399#issuecomment-1528678805

**Closed by balazsorban44** 2023-04-30 07:48 UTC
Labels: triage

**Comment by Thinkscape** [comment] 2023-05-01 00:59
> Re: prop drilling, it depends on your architecture, but I cannot give suggestions as you did not attach a reproduction. Most likely, you could just render the session-dependent components via a server component anyway instead of a client component.

Prop drilling is a known design shortcoming of React, I didn't know I had to explain it in this case. RSC are new, but their design just doesn't support Context which elevates this issue and `next-auth` design compromise.

I think I want to push back though @balazsorban44.

```js
  session: {
    strategy: "database",
    maxAge: 60,
    updateAge: 30,
  },
```

* I'm using database strategy.
* Sessions are identified with an `id` and the expiration is stored in a database.
* `getServerSession` has no reason to remove `expiry` date -- it is well known and stored as a field in the db. It is also perfectly capable to respect `session.maxAge` and `session.updateAge` as it can easily `UPDATE` the field in db.
* This provides RSC parity with the `useSession` equivalent in client components.

Hence the `expires` stripping and reasoning in https://next-auth.js.org/configuration/nextjs#in-app-directory only seems to apply to the `jwt` strategy, and this issue report still holds.

**Comment by balazsorban44** [comment] 2023-05-01 12:29
With RSC, you just reach for the state (even if it's coming from a database) wherever you need it, there is simply no need for a context anymore, thanks to the new caching APIs, which will make sure there won't be overhead. The documentation from the React team is coming (that's why for now I linked to https://beta.nextjs.org/docs/data-fetching/caching#per-request-caching), as the API is being tested via Next.js.


The session cookie's expiry is independent of the expiry saved in the database, although they are in sync. Even if we update the actual value in the database, the session cookie's expiry won't reflect it, hence causing an undesired state where a session exists in the database, even if the session cookie got deleted because of the missing rotation.

As already explained in https://github.com/nextauthjs/next-auth/issues/7399#issuecomment-1528678805, I am working on a solution to resolve this problem, which will involve using Middleware to rotate the expiry dates correctly, and there will be a new API to read the auth state anywhere, similar to `getServerSession`, but without the aforementioned shortcoming.

**Comment by Thinkscape** [comment] 2023-05-02 00:42
Thanks for taking the time to dive a bit deeper with me. That explains it much better.
I've taken some inspiration from what Clerk does, re-implementing some of it with `next-auth` (in my project). 

I think they "borrowed" a lot of the `next-auth` architecture while introducing some decent improvements, esp. for [edge friendliness](https://edge.clerk.app/). I'm not a fan of vendor lock-in however, so can't wait to see what's next for the project 🎉

**Comment by balazsorban44** [comment] 2023-05-02 14:36
Stay tuned... :wink:

**Comment by michaelhays** [comment] 2023-05-12 18:55
FWIW, using this pattern with [Zustand](https://github.com/pmndrs/zustand) is working well for me, in order to share the server session with client components:

`app/layout.tsx`
```tsx
import { getServerSession } from 'next-auth'
import { redirect } from 'next/navigation.js'
import type { ReactNode } from 'react'
import nextAuthServerSessionOptions from './api/auth/[...nextauth]/serverSessionOptions.ts'
import AppLayoutClient from './layoutClient.tsx'

type Props = {
  children: ReactNode
}

export default async function AppLayout({ children }: Props) {
  const session = await getServerSession(nextAuthServerSessionOptions)

  if (!session) {
    redirect('/login')
  }

  return <AppLayoutClient session={session}>{children}</AppLayoutClient>
}
```

`app/layoutClient.tsx`
```tsx
'use client'

import type { Session } from 'next-auth'
import type { ReactNode } from 'react'
import lodash from 'lodash'
import useSessionStore from './sessionStore.ts'

type Props = {
  session: Session
  children: ReactNode
}

export default function AppLayoutClient({ session, children }: Props) {
  const { session: clientSession, setSession } = useSessionStore()

  if (!lodash.isEqual(session, clientSession)) {
    setSession(session)
  }

  if (!clientSession) {
    return null
  }

  return <>{children}</>
}
```

`app/sessionStore.ts`
```ts
import type { Session } from 'next-auth'
import { create } from 'zustand'

type SessionStore = {
  session: Session
  setSession: (session: Session) => void
}

const useSessionStore = create<SessionStore>()((set) => ({
  // @ts-expect-error: `session` should be non-null whenever used
  session: null,
  setSession: (session) => set({ session }),
}))

export default useSessionStore
```

`app/SomeClientComponent.tsx`
```tsx
'use client'

import useSessionStore from './sessionStore.ts'

export default function AppPageClient() {
  const { session } = useSessionStore()

  return <p>User: {session.user.name}</p>
}
```

**Comment by SrBrahma** [comment] 2024-01-07 16:34
@michaelhays there seems to be this existing solution: https://next-auth.js.org/getting-started/client#sessionprovider
