### ISSUE TITLE
props returned from `getServerSideProps()` due to _app.tsx `pageProps` problem

### ISSUE THREAD

**Issue by ChristianDBrooks** [nextauthjs/next-auth#6099] opened 2022-12-17 02:36 UTC
### Environment

 System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 71.16 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.12.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.1.2 - /usr/local/bin/npm
    Watchman: 2021.08.30.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 14.0.3
  npmPackages:
    next: latest => 13.0.7 
    next-auth: latest => 4.18.6 
    react: ^18.2.0 => 18.2.0 

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

I have duplicated the issue I have seen in my project using the next-auth-example as a template. Any prop returned from getServerSideProps() does not get passed to the page props. This can be seen in [/pages/server.tsx](https://github.com/nextauthjs/next-auth-example/blob/main/pages/server.tsx).

You can also go to https://next-auth-example.vercel.app/server, and sign in. You will not see the rendered element written on [line 31 in /pages/server.tsx](https://github.com/nextauthjs/next-auth-example/blob/main/pages/server.tsx#L31)

<pre>{JSON.stringify(session, null, 2)}</pre>
This should be rendered, but session is null, even though it has the correct session value before being returned by getServerSideProps(). Note: I have tested this even just passing a string value and the prop comes out undefined

I believe this is related to a problem in `_app.tsx` [on line 11](https://github.com/nextauthjs/next-auth-example/blob/8519a8091feeb20bee7f91fa929dcdfa98e4d841/pages/_app.tsx#L11). When I remove `: { session, ...pageProps },` from line 11 of code in `_app.tsx` my server side props are passed as expected.

```javascript
// line 11
pageProps: { session, ...pageProps },
```
So this works:
```js
export default function App({
  Component,
  pageProps,
}: AppProps) {
  return (
    <SessionProvider session={session}>
      <Component {...pageProps} />
    </SessionProvider>
  )
}
```
but the original does not:
```js
export default function App({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps<{ session: Session }>) {
  return (
    <SessionProvider session={session}>
      <Component {...pageProps} />
    </SessionProvider>
  )
}
```

### How to reproduce

1. Setup a new example app https://github.com/nextauthjs/next-auth-example/blob/main/README.md
2. I configured a GoogleProvider and that is
3. Look at `/pages/server.tsx`. `session` prop does not get passed as expected.

### Expected behavior

Server side props are populated in page component with next-auth pageProps configuration

**Comment by ChristianDBrooks** [comment] 2022-12-17 02:52
Update: I was able to find a solution that fixed the problem in my clone of `next-auth-example`

change the `App()` implementation to 

```jsx
export default function App({
  Component,
  pageProps, // <--- removed spreading
}: AppProps<{ session: Session }>) {
  return (
    <SessionProvider session={pageProps?.session}> // <--- dot notate into session prop
      <Component {...pageProps} />
    </SessionProvider>
  );
}
```

**Comment by ChristianDBrooks** [comment] 2022-12-17 02:53
Accidentally closed, leaving open so decision can be made if this needs to added to the example app.

**Comment by balazsorban44** [comment] 2022-12-17 06:33
duplicate of #5891

**Closed by balazsorban44** 2022-12-17 06:33 UTC
Labels: triage
