### ISSUE TITLE
NextAuth provider not working with custom nextjs pageExtensions

### ISSUE THREAD

**Issue by joao-pedrozo** [nextauthjs/next-auth#1495] opened 2021-03-11 01:05 UTC
**Describe the bug**
I'm using Relay which generates a `__generated__` folder inside my `pages` folder, and that's not allowed by Next(it just accept react components inside the `pages` folder). So, I added to `next.config.js` the config `pageExtensions: ['page.js']` and rename all my `pages/` files to the `.page.js` extension. Now, he'll no longer consider files without this extension as a React component.

The problem is: my nextAuth app provider(the one inside `_app` file) is printing an error in every single page that I enter, that's why he's breaking because this custom extension. The errors are: 

`GET http://localhost:3000/api/auth/session 404 (Not Found)`

`[next-auth][error][client_fetch_error] 
https://next-auth.js.org/errors#client_fetch_error /api/auth/session SyntaxError: Unexpected token < in JSON at position 0`

`POST http://localhost:3000/api/auth/_log 404 (Not Found)`

**Steps to reproduce**
- Create a next app with nextAuth and add the nexAuth provider in the `_app` file.
- Create a `next.config.js` file and add the `pageExtensions: ['page.js']` config
- Rename all your ´/page´ files to the `.page.js` extension
- Now you should get a few errors on your console

The repo I'm having this issue is: https://github.com/joao-pedrozo/reviewanything/tree/master/packages/frontend/src/pages

**Expected behavior**
I think that should automatically identify my next.config.js file and adapt to the provider work as expected.

**Screenshots or error logs**
`GET http://localhost:3000/api/auth/session 404 (Not Found)`

`[next-auth][error][client_fetch_error] 
https://next-auth.js.org/errors#client_fetch_error /api/auth/session SyntaxError: Unexpected token < in JSON at position 0`

`POST http://localhost:3000/api/auth/_log 404 (Not Found)`

**Additional context**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by viniciuscr** [comment] 2021-03-16 19:12
make sure the `[...nextauth].js`follows the same rule for page extensions
is should be something like: `/pages/auth/[...nextauth].page.js`

**Comment by balazsorban44** [comment] 2021-03-16 19:36
https://github.com/nextauthjs/next-auth/issues/1441 Looks to be very similar, I'm wondering if it's a duplicate. 🤔

**Comment by kettanaito** [comment] 2021-10-15 15:12
I'm getting the exact error. Deleting `.next` and re-running didn't help. It seems like the nested `[...nextuath].page.ts` routes are not considered pages by Next (not necessarily Next Auth's issue).

**Comment by ThangHuuVu** [comment] 2023-03-25 07:28
Seems like not a bug with NextAuth.js but a problem with the Next.js app setup. Closing 🙇‍♂️

**Closed by ThangHuuVu** 2023-03-25 07:28 UTC
