### ISSUE TITLE
GitHub Provider OAuthCallback error when using signin callback function

### ISSUE THREAD

**Issue by felixhaeberle** [nextauthjs/next-auth#6729] opened 2023-02-15 16:19 UTC
### Environment

System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 7.17 GB / 64.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 104.0.2
    Safari: 16.3

### Reproduction URL

it's currently running on localhost

### Describe the issue

Hey, there! When using the GitHub provider with an callback signin url it gives me a strange error:

```sh
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error access_token not present in TokenSet {
  error: {
    message: 'access_token not present in TokenSet',
    stack: 'TypeError: access_token not present in TokenSet\n' +
      '    at Client.requestResource (/Users/felixhaberle/Desktop/git/backstage/node_modules/openid-client/lib/client.js:1117:15)\n' +
      '    at Client.userinfo (/Users/felixhaberle/Desktop/git/backstage/node_modules/openid-client/lib/client.js:1235:33)\n' +
      '    at Object.request (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/providers/github.js:22:38)\n' +
      '    at oAuthCallback (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/core/lib/oauth/callback.js:124:41)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async Object.callback (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/core/routes/callback.js:50:11)\n' +
      '    at async NextAuthHandler (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/core/index.js:176:28)\n' +
      '    at async NextAuthNextHandler (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/next/index.js:23:19)\n' +
      '    at async Object.apiResolver (/Users/felixhaberle/Desktop/git/backstage/node_modules/next/dist/server/api-utils/node.js:366:9)\n' +
      '    at async DevServer.runApi (/Users/felixhaberle/Desktop/git/backstage/node_modules/next/dist/server/next-server.js:481:9)',
    name: 'TypeError'
  },
  providerId: 'github',
  message: 'access_token not present in TokenSet'
}
```  

I don't understand this error and don't know how to debug it.

This is my config file:

```ts
import { PrismaAdapter } from "@next-auth/prisma-adapter";
import { NextApiHandler } from "next";
import NextAuth from "next-auth";
import EmailProvider from "next-auth/providers/email";
import GithubProvider from "next-auth/providers/github";
import GitlabProvider from "next-auth/providers/gitlab";
import GoogleProvider from "next-auth/providers/google";
import { getInvite } from "../../../helper/invites/airtable";
import prisma from "../../../server/db/prisma";

const authHandler: NextApiHandler = (req, res) =>
  NextAuth(req, res, authOptions);
export default authHandler;

export const authOptions = {
  // Configure one or more authentication providers
  adapter: PrismaAdapter(prisma),
  secret: process.env.NEXTAUTH_SECRET,
  pages: {
    signIn: "/auth/login",
    signOut: "/",
    error: "/auth/error",
    verifyRequest: "/auth/verify-request",
    newUser: "/auth/new-user",
  },
  providers: [
    EmailProvider({
      server: process.env.EMAIL_SERVER,
      from: process.env.EMAIL_FROM,
    }),
    GithubProvider({
      clientId: process.env.GITHUB_CLIENT_ID as string || "",
      clientSecret: process.env.GITHUB_CLIENT_SECRET as string || ""
    }),
    GitlabProvider({
      clientId: process.env.GITLAB_CLIENT_ID as string,
      clientSecret: process.env.GITLAB_CLIENT_SECRET as string,
    }),
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID || "",
      clientSecret: process.env.GOOGLE_CLIENT_SECRET || "",
      authorization: {
        params: {
          prompt: "consent",
          access_type: "offline",
          response_type: "code",
        },
      },
    }),
    // ...add more providers here
  ],
  callbacks: {
    async signIn({ user, account, profile }: { user: any, account: any, profile: any}) {
      console.log("signIn", user, account, profile);
      
      if(!user.email) return false;

      // Check if the user is allowed to sign in
      const invite = await getInvite(user.email);
      // Check if invite exists
      if (!invite) return false;

      // Check if invite is allowed to sign in
      const isAllowedToSignIn = invite.invited;
      if (isAllowedToSignIn) {
        return true;
      } else {
        // Return false to display a default error message
        return false;
        // Or you can return a URL to redirect to:
        // return '/unauthorized'
      }
    },
  },
};

```

Can you help me with that? Google for example works with this approach and also Magic Link, but GitHub and GitLab aren't woking. What goes wrong here?

### How to reproduce

Haven't found a way to reproduce it yet. Just use the example provided above with the specific setings.

### Expected behavior

It should work and login should succeed after going through the signin callback.

**Comment by felixhaeberle** [comment] 2023-02-17 10:53
Turns out with updating on the newest version, the error is now the following:

```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error no access token provided {
  error: TypeError: no access token provided
      at Client.requestResource (/Users/felixhaberle/Desktop/git/backstage/node_modules/openid-client/lib/client.js:1123:13)
      at Client.userinfo (/Users/felixhaberle/Desktop/git/backstage/node_modules/openid-client/lib/client.js:1235:33)
      at Object.request (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/providers/github.js:27:38)
      at oAuthCallback (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/core/lib/oauth/callback.js:141:41)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.callback (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/core/routes/callback.js:52:11)
      at async AuthHandler (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/core/index.js:201:28)
      at async NextAuthHandler (/Users/felixhaberle/Desktop/git/backstage/node_modules/next-auth/next/index.js:24:19)
      at async Object.apiResolver (/Users/felixhaberle/Desktop/git/backstage/node_modules/next/dist/server/api-utils/node.js:366:9) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'github',
  message: 'no access token provided'
}
```

**Comment by AdisonCavani** [comment] 2023-02-18 17:27
Same with AWS Cognito provider: `id_token not present in TokenSet`
and Facebook: `no access token provided`.

**Comment by AdisonCavani** [comment] 2023-02-27 18:22
@ThangHuuVu I created a minimal reproduction example.
You can replate `CognitoProvider` with `GithubProvider`.

https://github.com/AdisonCavani/next-auth-oauth-callback-error-template

**Comment by jacobhq** [comment] 2023-02-28 20:36
I am also experiencing this issue, and since my app needs the github token I can't sign in. Does anyone have any workarounds?

**Comment by minajevs** [comment] 2023-04-22 18:53
It's been two months. I still cannot use GitHub Provider. Are there any news about it?

**Comment by balazsorban44** [comment] 2023-05-19 10:17
Closing as no reproduction was added (https://github.com/nextauthjs/next-auth/issues/6729#issuecomment-1446836794 did not reproduce the issue for me). If you have one, please open a new issue so we can look into this.

**Closed by balazsorban44** 2023-05-19 10:17 UTC
Labels: incomplete, prisma, triage

**Comment by BorisTheTripper** [comment] 2023-09-17 10:51
@balazsorban44 I just opened [a new issue](https://github.com/nextauthjs/next-auth/issues/8615), this should hopefully reproduce.

**Comment by gvigroux** [comment] 2024-05-06 14:41
I can still this error today...

**Comment by cd-Roid** [comment] 2024-07-03 12:00
i had this issue today actually. Check your Client ID and Secret and make sure its right. also check the variable name. If youre reading from an .env file check if the variable name is right. 

To Debug: 
set debug: true in your provider config and check the output for missing variables
