### ISSUE TITLE
getSession in API takes 5-10 seconds in a new project

### ISSUE THREAD

**Issue by davudk** [nextauthjs/next-auth#3301] opened 2021-11-29 21:15 UTC
### Question 💬

The title says it all..

I am trying to use `getSession({ req })` on the server side and it's taking way too long.

Why is it taking so long? I didn't flag it as bug since I might have overlooked something.

### Other info

I've hit this `test` API on the client side (latest Chrome and Safari) using axios and also using Postman (no cookies were passed).

The result is that it regularly takes 4-8 seconds to complete.

**This delay is only present when deployed onto Vercel. When running locally (using `vercel dev`) there is no delay and everything is alright.**

For reference, here is the `test` API on my sample deployment (hit this in Postman with a GET request):
https://gbs-website-aybet3xkf-eagle-logistics.vercel.app/api/test

#### Image for reference:

![image](https://user-images.githubusercontent.com/14043994/143943754-8b54f3ab-0f28-44f2-8398-68a35b6ab6af.png)

The session in the response is expectedly null.

### How to reproduce ☕️

Here are the relevant files:

### `pages/api/auth/[...nextauth].ts`
```ts
import NextAuth, { NextAuthOptions } from 'next-auth';
import Providers from 'next-auth/providers';

const authOptions: NextAuthOptions = {
    providers: [
        Providers.Credentials({
            credentials: {
                username: { label: "Username", type: "text", placeholder: "jsmith" },
                password: { label: "Password", type: "password" }
            },
            async authorize(credentials, req) {
                return null;
            }
        }),
    ]
};

export default NextAuth(authOptions);
```

### `pages/api/test.ts`
```ts
import type { NextApiRequest, NextApiResponse } from 'next';
import { getSession } from 'next-auth/client';

export default async (req: NextApiRequest, res: NextApiResponse) => {
    console.log('session load start:', new Date().toISOString());
    const session = await getSession({ req });
    console.log('session load end:', new Date().toISOString());

    res.status(200).json({ session });
}
```

**Comment by balazsorban44** [comment] 2021-11-29 21:29
Duplicate of #1535

**Closed by balazsorban44** 2021-11-29 21:29 UTC
Labels: question
