### ISSUE TITLE
Discord Provider Callback URL is Incorrect

### ISSUE THREAD

**Issue by conrmahr** [nextauthjs/next-auth#9114] opened 2023-11-10 20:46 UTC
### What is the improvement or update you wish to see?

Documentation and code comments reference incorrect callback URI for the Provider Discord:

❌ Screenshot of Documentation: <img width="994" alt="Discord Callback URL" src="https://github.com/nextauthjs/next-auth/assets/363781/1eba2108-571e-4ede-898d-2eda415a32e2">

❌ Code Comment: https://github.com/nextauthjs/next-auth/blob/87670000917a04b1d22191b4aa07c391fe910c5d/packages/core/src/providers/discord.ts#L94C6-L94C6

✅ **Correct Discord Callback URL:** `https://example.com/auth/callback/discord`
* Same format as GitHub Provider

### Is there any context that might help us understand?

Tested with:
```javascript
        "devDependencies": {
                "@sveltejs/adapter-node": "^1.3.1",
                "@sveltejs/kit": "^1.0.0",
                "svelte": "^4.2.2",
        },
        "type": "module",
        "dependencies": {
                "@auth/core": "^0.18.0",
                "@auth/sveltekit": "^0.3.11"
        }
``` 

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/core/providers/discord

**Comment by dotarjun** [comment] 2023-11-12 17:38
Can I be assigned to this issue? I'd like to work on this

**Comment by LekoArts** [comment] 2023-12-28 11:20
The cause of this is this related issue: https://github.com/nextauthjs/next-auth/issues/6980

**Comment by ndom91** [comment] 2023-12-29 03:19
Sorry for the confusion, the URL in the docs you screenshoted are specific to next.js, as @LekoArts pointed out the paths in SvelteKit are hardcoded to `/auth/..` (see: `next-auth/packages/frameworks-sveltekit/src/lib/index.ts:220`)

**Closed by ndom91** 2023-12-29 03:19 UTC
Labels: documentation, triage
