### ISSUE TITLE
Updating the session after is was created

### ISSUE THREAD

**Issue by dolphineye** [nextauthjs/next-auth#2425] opened 2021-07-26 10:37 UTC
### Question 💬

Hi,

I'm new to NextJS and NextAuth. My past experiences mostly involved PHP or Java a long time ago. My apologies for any dumb questions: things have noticeably changed over the years, so I need to catch up.

We are prototyping a web application where the user authenticates using NextAuth with the Credential provider. Then, the user can decide to explore projects and select one active project to work on.

Naively, I wanted to set my user's active project in a similar way as I would have done in PHP. Pseudo-code example below of what I'm trying to achieve:

```javascript
// Route api/project/switch
const post = async (req, res) => {
    const { query: { identifier } } = req;
    const session = await getSession({ req });
    session.user.project.identifier = identifier;
    await updateSession(session);
};
```

I've been looking into tutorials, documentation, GitHub issues for a day or so, but I've never come up with a clear answer to this what I think is a simple question.

For now, the best solution I've have in mind is to update the database and change the user's active project, then retrieve it via the `jwt` callback. But IMO it does not feel right.

So far, it looks like I'm [not the only one facing this problem](https://github.com/nextauthjs/next-auth/issues/2269). What am I missing? Is that even possible at all?

Thank you for your time!

### How to reproduce ☕️

Not relevant.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment] 2021-07-26 12:46
duplicate of #2269

**Closed by balazsorban44** 2021-07-26 12:46 UTC
Labels: question
