### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by Jonaskop44** [nextauthjs/next-auth#7763] opened 2023-06-09 13:12 UTC
### Question 💬

I wanted to protect my site with middleware. This is my code. 

`import { withAuth } from "next-auth/middleware";
export default withAuth({
  pages: {
    signIn: "/",
  },
});
export const config = {
  matcher: ["/user"],
};
` 

But when I tried it I got this error:
`./node_modules/next-auth/next/middleware.js
Module parse failed: Identifier 'NextResponse' has already been declared (3:6)
| "use strict";
| const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;
> const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;
| var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");
| Object.defineProperty(exports, "__esModule", {` 

I want to use the latest version of NextAuth and NextJs. I hope someone can help me.

### How to reproduce ☕️

.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by bodyaalyas12** [comment] 2023-06-10 12:05
This was answered in https://github.com/nextauthjs/next-auth/issues/7650 . You just need to update to `next@canary`

**Comment by balazsorban44** [comment] 2023-06-13 11:09
It's also out on `next@latest` (13.4.5). Duplicate of #7650

**Closed by balazsorban44** 2023-06-13 11:09 UTC
Labels: question
