### ISSUE TITLE
TypeError: __vite_ssr_import_2__.default is not a function

### ISSUE THREAD

**Issue by KoljaL** [nextauthjs/next-auth#6180] opened 2022-12-25 15:49 UTC
### Environment

Node: 18 used pnpm for install

```JSON
	"devDependencies": {
		"@faker-js/faker": "^7.6.0",
		"@iconify/json": "^2.1.156",
		"@playwright/test": "^1.29.1",
		"@sveltejs/adapter-auto": "^1.0.0",
		"@sveltejs/kit": "^1.0.1",
		"@typescript-eslint/eslint-plugin": "^5.47.0",
		"@typescript-eslint/parser": "^5.47.0",
		"eslint": "^8.30.0",
		"eslint-config-prettier": "^8.5.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"prettier": "^2.8.1",
		"prettier-plugin-svelte": "^2.9.0",
		"prisma": "^4.8.0",
		"svelte": "^3.55.0",
		"svelte-check": "^3.0.1",
		"svelte-preprocess": "^5.0.0",
		"tslib": "^2.4.1",
		"typescript": "^4.9.4",
		"unplugin-icons": "^0.14.15",
		"vite": "^4.0.3",
		"vitest": "^0.26.2"
	},
	"dependencies": {
		"@auth/core": "^0.2.3",
		"@auth/sveltekit": "^0.1.10",
		"@prisma/client": "^4.8.0"
	}
```

### Reproduction URL

https://github.com/KoljaL/Svoard

### Describe the issue

After reinstall all node_modules i get this error

```javascript
TypeError: __vite_ssr_import_2__.default is not a function
    at async instantiateModule (file:///Users/xxx/Code/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:52198:9)

```

`hooks.server.ts`

```javascript

import SvelteKitAuth from '@auth/sveltekit'
import { PrismaAdapter } from '$lib/server/PrismaAdapter'
import { PrismaClient } from '@prisma/client'
import type { Adapter, AdapterAccount } from '@auth/core/adapters'
...

// line 42
adapter: PrismaAdapter(PrismaClient) as Adapter<boolean>,
```
This seems similar, but the solution does not solve my issue:
https://github.com/nextauthjs/next-auth/issues/6106

### How to reproduce

Install the package.json and use the prisma adapter in the hooks.server.ts

### Expected behavior

No TypeError.

**Comment by OrJDev** [comment] 2022-12-25 15:56
This is very different from my issue, 
the error says `prismaClient` is not defined, you imported `PrismaClient` which is the type/class of your prisma client and not the actual client. Make sure you import it from the correct file

```ts
// server/prisma.ts
import { PrismaClient } from "@prisma/client");
export const prismaClient = new PrismaClient();
```

And then it could be used like

```ts
import { prismaClient } from "../server/prisma";
adapter: PrismaAdapter(prismaClient) as Adapter<boolean>
```

**Comment by KoljaL** [comment] 2022-12-25 16:02
@OrJDev thanks for the quick reply.
But it was to quick, i had a typo in my code, but after correct it, there is the "right" error:

`TypeError: __vite_ssr_import_2__.default is not a function`

I import the `PrismaClient` inside the `hooks.server.ts` and initialize it

**Comment by balazsorban44** [comment] 2022-12-26 00:12
Duplicate of https://github.com/nextauthjs/next-auth/issues/6170#issuecomment-1364543906

**Closed by balazsorban44** 2022-12-26 00:12 UTC
Labels: triage

**Comment by hugoblanc** [comment] 2023-07-14 15:28
In my case it was the supertest import
`import * as request from 'supertest';` => `import supertest from 'supertest';`
