### ISSUE TITLE
next-auth requires typeorm and its dependencies on SSR pages when deploying to AWS Amplify/serverless

### ISSUE THREAD

**Issue by Kakise** [nextauthjs/next-auth#2500] opened 2021-08-08 09:37 UTC
### Description 🐜

While deploying to Vercel works perfectly fine, when using next-auth, without using a DB (Credentials provider), typeorm and its adapters are somehow required by webpack in every SSR pages. The build then fails with a webpack error: `Module not found: module "typeorm" not found in ...`

The bug persists even after installing every single database deps possible because server side packages can't be used in SSR pages.

### Is this a bug in your own project?

No

### How to reproduce ☕️

- Fork next-auth starter kit
- Setup AWS Amplify to use your GitHub repo

### Environment 🖥

```
  System:
    OS: macOS 12.0
    CPU: (8) arm64 Apple M1
    Memory: 152.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.1 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.20.3 - /opt/homebrew/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 89.0.2
    Safari: 15.0
  npmPackages:
    next: ^11.0.1 => 11.0.1 
    next-auth: ^3.27.3 => 3.27.3 
    react: ^17.0.2 => 17.0.2 
```

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment] 2021-08-08 09:39
duplicate of #2439

**Closed by balazsorban44** 2021-08-08 09:39 UTC
Labels: bug

**Comment by balazsorban44** [comment] 2021-08-08 09:40
v4 (hopefully coming out soon) won't install typeorm implicitly, so this problem will go away for users who don't use databases
