### ISSUE TITLE
(node:6560) UnhandledPromiseRejectionWarning: TypeError: (0 , _preactRenderToString.default) is not a function

### ISSUE THREAD

**Issue by weltonclima** [nextauthjs/next-auth#1474] opened 2021-03-08 01:22 UTC
Good evening! I'm getting this error, I've tried everything and even used another notebook but the error persists.

(node:6560) UnhandledPromiseRejectionWarning: TypeError: (0 , _preactRenderToString.default) is not a function
    at signin (C:\www\next auth\netx-auth\node_modules\next-auth\dist\server\pages\signin.js:46:44)
    at Object.signin (C:\www\next auth\netx-auth\node_modules\next-auth\dist\server\pages\index.js:48:35)
    at C:\www\next auth\netx-auth\node_modules\next-auth\dist\server\index.js:188:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\www\next auth\netx-auth\node_modules\next-auth\dist\server\index.js:52:103)
    at _next (C:\www\next auth\netx-auth\node_modules\next-auth\dist\server\index.js:54:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:6560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 48)

**Comment by JPGallegos1** [comment] 2021-03-08 02:37
Same here. I thought it was a configuration mistake by me but after following officials' docs and some youtube tutorials, I came here to report it.

**Comment by JacksonMalloy** [comment] 2021-03-08 04:11
I also am getting this bug, been trying to debug it for hours! 
Glad others are stuck and not just me.
The request hangs whenever I try to log in. 

System information:

Node version: v14.15.4 (Haven't tried other versions of node)
WSL2 (Linux)

Package Versions: 
"next": "^10.0.8",
"next-auth": "^3.11.1"

I wonder if it's system related. 
Here are some steps I took to help repro

1. Set up blank nextjs project with https://next-auth.js.org/getting-started/example (I'm using typescript)
2. Setup Login component
```
const Login = () => {
  return (
      <button
        onClick={() => {
          signIn()
        }}
      >
        Log In
      </button>
  )
}
```
3. Whenever I try to login, I receive this error in the terminal: 

```
(node:7881) UnhandledPromiseRejectionWarning: TypeError: (0 , _preactRenderToString.default) is not a function
    at signin (/home/devjacks/projects/partypay.app/node_modules/next-auth/dist/server/pages/signin.js:46:44)
    at Object.signin (/home/devjacks/projects/partypay.app/node_modules/next-auth/dist/server/pages/index.js:48:35)
    at /home/devjacks/projects/partypay.app/node_modules/next-auth/dist/server/index.js:188:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/devjacks/projects/partypay.app/node_modules/next-auth/dist/server/index.js:52:103)
    at _next (/home/devjacks/projects/partypay.app/node_modules/next-auth/dist/server/index.js:54:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7881) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
(node:7881) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any recommendations, help would be greatly appreciated!
Happy to answer any further questions to help debug

**Comment by condinoaljoseph** [comment] 2021-03-08 05:54
I also get this error. Its just suddenly appear.

**Comment by Djiit** [comment] 2021-03-08 06:32
Looks like a duplicate of #1470

**Comment by balazsorban44** [comment] 2021-03-08 08:42
Duplicate of #1470

**Closed** 2021-03-08 08:42 UTC
Labels: bug, duplicate

**Comment by balazsorban44** [comment] 2021-03-08 08:45
Anyone discovering this, update your packages and make sure that you use at least `preact-render-to-string@5.1.14`! (check your lock files/node_modules) They recently introduced a bug by accident which has been patched in 5.1.14.

**Comment by balazsorban44** [comment] 2021-03-08 09:57
Also installing the latest `next-auth` shouldn't be able to reproduce this issue anymore.

**Comment by JPGallegos1** [comment] 2021-03-08 14:10
Thank you, guys. After update next-auth to version 3.11.2, it didn't happen anymore. Everything is working fine.

**Comment by weltonclima** [comment] 2021-03-08 16:44
With the update is working, thank you!
