### ISSUE TITLE
Build error after updating @core/auth to 0.6.0 when using SvelteKitAuthConfig

### ISSUE THREAD

**Issue by olafurw** [nextauthjs/next-auth#7311] opened 2023-04-19 08:55 UTC
### Environment

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 7.01 GB / 31.73 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.48)
    Internet Explorer: 11.0.19041.1566

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

After updating to the 0.6.0 version I get build errors that don't seem to be caused by my code. Was working fine in the previous version.

Seems to be caused by this or similar changes.

https://github.com/nextauthjs/next-auth/pull/7228/files#diff-4c2458380e50c967c70d7afe819dc7412180f9f817043f27441de3498e4d0479R124

`(value: SvelteKitAuthConfig): Promise<SvelteKitAuthConfig>', gave the following error. `

In a code example like this.

```
const svelteAuth = SvelteKitAuth((event) =>
    Promise.resolve({
        //debug: dev,
        trustHost: true,
        secret: AUTH0_AUTH_SECRET,
        pages: {
            error: '/login',
            signIn: '/login',
            signOut: '/logout'
        },
        providers: [
            Auth0({
                clientId: AUTH0_CLIENT_ID,
                clientSecret: AUTH0_CLIENT_SECRET,
                issuer: AUTH0_HOSTNAME
            })
        ] as Provider[],
        callbacks: {
            async signIn({ user }) {
              // ...
            },
            redirect({ baseUrl }) {
              // ...
            },
            session({ session }) {
              // ...
            }
        }
    })
) satisfies Handle;
```

```
Type 'import("c:/work/xx/platform/node_modules/@auth/core/types").Profile' is not assignable to type 'import("c:/work/xx/platform/node_modules/@auth/sveltekit/node_modules/@auth/core/types").Profile'.

Types of property 'sub' are incompatible.  
Type 'string | null | undefined' is not assignable to type 'string | undefined'.  
Type 'null' is not assignable to type 'string | undefined'.  
Overload 2 of 3, '(value: SvelteKitAuthConfig | PromiseLike<SvelteKitAuthConfig>): Promise<SvelteKitAuthConfig>', gave the following error.  
Type
'import("c:/work/xx/platform/node_modules/@auth/core/providers/index").Provider[]'
is not assignable to type
'import("c:/work/xx/platform/node_modules/@auth/sveltekit/node_modules/@auth/core/providers/index").Provider[]'.
```

### How to reproduce

Update the @auth/core to 0.6.0 in a project using the SvelteKitAuth

### Expected behavior

No build failure.

**Comment by balazsorban44** [comment] 2023-04-20 08:51
Duplicate of #6226.

A workaround for now: https://github.com/nextauthjs/next-auth/issues/6226#issuecomment-1368277163

Since `@auth/sveltekit` depends on `@auth/core`, ideally it should also be released with the updated dependency.

**Closed by balazsorban44** 2023-04-20 08:51 UTC
Labels: triage
