### ISSUE TITLE
Unexpected token d in JSON at position 0 in Vercel Production Environment

### ISSUE THREAD

**Issue by wxmann** [nextauthjs/next-auth#6688] opened 2023-02-11 01:35 UTC
### Environment

```
System:
  OS: macOS 12.3
  CPU: (10) arm64 Apple M1 Pro
  Memory: 63.27 MB / 16.00 GB
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 18.12.1 - /usr/local/bin/node
  npm: 8.19.2 - /usr/local/bin/npm
Browsers:
  Chrome: 107.0.5304.121
  Safari: 15.4
```

### Reproduction URL

Private repo

### Describe the issue

When I try to log into my Nextjs app deployed on Vercel, I get redirected to the error page `.../api/auth/signin?error=OAuthCallback`

Stack trace:
```
2023-02-11T01:23:14.775Z	1e150ed2-eefe-42fe-af99-e6a6cfab3ddf	ERROR	[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error Unexpected token d in JSON at position 0 {
  error: SyntaxError: Unexpected token d in JSON at position 0
      at JSON.parse (<anonymous>)
      at IncomingMessage.get (/var/task/node_modules/openid-client/lib/helpers/request.js:153:30)
      at processResponse (/var/task/node_modules/openid-client/lib/helpers/process_response.js:55:25)
      at Issuer.discover (/var/task/node_modules/openid-client/lib/issuer.js:152:20)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async openidClient (/var/task/node_modules/next-auth/core/lib/oauth/client.js:16:14)
      at async oAuthCallback (/var/task/node_modules/next-auth/core/lib/oauth/callback.js:85:20)
      at async Object.callback (/var/task/node_modules/next-auth/core/routes/callback.js:52:11)
      at async AuthHandler (/var/task/node_modules/next-auth/core/index.js:201:28)
      at async NextAuthHandler (/var/task/node_modules/next-auth/next/index.js:24:19) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'google',
  message: 'Unexpected token d in JSON at position 0'
}
```

Versions on `package.json`:
```
{
  ...
  "next": "13.1.6",
  "next-auth": "^4.19.2",
  ...
}
```
The `openid-client` version in my `node_modules` is 5.4.0.

The auth options in my app:

```
export const authOptions = {
  adapter: PrismaAdapter(prisma),
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    })
  ],
  callbacks: {
    async session({ session, token, user }) {
      session.user.id = user.id
      return session
    },
  }
}
```

```
import NextAuth from "next-auth"
import { authOptions } from "../../../lib/auth"

export default NextAuth(authOptions)
```

Confirmed the env variables are all set correctly in Vercel
<img width="908" alt="image" src="https://user-images.githubusercontent.com/7868877/218231537-282de7cc-bf66-44ae-8c2d-dd34a0da3ea3.png">

### How to reproduce

Try to login to my app, redirects me into the Error page

**This does not occur on my local environment, only on Vercel deployed environment.**

### Expected behavior

Try to login to my app, does not redirect me to the Error page

**Comment by rapz** [comment] 2023-02-11 01:36
Bunch of people with the same error probably something on vercel

**Comment by yutakobayashidev** [comment] 2023-02-11 01:39
I have the exact same Issue.

**Comment by yutakobayashidev** [comment] 2023-02-11 01:40
Related Links:
https://stackoverflow.com/questions/75417320/vercel-google-oauth-json-error-when-trying-to-sign-in-but-it-works-in-localhost

**Comment by zlwaterfield** [comment] 2023-02-11 01:40
Yep, seems to be a larger issue with Vercel. Longer thread here: https://github.com/nextauthjs/next-auth/issues/6685

**Comment by mintavenger** [comment] 2023-02-11 01:44
It started happening at 3:49 pm PST for us. Almost two hours ago. Twitter seems to work though.

**Comment by felipap** [comment] 2023-02-11 01:51
Reverting to a previous state from days ago seems to fix the issue. Does that suggest this could be fixed by changing library versions in package.json?

**Comment by mintavenger** [comment] 2023-02-11 01:53
@felipap what version did you revert to? We were on version `"next-auth": "^4.5.0",` and had the issues. We also tried updating to latest `"next-auth": "^4.14.0",`. I don't think it's an issue with the client library but more of how Vercel is handling the callback.

It works fine running locally on our laptops.

**Comment by wxmann** [comment] 2023-02-11 01:53
> Reverting to a previous state from days ago seems to fix the issue. Does that suggest this could be fixed by changing library versions in package.json?
> 
> (This is causing quite the damage for us because we needed to ship an unrelated bug fix to prod but can't.)

I redeployed an old deployment and originally encountered this issue with an older version of `next-auth` (4.18.8)

Rolling back to an older deployment (rather than redeploying) seems to be fine however.

**Comment by felipap** [comment] 2023-02-11 01:54
@mintavenger I reverted to an older deploy but with the same `next-auth` version, which tells me it's unrelated to the version itself. :/

**Comment by zlwaterfield** [comment] 2023-02-11 01:56
A rollback to a deploy from 8 hrs ago worked for me. Thanks @felipap!

**Comment by yutakobayashidev** [comment] 2023-02-11 01:58
https://github.com/vercel/community/discussions/1493

**Comment by mintavenger** [comment] 2023-02-11 02:06
Oooh. It must be something they are packaging in the new code. Thanks, @felipap. It worked for us by using rollback vs. redeploy. 
![image](https://user-images.githubusercontent.com/113479684/218233472-112359ff-8bbe-4769-9ede-d8d3d82b94c3.png)

**Comment by ArjanJ** [comment] 2023-02-11 02:41
Thought it was just me, this has been driving me insane for the last few hours.

**Comment by zlwaterfield** [comment] 2023-02-11 02:50
Vercel is aware and looking into it: https://twitter.com/leeerob/status/1624237510900563971?s=20&t=fNKQ1tBh_RKQhxmGSvMhAg

**Comment by based64-eth** [comment] 2023-02-11 02:51
Same thing here. Started breaking randomly in production without any code changes.

**Comment by swarnava** [comment] 2023-02-11 03:20
Hi everyone,

My name is Swarnava and I work for Vercel Customer Success team. We are investigating this issue now.

**Comment by engelmav** [comment] 2023-02-11 04:25
I was wondering why I found zero signs of this in my hours of google searches. It hadn't been indexed yet!

**Comment by swarnava** [comment] 2023-02-11 04:47
Hi,

We reverted a changes that we believe should fix the problem. If you are still facing this issue, please create a ticket using: vercel.com/help

**Comment by engelmav** [comment] 2023-02-11 05:03
> Hi,
> 
> We reverted a changes that we believe should fix the problem. Please redeploy your app, and let us know If you are still facing this issue: https://vercel.com/help

Confirmed it’s working now. Thank you!

**Closed** 2023-02-11 05:07 UTC
Labels: upstream

**Comment by oeduardoal** [comment] 2023-02-15 20:14
Hey guys -- Seems like the problem is back again...

@swarnava

**Comment by Masihhedayati** [comment] 2023-03-01 08:06
I still encounter the same issue!

**Comment by swarnava** [comment] 2023-03-01 15:42
Please create a new issue.

**Comment by djmango** [comment] 2023-05-07 12:17
Same here, no code changes

**Comment by Luckylo-com** [comment] 2023-05-25 21:31
i have no oauth or users, but with my project no deploed (nextjs, prisma, mongodb)
i have errors in pages:
SyntaxError: Unexpected token < in JSON at position 0

**Comment by Bharat0509** [comment] 2023-06-28 08:03
This error is occurred due to the fact that while deployment vercel link at which you are makings request provide html response and that's why after fetch you cannot do res.Json() . To resolve this you can check res.Headers['content-type'] is text/html than you just return null. And you're good to go.....

**Comment by per-hakansson** [comment] 2023-12-21 16:28
If you host your own API you'll need to deploy those first before deploying any pages that makes a fetch from that API.
