### ISSUE TITLE
Client Credentials Basic Auth Option

### ISSUE THREAD

**Issue by mod-flux** [nextauthjs/next-auth#1604] opened 2021-03-28 19:20 UTC
**Summary of proposed feature**
Provide a boolean option to switch providing an OAuth clients credentials via Basic Auth as opposed to the default and only supported the option of via a request-body during the `POST`

**Purpose of proposed feature**
The most up-to-date IETF OAuth 2.0 Auth Framework spec has stated that providing the client credentials via the request-body of the `POST` is explicitly not recmmended and only to be used in situations where clients are unable to directly utilize the HTTP Basic authentication scheme, which doesn't cover this library's primary use case. Here is the snippet in the RFC:

> Including the client credentials in the request-body using the two
parameters is NOT RECOMMENDED and SHOULD be limited to clients unable
to directly utilize the HTTP Basic authentication scheme (or other
password-based HTTP authentication schemes). The parameters can only
be transmitted in the request-body and MUST NOT be included in the
request URI.

Reference: https://tools.ietf.org/html/rfc6749#section-2.3.1

At present Next-auth defaults to and provides no official support for any other method than providing the client secret in the `POST` body of requests. Not having the ability to choose between Basic Auth and `POST` by easily stripping out the `client_id` and `client_secret` from the request body and provide it via Basic Auth is a blocker for any strict OAuth provider that's following the latest OAuth specifications and doesn't marry with the support available with NextAuth.

**Detail about proposed feature**
A boolean in the `options` for a provider that switches the default behaviour of providing the `client_id` and `client_secret` to the token endpoint if the OAuth service via the `POST` body to providing them as a base64 encoded string as a Basic auth header instead.

**Potential problems**
Describe any potential problems or potential limitations or caveats that might apply to the proposed solution.

**Describe any alternatives you've considered**
I've currently patched the `next-auth` package for our client and simply deleted the `client_secret` from the `POST` request before it gets stringified. Furthermore, I've used the `headers` option provided by next-auth to add a `Basic Auth` header which does the trick. However, it would be good for official support for this as I've noted something similar has been directly hardcoded into the library for providers such as `twitch` and would benefit being replaced with a more general approach.

**Additional context**
Related open issue: https://github.com/nextauthjs/next-auth/issues/950

I believe I have some experience of this and would be able to assist with a PR for this work, should that be of benefit.

**Comment by balazsorban44** [comment] 2021-03-28 20:37
This one feels like a duplicate of #950. Could we close it and continue there?

**Comment by mod-flux** [comment] 2021-03-28 20:39
Happy to @balazsorban44, didn't know if a feature proposal format was a good way of presenting it but if you're happy with the bug issue then feel free to close.

**Comment by balazsorban44** [comment] 2021-03-28 20:41
I think your description is very useful, so feel free to add it to #950 (although I can see you already did it partially)

**Closed** 2021-03-28 20:41 UTC
Labels: duplicate, enhancement
