### ISSUE TITLE
Getting signed in as the previously logged in user when using google/facebook/apple providers

### ISSUE THREAD

**Issue by vandanasriram** [nextauthjs/next-auth#2659] opened 2021-09-04 15:33 UTC
### Description 🐜

We have a next.js app with a Feathers.js backend that uses next-auth for logging in.  

Expected behaviour:
We have a react native app running with a feathers backend(uses web sockets for server side calls and not HTTP). We use credentials, google, facebook and apple login in the mobile app. The way login is set up is that we only allow users to sign in and not sign up. We make use of the feathers backend to verify that the user is already in the database. If he's not present an appropriate error is thrown and he is not allowed to sign up. We intend to do the same with the next-js web app. In the [...nextauth].js page inside the signin call back we add the feathers authentication code to verify if the user is present in the db. If not present an error should be thrown and the app should remain in the sign in page without a session being created. 
Actual Behaviour:
1. user 1 logs in with any provider (credentials/apple/facebook/google) and remains using the app
2. A new user(user 2) logs in with google/facebook/apple with an email which at present is not in the database
Instead of throwing the error (that the email is not present in the database) user 2 gets logged in as user 1 with the email id he used being added to user 1's record in the database

The steps to reproduce is given below. Although we use the same serverside calls for authentication in both the mobile app(react native+feathers) and in the web app(next.js + feathers) the bug only appears in the web app
### Is this a bug in your own project?

Yes

### How to reproduce ☕️

1. Load the web page as an non authenticated user----(user 1)
2. Press Login, taking you to the login page
3. Sign in with any provider (google/facebook/apple) as user 1 (an already created user)
4. While still logged in open another private window and open the web app there as an unauthenticated user
5. Go to login in page 
6. Try logging in with google/facebook/apple providers as a user that doesn’t have an account already in the backend (which we’ve tried to forbid)
7. The app gets logged in as user 1 (who is still in session) and,
8. The new facebook/google/apple email is added to user 1’s account in the database

### Screenshots / Logs 📽
[...nextauth].js code:
```js
import NextAuth from 'next-auth'
import Providers from 'next-auth/providers'
import client from '../client'


export default NextAuth({
    providers: [
        Providers.Apple({
            //
            clientId: "xxxxxxx",
            clientSecret:{
                teamId:"xxxxxxxx",
                keyId:"xxxxxxxxx"
            }
        }),
        Providers.Facebook({
            
            clientId: "xxxxxxxxxxxxx",
            clientSecret: "xxxxxxxxxxx",
        }

        ),
        Providers.Google({
            name: 'Google',

            
            clientId: "xxxxxxxx",
            clientSecret: "xxxxxxxxxxx",

        }),
        Providers.Credentials({
            name: 'Credentials',
            credentials: {
                username: { label: "Username", type: "text", placeholder: "username" },
                password: { label: "Password", type: "password", placeholder: "password" },
            },


            async authorize(credentials, req) {
              

                const request = {
                    strategy: "local",
                    uname: credentials.username,
                    pword: credentials.password,
                    extraProps: { apiVersion: "4" }
                }

                const userDetails = await client.authenticate(request);

                // If no error and we have user data, return it
                if (userDetails) {
                    return fullDetails
                }
                else {
                    // Return null if user data could not be retrieved
                    return null
                }
            }
        }),



    ],

   


   



    pages: {

        error: '/signin'
    },


    callbacks: {

        async signIn(user, account, profile) {

            if (account.provider === 'google') {
                //     const {accessToken} =await client.authenticate({
                //         strategy: "google",
                //        generatedToken: account.idToken,
                //        type: "web-app"
                //    })
                const temp = await client.authenticate({
                    strategy: "google",
                    generatedToken: account.idToken,
                    type: "web-app"
                })

                const { accessToken } = temp
                user.user = temp.user
                user.provider = "google"
                user.accessToken = accessToken

                console.log(temp.user, "user  temp")
                if (user.accessToken) {
                    return true
                }

            }
            else if (account.provider === "credentials") {

                return true;
            }
            else if (account.provider === 'facebook') {
                const temp = await client.authenticate({
                    strategy: "facebook",
                    generatedToken: account.accessToken,
                    type: "web-app"
                })
                const { accessToken } = temp
                user.user = temp.user
                user.provider = "facebook"
                user.accessToken = accessToken

                if (user.accessToken) {
                    return true
                }

            }
           
        },
        async jwt(token, user, account, profile, isNewUser) {
            if (user) {
                token = user?.provider ? user : { user }.user;
            }
     
            return token
        },


      

        async session(session, token) {
            session.accessToken = token.accessToken
            session.user = token.user
            return session
        }

    },
   

  
    theme: 'dark',

   
    debug: true,
   
})
```

When the user is redirected to home page, we run the code to add the jwt returned from the session object to be added to the local storage to enable serverside calls (using feathers socket connection) 
_No response_

### Environment 🖥

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
    Memory: 291.43 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 6.14.14 - ~/Nikhil/YUSER/yuser-network-web/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 92.0.4515.159
    Safari: 14.0
  npmPackages:
    next: ^11.0.1 => 11.0.1 
    next-auth: ^3.27.3 => 3.27.3 
    react: ^17.0.2 => 17.0.2 
    feathers server - version: 4.5.11
    mongoDB 

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment] 2021-09-04 18:26
do you have a reproduction? I'm guessing the problem will be that the Credentials provider is inherently different than the others in that it won't save anything to the database. it is  generally not advised to roll your own password solution, nand so we don't allow saving these kinds of profiles being created in the database.

**Comment by pribeh** [comment] 2021-09-05 17:05
Thanks for getting back to us quick @balazsorban44 . @vandanasriram has updated the issue with code we currently are using in the project at hand. We've also made a few changes to the notes and steps to reproduce. We just checked and it looks like it doesn't matter if we remove credentials provider. The issue happens with any provider.

To be clear, we're currently attempting to use nextauth to authenticate existing users and not to create new users. It also appears that there are two aspects to this issue:

1. the user (2) who attempts to login with a provider not associated with an account logins as an already logged-in user (1)
2. when this happens, user 1's email is overwritten by the email provided by user 2

We are using nextjs/nextauth to connect to a backend already in use for a mobile application. The backend runs feathersjs which users websockets, not HTTPs. I wanted to highlight that we are doing something extra to allow feathers to work properly that may be a factor in this issue which @vandanasriram added to the above description:

"When the user is redirected to home page, we run additional code to add the jwt returned from the session object to be added to the local storage to enable serverside calls (using feathers socket connection)"

Let us know what you think. Thanks

**Comment by balazsorban44** [comment] 2021-09-05 17:21
Without looking much into it yet, I see at least one problem. The signIn callback is not meant to mutate the user object, and might stop working in the future. That method is supposed to be used to determine if the user is allowed to log in or not.

**Comment by pribeh** [comment] 2021-09-06 00:02
@balazsorban44 thanks. How should we save the jwt token? As a cookie?

**Comment by balazsorban44** [comment] 2021-09-06 07:21
`next-auth` already stores session data in a fairly secure way (in a JWT in a HttpOnly, secure cookie), which optionally can also be encrypted. Or if you have a database, we also provide the possibility to persist sessions in that database.

I'll have to add that I don't have much experience with websockets.

**Comment by balazsorban44** [comment] 2021-09-07 17:00
This has been discussed through a call, and the most probable explanation for the issue mentioned in the title was a caching misconfiguration on the host environment, so not an identifiable issue in `next-auth`. I had a similar issue a while back: https://github.com/vercel/next.js/discussions/14136

Some services like Azure CDN or Google will set a default cache time if they don't receive a `Cache-Control` header from the origin server. In my opinion, it shouldn't be the case, but I cannot fight both Azure and Google... :shrug: 

(I tried: https://docs.microsoft.com/en-us/answers/questions/316956/azure-cdn-should-respect-origin-cache-control.html)

I am happy to follow up on this if further issues arise, but I'll close this for now.

**Closed by balazsorban44** 2021-09-07 17:00 UTC
Labels: bug, incomplete

**Comment by mehthabt** [comment] 2023-01-21 09:50
even im facing the same for facebook login, what if the user want to sigin with another account with facebook. once we login with an aaccount, the same session is returned everytime
