### ISSUE TITLE
Unable to stop redirect with email signIn

### ISSUE THREAD

**Issue by alex-cory** [nextauthjs/next-auth#1546] opened 2021-03-18 16:45 UTC
**Describe the bug**
In [the docs](https://next-auth.js.org/getting-started/client#using-the-redirect-false-option) it says `signIn('email', { redirect: false })` should keep you on the same page, but it doesn't. It still redirects to `/api/auth/verify-request?provider=email&type=email`. I upgraded to `v3.13.0` to see if that helped but it did not.

**Steps to reproduce**
I have it set up like this
```js
signIn('email', { redirect: false })`
```

Include a link to public repository which can be used to reproduce the behaviour.

**Expected behavior**
I expect it to not redirect to `/api/auth/verify-request?provider=email&type=email`

**Screenshots or error logs**
Here are the logs from the server
```
[next-auth][debug][typeorm_get_user_by_email] alexcoryregister@gmail.com
[next-auth][debug][typeorm_create_verification_request] alexcoryregister@gmail.com
REDIRECT http://a.local:3000/?forYou=true <- this was called in the redirect callback
```

![Mar-18-2021 12-39-19](https://user-images.githubusercontent.com/5455859/111663231-d6fecb80-87cd-11eb-84df-f6dce351c5cc.gif)

**Additional context**
Seems like issue https://github.com/nextauthjs/next-auth/issues/1542 has the same problem he's just reporting something different. Notice he has `redirect: false` but it's still redirecting.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by bduff9** [comment] 2021-03-18 23:37
@alex-cory Just saw this. FYI, my page is not redirecting.  The redirect: false is working as expected.  What I am seeing is after successful sign in (i.e. the page I enter the email on stays on that page, but I click on the email link I get to verify), the callbackUrl value is ignored and it always go to the home page.  But the initial behavior when calling sign in does work as expected.  Unsure why you are seeing it change pages like you are, but that is the opposite of what I am seeing at that stage.

**Comment by identiq** [comment] 2021-12-09 01:08
https://github.com/nextauthjs/next-auth/issues/3226

**Comment by canastro** [comment] 2023-02-09 10:41
I'm having the same issue with @auth/sveltekit. Is there any workaround for sveltekit projects?

**Comment by ThangHuuVu** [comment] 2023-03-25 08:18
I can't reproduce this issue with v4, so I'm closing it. If anyone is still having the issue, feel free to open another one with a reproduction 🙏

**Closed by ThangHuuVu** 2023-03-25 08:18 UTC
Labels: bug
