### ISSUE TITLE
CredentialsProvider doesnt seem to work on v4 (beta 7)

### ISSUE THREAD

**Issue by Pruxis** [nextauthjs/next-auth#3289] opened 2021-11-27 08:51 UTC
### Question 💬

I have tried both the default sign-in page that is generated automatically or using the signIn function.

Example usage:
``` typescript
signIn('credentials', {
  redirect: false, // tried both with and without redirect.
  email: elements.email.value || 'test@test.com',
  password: elements.password.value || 'test',
});
```

In all cases the following is return from the signIn callback:
```
{
  user: {
    id: 1,
    name: 'J Smith',
    email: 'jsmith@example.com',
    redirect: 'false',
    password: 'fdsfds',
    csrfToken: '92119b7fbbf176b8de47f18ccce385a5caf7c8887bc60d0d793a92f99e55ef1e',
    callbackUrl: 'http://localhost:3000/login',
    json: 'true'
  },
  account: {
    providerAccountId: 1,
    type: 'credentials',
    provider: 'credentials'
  },
  credentials: [Object: null prototype] {
    redirect: 'false',
    email: 'jsmith@example.com',
    password: 'fdsfds',
    csrfToken: '92119b7fbbf176b8de47f18ccce385a5caf7c8887bc60d0d793a92f99e55ef1e',
    callbackUrl: 'http://localhost:3000/login',
    json: 'true'
  }
}
```

### How to reproduce ☕️

Provider configuration:
``` typescript
CredentialsProvider({
  name: 'EmailPassword',
  authorize: async (credentials, f) => {
    // const [user] = req.models.user.find({});
    // return user;
    const user = { id: 1, name: 'J Smith', email: 'jsmith@example.com', ...credentials };
    return user;
  },
  type: 'credentials',
  credentials: {
    email: { label: 'Email', type: 'text', placeholder: 'test@test.com' },
    password: { label: 'Password', type: 'password' },
  },
}),```



### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by Pruxis** [comment] 2021-11-27 08:58
In all of the cases the event signIn is also being called.

```
   events: {
      signIn: message => console.log('Event:: ', message),
    },
 ```
 
 So the cookie will be set accordingly based on https://github.com/nextauthjs/next-auth/blob/main/src/server/routes/callback.js#L414
 
I don't really see why it's not functioning as expected, upon using useSession in the frontend it always indicates as status unauthenticated.

**Comment by balazsorban44** [comment] 2021-11-27 10:51
What's the problem? Is this a duplicate ofn#3216?

**Closed** 2021-11-27 10:53 UTC
Labels: question
