### ISSUE TITLE
Unexpected token 'export' in @next-auth/prisma-adapter

### ISSUE THREAD

**Issue by SooditK** [nextauthjs/next-auth#4207] opened 2022-03-17 09:38 UTC
### Adapter type

@next-auth/prisma-adapter

### Environment

```
System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 1.61 GB / 7.21 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.0 - /var/lib/snapd/snap/bin/node
    Yarn: 1.22.17 - /var/lib/snapd/snap/bin/yarn
    npm: 8.3.1 - /var/lib/snapd/snap/bin/npm
  Browsers:
    Firefox: 98.0
  npmPackages:
    next: 12.1.0 => 12.1.0 
    next-auth: ^4.2.1 => 4.2.1 
    react: 17.0.2 => 17.0.2 


  npmPackages:
    @next-auth/prisma-adapter: ^1.0.1 => 1.0.1
```
![Firefox_Screenshot_2022-03-17T09-08-23 719Z](https://user-images.githubusercontent.com/50576944/158777120-02283cc4-54d8-43fc-b6d8-bda6328c8202.png)

![Firefox_Screenshot_2022-03-17T09-14-04 752Z](https://user-images.githubusercontent.com/50576944/158777155-1d29409d-eae8-4c0b-8b1b-966a700f9678.png)

### Reproduction URL

https://github.com/SooditK/porquemaria

### Describe the issue

```
2022-03-17T09:01:40.124Z	c5e69049-6219-4c67-b8f5-e8c0177831d3	ERROR	/var/task/node_modules/@next-auth/prisma-adapter/dist/index.js:1
export function PrismaAdapter(p) {
^^^^^^
SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16) 
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.123 (/var/task/.next/server/pages/api/auth/[...nextauth].js:32:40)
    at __webpack_require__ (/var/task/.next/server/webpack-api-runtime.js:25:42)
    at __webpack_exec__ (/var/task/.next/server/pages/api/auth/[...nextauth].js:86:39)
RequestId: c5e69049-6219-4c67-b8f5-e8c0177831d3 Error: Runtime exited with error: exit status 1Runtime.ExitError
```
Apologies, for any Indentation Issues

After Hosting, an Example Auth Application (using Next-Auth, Prisma Adapter, Vercel), This is the error that I'm getting in the Function Logs in Vercel (500 Internal Server Error, at the Frontend Side)

### How to reproduce

In my Local Machine, It is running fine, as Expected. So, to reproduce, One might have to try to host it on Vercel.

Link: 
https://github.com/SooditK/porquemaria.git

The .env.example file is also added in the repository, for reference, as well.

### Expected behavior

I'm using useSession() hook, and checking if the user is authenticated, He/She will see his/her Profile Picture in a Small Card, with their Name, Email Address, and a Signout Button

If the user is not authenticated, User should see 3 buttons, Sign In with Discord, Sign In with Google, Sign in with Email, respectively.

**Comment by balazsorban44** [comment] 2022-03-17 12:45
duplicate of #4198

**Closed by balazsorban44** 2022-03-17 12:45 UTC
Labels: adapters, prisma, triage
