### ISSUE TITLE
next-auth/react seems to be broken in v4

### ISSUE THREAD

**Issue by cyrus-za** [nextauthjs/next-auth#2212] opened 2021-06-18 10:27 UTC
I get the following error when upgrading to v4.0.0-next.15
```sh
TypeError: can't access property "useSession", next_auth_react__WEBPACK_IMPORTED_MODULE_0__ is undefined
```

I checked and the code seems to be there in dist/client/react but for some reason at runtime it thinks it is not there. Maybe webpack excludes it for some reason?

EDIT: After checking the server logs, it seems like it might be related to reast-ssr-prepass but I am not sure. prepass might just get the error when trying to access next-auth

```sh
event - compiled successfully
TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableRest (webpack-internal:///../../node_modules/.pnpm/@babel/runtime@7.12.13/node_modules/@babel/runtime/helpers/nonIterableRest.js:2:9)
    at _slicedToArray (webpack-internal:///../../node_modules/.pnpm/@babel/runtime@7.12.13/node_modules/@babel/runtime/helpers/slicedToArray.js:10:103)
    at ErrorBoundary (webpack-internal:///../../libs/utils/sentry/src/lib/ErrorBoundary.tsx:33:183)
    at renderWithHooks (/Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:271:20)
    at render$2 (/Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:278:6)
    at /Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:377:64
    at render (/Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:378:4)
    at visitElement (/Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:466:9)
    at visitLoop (/Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:478:17)
    at visit (/Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:517:3)
    at Object.module.exports [as default] (/Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:603:5)
    at _callee$ (webpack-internal:///../../node_modules/.pnpm/@trpc/next@6.3.0_805b647cab119c293891d4a228ac91ac/node_modules/@trpc/next/dist/trpc-next.cjs.dev.js:108:56)
    at tryCatch (/Users/pieter/Invisible/invisible/node_modules/.pnpm/regenerator-runtime@0.13.7/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/pieter/Invisible/invisible/node_modules/.pnpm/regenerator-runtime@0.13.7/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/pieter/Invisible/invisible/node_modules/.pnpm/regenerator-runtime@0.13.7/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (webpack-internal:///../../node_modules/.pnpm/@babel/runtime@7.14.6/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (webpack-internal:///../../node_modules/.pnpm/@babel/runtime@7.14.6/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at eval (webpack-internal:///../../node_modules/.pnpm/@babel/runtime@7.14.6/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7)
    at new Promise (<anonymous>)
    at Function.eval (webpack-internal:///../../node_modules/.pnpm/@babel/runtime@7.14.6/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
    at Function.eval [as getInitialProps] (webpack-internal:///../../node_modules/.pnpm/@trpc/next@6.3.0_805b647cab119c293891d4a228ac91ac/node_modules/@trpc/next/dist/trpc-next.cjs.dev.js:130:24)
    at loadGetInitialProps (/Users/pieter/Invisible/invisible/node_modules/.pnpm/next@10.2.3_507781d099a67956587e23f5ac79078b/node_modules/next/dist/next-server/lib/utils.js:5:101)
TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableRest (webpack-internal:///../../node_modules/.pnpm/@babel/runtime@7.12.13/node_modules/@babel/runtime/helpers/nonIterableRest.js:2:9)
    at _slicedToArray (webpack-internal:///../../node_modules/.pnpm/@babel/runtime@7.12.13/node_modules/@babel/runtime/helpers/slicedToArray.js:10:103)
    at ErrorBoundary (webpack-internal:///../../libs/utils/sentry/src/lib/ErrorBoundary.tsx:33:183)
    at renderWithHooks (/Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:271:20)
    at render$2 (/Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:278:6)
    at /Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:377:64
    at render (/Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:378:4)
    at visitElement (/Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:466:9)
    at visitLoop (/Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:478:17)
    at visit (/Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:517:3)
    at Object.module.exports [as default] (/Users/pieter/Invisible/invisible/node_modules/.pnpm/react-ssr-prepass@1.4.0_react@17.0.2/node_modules/react-ssr-prepass/dist/react-ssr-prepass.js:603:5)
    at _callee$ (webpack-internal:///../../node_modules/.pnpm/@trpc/next@6.3.0_805b647cab119c293891d4a228ac91ac/node_modules/@trpc/next/dist/trpc-next.cjs.dev.js:108:56)
    at tryCatch (/Users/pieter/Invisible/invisible/node_modules/.pnpm/regenerator-runtime@0.13.7/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/pieter/Invisible/invisible/node_modules/.pnpm/regenerator-runtime@0.13.7/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/pieter/Invisible/invisible/node_modules/.pnpm/regenerator-runtime@0.13.7/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (webpack-internal:///../../node_modules/.pnpm/@babel/runtime@7.14.6/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (webpack-internal:///../../node_modules/.pnpm/@babel/runtime@7.14.6/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at eval (webpack-internal:///../../node_modules/.pnpm/@babel/runtime@7.14.6/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7)
    at new Promise (<anonymous>)
    at Function.eval (webpack-internal:///../../node_modules/.pnpm/@babel/runtime@7.14.6/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
    at Function.eval [as getInitialProps] (webpack-internal:///../../node_modules/.pnpm/@trpc/next@6.3.0_805b647cab119c293891d4a228ac91ac/node_modules/@trpc/next/dist/trpc-next.cjs.dev.js:130:24)
    at loadGetInitialProps (/Users/pieter/Invisible/invisible/node_modules/.pnpm/next@10.2.3_507781d099a67956587e23f5ac79078b/node_modules/next/dist/next-server/lib/utils.js:5:101)
```

**Comment by balazsorban44** [comment] 2021-06-18 10:39
Please provide a reproduction.

**Comment by cyrus-za** [comment] 2021-06-18 11:22
@balazsorban44 here you go https://github.com/cyrus-za/next-auth-issue-2212

You'll notice I use pnpm but I created a `yarn` branch too. Same issue. 

It works fine when cloning the example app but as soon as switching to v4 and replacing `next-auth/client` imports to `next-auth/react` it throws errors

**Comment by balazsorban44** [comment] 2021-06-18 20:04
So I checked your reproduction, and it has multiple issues. v4 is going to contain a bunch of breaking changes, and so it would be nice if you could first accommodate for those, and check if your issue is still relevant. 

I just cloned https://github.com/nextauthjs/next-auth-example, changed the `next-auth` version to `4.0.0-next.15`, did the relevant changes, and had no problems.


Try going through the **BREAKING CHANGES** sections of the prereleases: https://github.com/nextauthjs/next-auth/releases

**Comment by cyrus-za** [comment] 2021-06-21 11:38
I checked the breaking changes and there's nothing mentioned about installing nodemailer. Why does v4 need nodemailer installed when v3 simply has it as a internal dep?

Also installing nodemailer might fix my reproduction but the actual app still fails with same issue. I'm not sure how to do a repro. I went through all the breaking changes and applied them.

**Comment by balazsorban44** [comment] 2021-06-21 15:15
Because we intend to deliver less code. If someone doesn't use the Email provider there is no need to install nodemailer. We will be more precise in the release notes when we release v4, but until then, you acknowledge that you are working with a potentially breaking version. Since the problem cannot be convincingly reproduced, I'll close this issue. Feel free to reopen if you found the exact issue, or open a PR with a potential fix.

**Closed by balazsorban44** 2021-06-21 15:15 UTC
Labels: bug, incomplete
