### ISSUE TITLE
Dynamically set NEXTAUTH_URL based on request data

### ISSUE THREAD

**Issue by jp112233** [nextauthjs/next-auth#2967] opened 2021-10-16 09:11 UTC
### Question 💬

We are using the next auth to login with fusionauth in our application which seems to work perfectly! 

We are looking for an option to use **NEXTAUTH_URL** dynamically. We have a case where we have multiple aliases like abc.com, xyz.com which are pointing to the same codebase. We would like to have a different **NEXTAUTH_URL** **based on from where the request is coming**. If It’s abc.com then it should be abc.com and If It’s xyz.com It should be xyz.com. 

Do we have any option to set this as a part of provider configuration? Here is my provider configurations. 

```
Providers.FusionAuth({
  id: "fusionauth",
  name: "FusionAuth",
  domain: "xyz.fusionauth.io",
  clientId: process.env.clientId,
  clientSecret: process.env.clientSecret,
  tenantId: process.env.tenantId,
  scope: "offline_access",
  profileUrl: `https://xyz.fusionauth.io/oauth2/userinfo`,
  profile(profile, _tokens) {
    return {
    id: profile.applicationId,
    email: profile.email,
    image: profile.picture,
    name: profile.name,
    userid: profile.sub,
    };
  },
})
```

Can anyone please help me with this?

Thanks a lot in advance!

### How to reproduce ☕️

I am looking for a solution where I can use **NEXTAUTH_URL** dynamically.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment] 2021-10-16 11:44
duplicate of #600

**Closed** 2021-10-16 11:44 UTC
Labels: question

**Comment by jp112233** [comment] 2021-10-16 11:50
Sure, Thanks.

Is nextauth having any plan to introduce this feature?

**Comment by balazsorban44** [comment] 2021-10-16 11:51
see the linked issue
