### ISSUE TITLE
NextAuth middleware incorrectly blocking authenticated users

### ISSUE THREAD

**Issue by burstWizard** [nextauthjs/next-auth#5096] opened 2022-08-05 06:53 UTC
### Question 💬

I'm integrating NextAuth into my web app and facing an issue with protecting specific pages. I have followed the docs here: https://next-auth.js.org/configuration/nextjs#middleware. When I visit a "restricted" page, even when I have authentication, it redirects me back to the login page. I can't ever get into the "restricted" page.

I know the user is correctly logged in because pages that are not protected are accessing user data just fine.

I am only using Google OAuth, no email, no other providers.

### How to reproduce ☕️

middleware.js at root like so:
```
export { default } from "next-auth/middleware"

export const config = { matcher: ["/student/account"] }
```
Set a NEXTAUTH_SECRET in .env using openssl generated string.

Visit /student/account after logging in, you will see that you are bounced back to the login page.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment] 2022-08-05 09:25
Likely a duplicate of #5008

**Closed by balazsorban44** 2022-08-05 09:25 UTC
Labels: question

**Comment by burstWizard** [comment] 2022-08-05 17:38
Thank you!, I'll wait for a fix.
