### ISSUE TITLE
callbackUrl seems to be ignored

### ISSUE THREAD

**Issue by bduff9** [nextauthjs/next-auth#1542] opened 2021-03-18 01:29 UTC
**Describe the bug**

Using callbackUrl with email, google, and twitter providers.  I would expect the application to redirect to this URL after successful sign-in.  Instead, it always redirects to the root.

**Steps to reproduce**

```
const { error: signInError } = await signIn('email', {
  callbackUrl,
  email,
  redirect: false,
});
```
..where callbackUrl is currently hardcoded to `http://localhost:3000/picks/set`.  I have confirmed this value, however, there is a cookie I see with the name `next-auth.callback-url` that is always set to `http%3A%2F%2Flocalhost%3A3000`.

**Expected behavior**

I would expect the application to be redirected to http://localhost:3000/picks/set after successful authentication.

**Screenshots or error logs**

N/A

**Additional context**

I am using the latest NextAuth (3.13.0) and NextJS (10.0.9).  Node version is 14.15.4.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [X] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by rmgpinto** [comment] 2021-04-02 08:19
There's a solution while this bug isn't fixed.
`$ yarn add cookies`

Then on your page:

`import Cookies from 'cookies'`

add this to `getServerSideProps(context)`:
```
const cookies = new Cookies(context.req, context.res)
cookies.set("next-auth.callback-url", <URL>)
```

thanks for pointing out to `next-auth.callback-url`

**Comment by balazsorban44** [comment] 2021-04-02 15:37
@bduff9 cluldnypu please a reproduction?

**Comment by khenrix** [comment] 2021-04-12 15:33
I have the same issue. 

@rmgpinto Thanks for the workaround. 
I managed to get it working using your suggestion locally.
But when I deploy the application it does not work.

I can see that the "next-auth.callback-url" is correctly set, but it seems to ignore it.

Running locally (by building / running and with dev server): http://localhost:3000/login_route -> (LOGIN) -> http://localhost:3000/wanted_route

Deployed: https://<my_website>.com/login_route -> (Login) -> https://<my_website>.com ???

Any suggestions?

**Comment by eugenehp** [comment] 2021-09-26 19:51
Here're some of the efforts I've tried to get callbacks to work but also subdomains too.

Specifically if you want to pass `callbackUrl` inside your `redirect_url` for Twitter and other OAuth 1.x providers, here's what [fixed it](https://github.com/eugenehp/next-auth/commit/01485aa7d5ee5f5b0f2b5ac211b638fa6690a555#diff-81e58f434494511377015c5f0595a88dfc3f1bfda36b0586a10d729bbf4e2dc1R16):

```javascript
provider.callbackUrl = provider.callbackUrl + `?callbackUrl=` + encodeURIComponent(req.options.callbackUrl)
```

Check previous commits in that branch to get a better [picture](https://github.com/eugenehp/next-auth/commit/df7ada7314c5cb52bbd5dc46bde82384c6b48f0c#diff-9e8ff2b96340e6d9fca060a8404aac415e4775be52e407f0362ef8663acbb1d9R35).

I know maintainers are focusing on the 4.x branch and options are not exposed there in the same way, but could be useful if you guys decide to revive the subdomains + callbackUrls persisted.

**Comment by geovanisouza92** [comment] 2022-01-23 16:17
I'm running in the same issue while trying to use Next Auth as a centralized/common auth infrastructure for cli login.

I've created a minimal repro example: https://github.com/geovanisouza92/next-auth-standalone-auth

**Comment by renevangsgaardjp** [comment] 2022-06-02 14:41
I just stumbled upon this issue today. We have an application that serves multiple domains, meaning that the `callbackUrl` is dynamic on each request. This issue makes that impossible, and I have not found any work around yet.

**Comment by renevangsgaardjp** [comment] 2022-06-07 14:27
I managed to get one step further, by overwriting `redirect_uri` on each sign in, like this:
```
signIn("keycloak", undefined, {
  redirect_uri: `https://${host}/api/auth/callback/keycloak`,
})
```
Now the `redirect_uri` is set correctly when redirecting to the auth provider (keycloak).

The issue now is that when I get back, next-auth attempts to fetch id token, and it fails by sending the wrong `redirect_uri` to the auth provider. This is the log statements from next-auth:
```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error invalid_grant (Incorrect redirect_uri) {
  error: {
    message: 'invalid_grant (Incorrect redirect_uri)',
    stack: 'OPError: invalid_grant (Incorrect redirect_uri)\n' +
      ... clipped ...
    name: 'OPError'
  },
  providerId: 'keycloak',
  message: 'invalid_grant (Incorrect redirect_uri)'
}
```

As I am uncertain if my issue is completely related to this issue, I have created another issue https://github.com/nextauthjs/next-auth/issues/4668.

**Comment by DracoBlue** [comment] 2022-11-02 10:39
I had a similiar issue and fixed it by specifiying the NEXTAUTH_URL with the proper base domain like https://example.org. This properly reformatted the callback url to my expected host.

**Comment by noah-haub** [comment] 2023-01-12 16:40
I for the life of me can't figure out how to use Next Auth with ngrok. My URLs keep changing on every app build, and the redirect Url is always incorrect.

Has anyone got Next Auth and ngrok working?

**Comment by geminiyellow** [comment] 2023-02-13 11:31
same issues .

Google provider can redirect collectly, but Apple provider not. i don't know why same logic cause two different result.

**Comment by DracoBlue** [comment] 2023-02-13 19:54
Please check if setting the parameter in https://github.com/nextauthjs/next-auth/issues/1542#issuecomment-1300016433 helps.

I was only searching for callbackUrl because my next url was not correct. Fixing it, fixed my issue. Leaving no other changes - especially to the callbackUrl - necessary at all.

**Comment by geminiyellow** [comment] 2023-02-14 14:03
thank you for your help. but i don't think my setting is wrong. when use debug true, only problem is when use apple provider get the  wrong cookies callback Url. i don't know where it was come from.

maybe i can update it before goto sns auth page.

> Please check if setting the env `NEXTAUTH_URL` in https://github.com/nextauthjs/next-auth/issues/1542#issuecomment-1300016433 helps.
> 
> I was only searching for callbackUrl because my next url was not correct. Fixing it, fixed my issue. Leaving no other changes - especially to the callbackUrl - necessary at all.

**Comment by geminiyellow** [comment] 2023-02-28 02:19
finally, i change the cookies's sameSite to none it work.

**Comment by ThangHuuVu** [comment] 2023-03-25 07:50
I cannot reproduce this issue in v4, so I'll close it. Feel free to reopen a new issue if you still have the problem 🙇‍♂️

**Closed by ThangHuuVu** 2023-03-25 07:50 UTC
Labels: bug

**Comment by gregg-cbs** [comment] 2023-04-14 21:52
> ```ts
> 
> 
> signIn('credentials', {
> ```

The magic for me was putting the right callback url in the signIn method:
```jsx
<button 
  onClick={()=> signIn('google', {
    callbackUrl: `${new URLSearchParams(window.location.search).get('callbackUrl')}`
  })}
>
  Sign in with Google
</button>
```

**Comment by mifrej** [comment] 2023-05-09 09:07
I'm using a custom Oauth provider setup, and have the same issue.
There are lots of moving parts (custom auth) in my solution, so very hard to prepare a replication example.
The solution from [comment](https://github.com/nextauthjs/next-auth/issues/1542#issuecomment-1167773809) helped.

I feel like the server-side `getServerSideProps` interactions with the session, should be documented in more detail.

**Comment by MGlobus** [comment] 2023-07-30 09:52
I added to the .env.local file in the root, NEXTAUTH_URL=<your_domain>api/auth
 and the problem was solved
