### ISSUE TITLE
Email Provider authentication does not create user account in account table in database after successful authentication

### ISSUE THREAD

**Issue by thebreaktop** [nextauthjs/next-auth#1313] opened 2021-02-14 14:02 UTC
**Describe the bug**

Email Provider authentication does not create user account in `account` table in database after successful authentication (only if new user)

Do not report bugs with your own project here, ask from help by raising a question instead - this helps us a lot with administration overhead.

**Steps to reproduce**
1. Sign in using Email
2. Verify email will be sent to specified email
3. Go to email and click on the verify your email link
4. You should be logged in
5. Check DB. The documentation `https://next-auth.js.org/providers/email` says 

> An account will not be created for the user until the first time they verify their email address. If an email address already associated with an account, the user will be signed in to that account when they use the link in the email.

So I would expect to see an account entry in the database table account once successfully logged in.

Here is an example of the issue. 

Here is an example with the bug `https://github.com/JunayedMizan/next-auth-bug`

**Expected behavior**
I would expect to see an account entry in the database table `account` once successfully logged in.

**Comment by iaincollins** [comment] 2021-02-14 16:56
Hi there!

Signing with email creates an entry in the **User** table but not the **Account** table.

It looks like the wording there could be clearer - when it says "account" it is referring to a User account, not an entry in the Account table (which is currently only used to store data about OAuth accounts). This is the intended behaviour.

Longer term, using the Account table to support linking email address is something I've had in mind, but I suspect will  be a breaking change if/when that drops. Doing this was ruled out of scope for the initial version due to the considerable extra work to support all the scenarios around that flow. It's probably not going be something that changes any time soon.

**Comment by balazsorban44** [comment] 2021-02-16 10:52
So we should improve the docs on this to be less ambiguous.

**Closed** 2021-05-06 22:54 UTC
Labels: documentation, good first issue

**Comment by surbhi-dot-dev** [comment] 2025-03-30 14:19
The documentation is quite confusing—I also expected an account to be created. Once I get past the learning curve, I’d be happy to contribute to improving the docs.
