### ISSUE TITLE
404 page in NextJS refresh endlessly because next auth middleware

### ISSUE THREAD

**Issue by meyer0x** [nextauthjs/next-auth#6765] opened 2023-02-20 11:29 UTC
### Environment

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 1.15 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Safari: 16.2

### Reproduction URL

No reproduction URL

### Describe the issue

When I create a custom 404 page in NextJS, it keeps refreshing while the next auth middleware is enabled on the page in question (via the middleware / matcher configuration).

### How to reproduce

Create a custom 404 page

Add the default next-auth/middleware in middleware.ts of your nextjs app

Add some pages in the matcher config of nextjs middleware 

### Expected behavior

Just the 404 page without redirecting to itself / refreshing

**Comment by bartektelec** [comment] 2023-02-22 08:47
https://github.com/bartektelec/authjs-bug-infinite-redirect

here a reproduction repo with SvelteKit. I think i explained it good enough in the README

**Comment by balazsorban44** [comment] 2023-05-19 10:19
@bartektelec thanks, but the report is specifically for Next.js Middleware, so it seems to be unrelated. Could you please reopen your issue as a separate one?

I'm closing this as the OP did not add a reproduction.

**Closed by balazsorban44** 2023-05-19 10:19 UTC
Labels: incomplete, triage
