### ISSUE TITLE
@auth/sveltekit has the wrong dependency on old @auth/core 0.5.1 package

### ISSUE THREAD

**Issue by hgoona** [nextauthjs/next-auth#7587] opened 2023-05-19 01:41 UTC
### Environment

-

### Reproduction URL

-

### Describe the issue

This package has an error: 
https://www.npmjs.com/package/@auth/sveltekit/v/0.3.1?activeTab=code

The dependency on @auth/core should be to v0.7.1 (not 0.5.1) unless I am missing something???
![image](https://github.com/nextauthjs/next-auth/assets/30910108/c33d2888-906b-4526-922a-6cf68569a1c9)

Please confirm? I'm not sure how to get around this issue but during build, it continues to reinstall this old version of auth/core and creates conflicting errors between the newer 0.7.1 and old 0.5.1 which I'm guessing should not exist there.

### How to reproduce

-

### Expected behavior

-

**Comment by hgoona** [comment] 2023-05-19 03:50
@balazsorban44 dunno if this is in your domain for authjs?

**Comment by hgoona** [comment] 2023-05-19 03:51
@balazsorban44 dunno if this is in your domain for authjs?

**Comment by balazsorban44** [comment] 2023-05-19 09:54
Duplicate of #6226. See https://github.com/nextauthjs/next-auth/issues/6226#issuecomment-1368277163 for a workaround.

**Closed by balazsorban44** 2023-05-19 09:54 UTC
Labels: triage
