### ISSUE TITLE
Next.14 issue with next-auth as resolving the dependency 

### ISSUE THREAD

**Issue by engislam95** [nextauthjs/next-auth#8972] opened 2023-10-27 05:10 UTC
### Environment

OS : Window , 
react : "^18",
Next : "14.0.0"
Next-auth : latest

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

  - facing currently the issue while setup next.js app using @latest 14 with next-auth. 
  
![image](https://github.com/nextauthjs/next-auth/assets/37150151/0f5ebbc1-8bd6-4197-82d2-848b9e59ef06)

### How to reproduce

Fix upstream dependency conflict

### Expected behavior

- next-auth working correctly without conflict or making it { --force or --legacy-peer-deps }.

**Comment by anuragchauhan766** [comment] 2023-10-27 10:06
try using beta version nextjs 14 document mention using next-auth beta  version

**Comment by philwolstenholme** [comment] 2023-10-27 11:41
This is a duplicate of https://github.com/nextauthjs/next-auth/issues/8970 and should be closed

**Comment by balazsorban44** [comment] 2023-10-27 19:59
:point_up:

**Closed by balazsorban44** 2023-10-27 19:59 UTC
Labels: bug, triage

**Comment by balazsorban44** [comment] 2023-10-27 20:03
`4.24.4` is out with a fix. Please upgrade `npm i next-auth@latest`
