### ISSUE TITLE
next-auth/react has no exported member 'getCsrfToken'

### ISSUE THREAD

**Issue by DanielSinclair** [nextauthjs/next-auth#8079] opened 2023-07-18 16:23 UTC
### Environment

next-auth: `4.22.2`
next: `13.4.3`
react: `18.2.0`
OS: macOS 13.4.1

### Reproduction URL

N/A

### Describe the issue

`getCsrfToken` export is missing in `4.22.2` when upgrading from `4.22.1`

### How to reproduce

Install `next-auth@4.22.2`
Import ```import { getCsrfToken } from 'next-auth/react';```

### Expected behavior

Expecting `getCsrfToken` to be exported

**Comment by kashyapro** [comment] 2023-07-18 16:40
I have the same issue of getToken method from 
```import { getToken } from "next-auth/jwt"```

**Comment by dovidk** [comment] 2023-07-18 16:48
Same issue, here are some other types that were removed as well

```import {
  // These are ignores due to the fact that the types are not correct.
  // Feel free to remove when a fix is available.

  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  ClientSafeProvider,
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  getCsrfToken,
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  getProviders,
} from 'next-auth/react';```

**Comment by balazsorban44** [comment] 2023-07-18 20:46
duplicate of #8078

**Closed by balazsorban44** 2023-07-18 20:46 UTC
Labels: triage
