### ISSUE TITLE
Dynamic configuration of `NEXTAUTH_URL` and `NEXTAUTH_SECRET`

### ISSUE THREAD

**Issue by khteh** [nextauthjs/next-auth#7264] opened 2023-04-15 05:03 UTC
### Description 📓

I have a React.JS/Next.JS application which can be accesed through 2 URLs and I configure it to use separate `clientId` and `clientSecret` based on `req.headers.host`.

I need to dynamically configure `NEXTAUTH_URL` based on the URL my application is accessed from. The DuendeIDS6Provider logs `"Invalid redirect_uri:` and
```
export default async function auth (req: NextApiRequest, res: NextApiResponse) {
    await NextAuth(req, res, {
        callbacks: {
          async redirect ({ url, baseUrl }) {
            const origin = new URL(url).origin
            console.log(`redirect url: ${url}, baseUrl: ${baseUrl}, URL(url).origin: ${origin}`)
            return `${baseUrl}/management/overviews`
          }
        }
    });
});
```
shows redirecting to the base url configure in `NEXTAUTH_URL`.

How to configure `NEXTAUTH_URL` and `NEXTAUTH_SECRET` dynamically based on the same parameter at runtime?

### How to reproduce ☕️

https://github.com/nextauthjs/next-auth-example accessed from 2 different URLs using different clientID to access DuendeIDS6Provider without any error. Current behaviour uses the hard-coded `NEXTAUTH_URL` which is read from ENV once when the application starts up.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment] 2023-04-15 15:56
Duplicate of #7247

**Closed by balazsorban44** 2023-04-15 15:56 UTC
Labels: enhancement, triage
