### ISSUE TITLE
"SyntaxError: Cannot use import statement outside a module" after updating @next-auth/firebase-adapter to 1.0.2

### ISSUE THREAD

**Issue by harlandjp** [nextauthjs/next-auth#5589] opened 2022-10-17 22:35 UTC
### Adapter type

@next-auth/firebase-adapter

### Environment

  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 738.03 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Safari: 16.0

### Reproduction URL

N/A

### Describe the issue

After updating @next-auth/firebase-adapter to 1.0.2, calls to next-auth endpoints fail with the error `error - SyntaxError: Cannot use import statement outside a module`.

### How to reproduce

Run NextJS and try to login using next-auth

### Expected behavior

Adapter works as expected.

**Comment by balazsorban44** [comment] 2022-10-18 19:59
Duplicate of #5551

**Closed by balazsorban44** 2022-10-18 19:59 UTC
Labels: adapters, firebase, triage
