### ISSUE TITLE
TypeScript error for the Credentials provider

### ISSUE THREAD

**Issue by dragoncorf** [nextauthjs/next-auth#2701] opened 2021-09-08 15:35 UTC
### Description 🐜

The changes to Providers in [...nextauth].ts in V4 appered a TypeScript error for the Credentials provider.

``` TypeScript
Type 'CredentialsConfig<{ username: { label: string; type: string; }; password: { label: string; type: string; }; }>' is not assignable to type 'Provider'.
  Type 'CredentialsConfig<{ username: { label: string; type: string; }; password: { label: string; type: string; }; }>' is not assignable to type 'CredentialsConfig<{}>'.
    Types of property 'authorize' are incompatible.
      Type '(credentials: Record<"username" | "password", string>, req: NextApiRequest) => Awaitable<Omit<User, "id"> | { id?: string | undefined; } | null>' is not assignable to type '(credentials: Record<never, string>, req: NextApiRequest) => Awaitable<Omit<User, "id"> | { id?: string | undefined; } | null>'.
        Types of parameters 'credentials' and 'credentials' are incompatible.
          Type 'Record<never, string>' is missing the following properties from type 'Record<"username" | "password", string>': username, password
```

### Is this a bug in your own project?

No

### How to reproduce ☕️

``` TypeScript
import bcrypt from 'bcryptjs';
import prisma from 'lib/prisma';
import NextAuth from 'next-auth';
import CredentialsProvider from 'next-auth/providers/credentials';

export default NextAuth({
  providers: [
    CredentialsProvider({
      name: 'Credentials',
      credentials: {
        username: { label: 'Username', type: 'text' },
        password: { label: 'Password', type: 'password' }
      },
      async authorize(credentials: any, req) {
        const user = await prisma.user.findUnique({
          where: {
            username: credentials.username
          }
        });

        if (!user) {
          return null;
        }

        const valid = await bcrypt.compare(credentials.password, user.password);

        if (!valid) {
          console.log(`Credentials not valid`);
          return null;
        }

        if (user) {
          return { ...user, email: user.username };
        }
        return null;
      }
    })
  ]
});
```

### Environment 🖥

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz 
    Memory: 3.44 GB / 11.81 GB
  Binaries:
    Node: 14.15.4 - D:\Node\node.EXE
    npm: 6.14.10 - D:\Node\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.38)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    next: ^10.2.3 => 10.2.3
    next-auth: ^4.0.0-beta.2 => 4.0.0-beta.2
    react: ^17.0.2 => 17.0.2

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment] 2021-09-08 17:07
I still cannot reproduce it, so it's probably a misconfiguration somewhere.

Make sure/double-check that your `node_modules/next-auth/package.json` contains at least version `4.0.0-beta.2`.

Here is how it looks locally for me. Note, I also removed the `any`, as it wasn't needed:
![](https://i.imgur.com/jzbwJ5r.png)


(Small suggestion, if you don't use `req`, just don't declare it.)

You could try creating a CodeSandbox or a reproduction repo if you still think it is an error, but I have a strong feeling it is something with the version being incorrect in node_modeules.

I'll close this, for now, but if you can prove the error in a reproducible way, I will gladly reopen it.

**Comment by Rhym** [comment] 2021-09-08 21:39
@balazsorban44 Can you please show how you're importing the provider?

**Comment by balazsorban44** [comment] 2021-09-08 21:42
I literally pasted the code from above. 😅

**Comment by Rhym** [comment] 2021-09-08 21:45
Haha, I swear I must be doing something dumb.

![Screen Shot 2021-09-09 at 09 44 18](https://user-images.githubusercontent.com/1136811/132589825-4821be5b-cda4-4508-baeb-d7299c2765b3.png)

**Comment by balazsorban44** [comment] 2021-09-08 21:49
Here it is: https://stackblitz.com/edit/nextjs-hdxwhs?file=pages/api/auth/[...nextauth].ts

**Comment by Rhym** [comment] 2021-09-08 22:14
Here's a reproducible issue: https://codesandbox.io/s/charming-feynman-0p5gf?file=/src/pages/api/auth/%5B...nextauth%5D.ts

**Comment by balazsorban44** [comment] 2021-09-08 22:28
Now that just doesn't make sense to my brain... 👀

**Comment by Rhym** [comment] 2021-09-08 22:29
Me too man, me too 😂

**Comment by balazsorban44** [comment] 2021-09-08 22:30
Maybe a difference in the `tsconfig.json` causing this?

I have to go now, but please keep digging :pray:

**Comment by Rhym** [comment] 2021-09-08 22:37
The issue is when the `tsconfig.json` has strict mode turned on: `"strict":true,`

**Comment by Rhym** [comment] 2021-09-08 22:40
Sweet man, thank you for all your time working with me on this. For now I'll set strict to false, but would be awesome to support strict mode too :) But totally get if that would be a ballache.

**Comment by balazsorban44** [comment] 2021-09-09 10:54
I will close this in favour of #2709.

The current fix for **this** issue is to turn off strict mode in `tsconfig.json`.

**Closed by balazsorban44** 2021-09-09 10:54 UTC
Labels: bug, TypeScript

**Comment by copleykj** [comment] 2021-11-18 18:20
As an update to this just in case anyone else comes across the problem, upgrading from 4.0.0-beta.4 to 4.0.0-beta.7 worked for me.

**Comment by balazsorban44** [comment] 2021-11-18 19:24
it did not, see my answer here https://github.com/nextauthjs/next-auth/issues/2709#issuecomment-973183324

**Comment by r4881t** [comment] 2022-02-04 17:29
I'm facing something similar it seems. Asked here at SO https://stackoverflow.com/questions/70990262/how-to-write-authorize-function-correctly-in-typescript-for-nextauthjs

**Comment by TimMTech** [comment] 2022-09-21 23:23
Nextjs with its 4,555,332,233 issue.  Keep it up Vercel!

**Comment by RudrThakur** [comment] 2022-10-22 05:22
![image](https://user-images.githubusercontent.com/26500643/197321960-f42f52e5-dbfe-4f04-841a-72660cb8d0df.png)

doesn't work anymore. Did anyone find the solution yet.

**Comment by coycoylaniba** [comment] 2023-03-13 11:03
does anyone have a fix for this? im also getting this error.

**Comment by gerardmarquinarubio** [comment] 2023-05-06 17:40
Bumping this, still an issue as of May 2023. My workaround was to simply type the return as `any`:

```ts
CredentialsProvider({
      name: "Credentials",
      credentials: { 
        email: { label: "Username", type: "text", placeholder: "johndoe@domain.com" },
        password: { label: "Password", type: "password", placeholder: "verysecurepassword" },
      },
      async authorize (credentials) {
        try {
          if (!credentials) throw new Error("no credentials to log in as");
          const { email, password } = credentials;
          const {
            salt,
            password: hashedPassword,
            ...user
          } = await client.user.findUniqueOrThrow({
            where: {
              email,
            },
          });
          const logged = await comparePassword(password, salt, hashedPassword);
          if (!logged) throw new Error("invalid credentials");
          return user as any; // fix for https://github.com/nextauthjs/next-auth/issues/2701
        } catch (ignored) {
          return null;
        }
      }
    })
```

**Comment by aayushsingh7** [comment] 2023-05-08 17:17
Can anyone tell me what's wrong with my code i have tried everything even the  ( "strict":false  ) but it still doesn't work

` CredentialsProvider({
        name: "Credentials",
        async authorize(credentials, req) {
          if (!credentials) {
            throw new Error("Credentials are required");
          }
          const isUserExists = await User.findOne({ email: credentials.email });
          if (!isUserExists) {
           throw new Error("No user found")
          }
          const checkPassword = await bcryptjs.compare(
            credentials.password,
            isUserExists.password
          );
          if (!checkPassword || isUserExists.email !== credentials.email) {
            throw new Error("Invalid credentials")
          }
          return isUserExists
        },
      })`

**Comment by gerardmarquinarubio** [comment] 2023-05-08 17:24
> Can anyone tell me what's wrong with my code i have tried everything even the ( "strict":false ) but it still doesn't work
> 
> ```
> ` CredentialsProvider({
>         name: "Credentials",
>         async authorize(credentials, req) {
>           if (!credentials) {
>             throw new Error("Credentials are required");
>           }
>           const isUserExists = await User.findOne({ email: credentials.email });
>           if (!isUserExists) {
>            throw new Error("No user found")
>           }
>           const checkPassword = await bcryptjs.compare(
>             credentials.password,
>             isUserExists.password
>           );
>           if (!checkPassword || isUserExists.email !== credentials.email) {
>             throw new Error("Invalid credentials")
>           }
>           return isUserExists
>         },
>       })`
> ```

For one you forgot the credentials field in the provider, in my comment that's just above yours you've got a working example with prisma too.

**Comment by Issaminu** [comment] 2023-05-14 15:15
@balazsorban44 Any updates on this?

**Comment by Meagle89** [comment] 2023-05-31 10:09
`interface Credentials extends Record<"username" | "password", string> {}

  async authorize(credentials?: Credentials): Promise<LoggedInUser | null> {
        if (!credentials) return null;
`

fixed it for me

**Comment by michael-lloyd-morris** [comment] 2023-08-16 19:18
Instead of changing the strict setting in the tsconfig I highly recommend just using tsignore

```
  providers: [
    // @ts-ignore
    CredentialsProvider({
```

**Comment by itihask56** [comment] 2023-10-14 06:44
You can get rid of this kind of error in two ways:
//1
in tsconfig.json file, add "noImplicitAny " :false,

`{
  "compilerOptions": {
    // ... other properties
    "noImplicitAny": false
  }
}`

//2

in tsconfig.json file, set "strict " :false,

`{
  "compilerOptions": {
    // ... other properties
    "strict": false
  }
}`

**Comment by Yohannfra** [comment] 2023-11-06 15:15
> Instead of changing the strict setting in the tsconfig I highly recommend just using tsignore
> 
> ```
>   providers: [
>     // @ts-ignore
>     CredentialsProvider({
> ```

```typescript
      /* eslint-disable-next-line @typescript-eslint/ban-ts-comment*/
      // @ts-ignore
      async authorize(credentials, req) {
      ...
 ```
 
 Works like a charm ! 👍

**Comment by AnimeAllstar** [comment] 2024-02-05 00:40
why has this been closed if the issue still exists when `"strict": true`?

**Comment by cwiik** [comment] 2024-02-05 17:53
> why has this been closed if the issue still exists when `"strict": true`?

thinking same..

**Comment by zllWarMachinellz** [comment] 2024-02-06 16:43
The solution I provided for this issue encountered with Next.js was as follows:

 `async authorize(credentials, req): Promise<any>`
i used prisma and nextAuth "version": "4.24.5"

**Comment by Magimart** [comment] 2024-02-08 14:16
This solution works without turning strict to false   ==== strict: true;
I have tested on Nextjs 13.5.4 and node 18x , the deployment node version18x at vercel.

simply combine the types 

type CombineRequest = Request & NextApiRequest;
type CombineResponse = Response & NextApiResponse;

async function auth(req: CombineRequest, res: CombineResponse){ 

    return await NextAuth(req, res, {
        session: {
            strategy: "jwt",
        },
        providers: [
            CredentialProviders({
               // @ts-ignore
               async authorize(credentials: Credentials): Promise<any>{
                 /** your logic */
               }
            })
        ]
    })
};

**Comment by jaydave1412** [comment] 2024-03-30 22:57
I have this config that is working but it should not

    import nextAuth from "next-auth/next";
    import { AuthOptions } from "next-auth";
    import CredentialsProvider from "next-auth/providers/credentials";
    
    export const authOptions: AuthOptions = {
      providers: [
        CredentialsProvider({
          credentials: {
            email: {},
            password: {},
          },
          async authorize(credentials) {
            const user = { id: "hello", name: "jay", password: "dave" };
            if (!user || !user.password) return null;
    
            const passwordsMatch = user.password === credentials?.password;
    
            if (passwordsMatch) return user;
            return null;
          },
        }),
      ],
    };
    
    export default nextAuth(authOptions);

how I decided to add id, 
I looked into the types, 

this is how credentials config interface is defined

    export interface CredentialsConfig<
      C extends Record<string, CredentialInput> = Record<string, CredentialInput>
    > extends CommonProviderOptions {
      type: "credentials"
      credentials: C
      authorize: (
        credentials: Record<keyof C, string> | undefined,
        req: Pick<RequestInternal, "body" | "query" | "headers" | "method">
      ) => Awaitable<User | null>
    }

as you can see it returns awaitable user and user is defined like this

    export interface DefaultUser {
      id: string
      name?: string | null
      email?: string | null
      image?: string | null
    }
    
    /**
     * The shape of the returned object in the OAuth providers' `profile` callback,
     * available in the `jwt` and `session` callbacks,
     * or the second parameter of the `session` callback, when using a database.
     *
     * [`signIn` callback](https://next-auth.js.org/configuration/callbacks#sign-in-callback) |
     * [`session` callback](https://next-auth.js.org/configuration/callbacks#jwt-callback) |
     * [`jwt` callback](https://next-auth.js.org/configuration/callbacks#jwt-callback) |
     * [`profile` OAuth provider callback](https://next-auth.js.org/configuration/providers#using-a-custom-provider)
     */
    export interface User extends DefaultUser {}

as you can see password is not part of User in the interface then why is it working

**Comment by randhirsingh0578** [comment] 2024-04-18 15:22
import NextAuth, { NextAuthOptions } from "next-auth";
import CredentialsProvider from "next-auth/providers/credentials";

const authOptions: NextAuthOptions = {
  providers: [
    CredentialsProvider({
      type: "credentials",
      credentials: {},
      authorize(credentials:any, req:any) {
        const user = { id: "1", name: "J Smith", email: "jsmith@example.com" }
        if (user) {
            return user
          } else {
            return null
          }
     }
    }),
  ],
};

export default NextAuth(authOptions);

**Comment by randhirsingh0578** [comment] 2024-04-18 15:22
please try my  above code in for the [...nextauth].tsx this works

**Comment by ebengtso** [comment] 2024-07-08 08:01
This works. It's a compiled snippet from the documents and comments

`interface Credentials extends Record<"identifier" | "password", string> {}

export const authOptions = {

  providers: [
    CredentialsProvider({
      credentials: {
        identifier: { label: 'Identifier', type: 'identifier' },
        password: { label: 'Password', type: 'password' },
      }, 

      authorize: async (credentials?:Credentials) : Promise<User | null> =>  {
        if (!credentials) return null;
        ...
        return {...user props here...} as User;

`

**Comment by anggaggaH** [comment] 2024-10-31 09:46
> This works. It's a compiled snippet from the documents and comments
> 
> `interface Credentials extends Record<"identifier" | "password", string> {}
> 
> export const authOptions = {
> 
> providers: [ CredentialsProvider({ credentials: { identifier: { label: 'Identifier', type: 'identifier' }, password: { label: 'Password', type: 'password' }, },
> 
> ```
>   authorize: async (credentials?:Credentials) : Promise<User | null> =>  {
>     if (!credentials) return null;
>     ...
>     return {...user props here...} as User;
> ```
> 
> `

Thanks, it's work

really appreciate it

**Comment by h-behgam** [comment] 2024-11-05 14:59
> > This works. It's a compiled snippet from the documents and comments
> > `interface Credentials extends Record<"identifier" | "password", string> {}
> > export const authOptions = {
> > providers: [ CredentialsProvider({ credentials: { identifier: { label: 'Identifier', type: 'identifier' }, password: { label: 'Password', type: 'password' }, },
> > ```
> >   authorize: async (credentials?:Credentials) : Promise<User | null> =>  {
> >     if (!credentials) return null;
> >     ...
> >     return {...user props here...} as User;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `
> 
> Thanks, it's work
> 
> really appreciate it


Thanks, it's works.

**Comment by grepsoft** [comment] 2024-12-19 22:59
this issue is still present. 
```
    "next": "15.1.0",
    "next-auth": "^5.0.0-beta.25",
```
and strict mode is true:
`    "strict": true,`
