### ISSUE TITLE
Does not load env from `next.config.js` and keep using the wrong URL (localhost:3000) for sign in

### ISSUE THREAD

**Issue by khteh** [nextauthjs/next-auth#6768] opened 2023-02-21 03:37 UTC
### Environment

  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 47.11 GB / 62.48 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 110.0

### Reproduction URL
https://github.com/nextauthjs/next-auth-example
Any value other than https://localhost:3000

### Describe the issue

I have both `NEXTAUTH_URL` and `NEXTAUTH_URL_INTERNAL` defined as `https://localhost:4434` but clicking the sign in button keeps redirecting to `http://localhost:3000/api/auth/signin/<provider>`

`"next-auth": "^4.19.2",`

Console log:
```
NEXTAUTH_URL: https://localhost:4434
[next-auth][warn][NEXTAUTH_URL] 
https://next-auth.js.org/warnings#nextauth_url
```
### How to reproduce

You can reproduce yourself!

### Expected behavior

`NEXTAUTH_URL` and `NEXTAUTH_SECRET` should be read from `next.config.js`

**Comment by khteh** [comment] 2023-02-22 03:08
Using `.env.local` works but NOT with `next.config.js`:
```
const config = require('config')
module.exports = {
    env: {
        NEXTAUTH_SECRET: config.get('NEXTAUTH_SECRET'),
        NEXTAUTH_URL: config.get('NEXTAUTH_URL'),
        DUENDE_IDS6_ISSUER: config.get('DUENDE_IDS6_ISSUER'),
        DUENDE_IDS6_CLIENT_ID: config.get('DUENDE_IDS6_CLIENT_ID'),
        DUENDE_IDS6_CLIENT_SECRET: config.get('DUENDE_IDS6_CLIENT_SECRET'),
    }    
}
```

**Comment by balazsorban44** [comment] 2023-02-28 11:45
Using `next.config.js` (especially for secrets!) is not recommended as they will be part of the client bundle, as documented:

> Note: environment variables specified in this way will always be included in the JavaScript bundle, prefixing the environment variable name with NEXT_PUBLIC_ only has an effect when specifying them [through the environment or .env files](https://nextjs.org/docs/basic-features/environment-variables).

https://nextjs.org/docs/api-reference/next.config.js/environment-variables

I recommend using `.env.local` for all variables instead. 

_A kind reminder, you have [posted 10 issues](https://github.com/nextauthjs/next-auth/issues?q=is%3Aissue+author%3Akhteh) recently, all without a proper reproduction. `http://localhost:3000` is _not_ a reproduction. We need to see your code to investigate in most cases. If you have project-specific questions (like many of the opened issues), please use [Discussuions](https://github.com/nextauthjs/next-auth/discussions) instead._ The issue tracker is for reporting bugs.

**Closed by balazsorban44** 2023-02-28 11:45 UTC
Labels: incomplete, triage

**Comment by khteh** [comment] 2023-03-13 01:33
My application runs in k8s. Would k8s container environment work instead of `.env`?

**Comment by redimongo** [comment] 2023-03-15 05:55
I am having issues with this with the latest version 4.20.1 and while running in a docker container.

I am using 
```
NEXTAUTH_URL_INTERNAL=http://nextjs:3000
```

as my docker name is nextjs it was working find when using 4.10.3. Tried to upgrade and bam things broke.

**Comment by sreimer15** [comment] 2023-07-11 22:08
I am trying to have my http server be accessible via proxy
```sh
npx local-ssl-proxy --source 3001 --target 3000
```

Since I have to do some hack for instagram OAUTH, but sinve my server is actually on http, all my sessions break because all my redirect urls are going to http in local development

is there some way to always force https using this library?
