### ISSUE TITLE
Can't build the app since upgraded to nextjs 13.4.4

### ISSUE THREAD

**Issue by mortezaalizadeh** [nextauthjs/next-auth#7659] opened 2023-05-27 08:19 UTC
### Question 💬

Hi, since the new nextjs version 13.4.4  came out (I was using version 13.4.3 before), I can no longer build my app and I am getting the following error while building the app. Does anyone have any idea what has changed causing this issue? Cheers

╰─➤  yarn build
yarn run v1.22.19
$ next build
- info Linting and checking validity of types  
Failed to compile.

./node_modules/next-auth/next/middleware.js
Module parse failed: Identifier 'NextResponse' has already been declared (3:6)
File was processed with these loaders:
 * ./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
You may need an additional loader to handle the result of these loaders.
| "use strict";
| const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;
> const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;
| var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");
| Object.defineProperty(exports, "__esModule", {

Import trace for requested module:
./node_modules/next-auth/next/middleware.js
./node_modules/next-auth/middleware.js

> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### How to reproduce ☕️

Upgreade nextjs to version 13.4.4 and try to build the app

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by moinulmoin** [comment] 2023-05-29 11:54
Yes, same experience here. 
![image](https://github.com/nextauthjs/next-auth/assets/63459189/33cae5b8-c309-4e97-b0be-e37904c6fcd7)

**Comment by osomaher2020** [comment] 2023-05-29 13:19
![image](https://github.com/nextauthjs/next-auth/assets/72032764/a63a049c-fbf3-42fc-b9b1-7123b6dd124b)

The same Issue !

**Comment by osomaher2020** [comment] 2023-05-29 14:04
yarn add next@13.3.3

Solved it 💯

**Comment by jstebenne** [comment] 2023-05-29 18:25
I believe this issue is a duplicate of https://github.com/nextauthjs/next-auth/issues/7659

**Comment by balazsorban44** [comment] 2023-05-29 18:54
duplicate of #7650

**Closed by balazsorban44** 2023-05-29 18:54 UTC
Labels: question
