### ISSUE TITLE
Not Found: NextAuth.js in Next13 App Level Directory

### ISSUE THREAD

**Issue by erwinagpasa** [nextauthjs/next-auth#7120] opened 2023-03-31 09:47 UTC
### Environment

Hi Please anyone can help me? I'm using package
```
"next": "13.2.4",
"next-auth": "^4.20.1",
"react": "18.2.0",
```

and I have submit function to register user
```
async function onSubmit(values: any) {
    const options = {
      method: "POST",
      headers: { "Content-Type": "application/json", },
      body: JSON.stringify(values),
    }

    await fetch('/api/auth/signup', options)
      .then(res => res.json())
      .then((data) => {
        if (data) router.push('/authentication');
      });
    console.log(values)

  }
```
but when I hit submit I got this error

**http://localhost:3000/api/auth/signup 404 (Not Found)**

Below is my project directory
<img width="301" alt="Screenshot 2023-03-31 at 9 25 19 AM" src="https://user-images.githubusercontent.com/637956/229086269-d6b49ad0-3c9f-4fd8-92a5-91a1891e0d60.png">

### Reproduction URL

https://github.com/nextauthjs/next-auth-example/APP

### Describe the issue

**http://localhost:3000/api/auth/signup 404 (Not Found)**

### How to reproduce

Install latest nextjs
```
"next": "13.2.4",
"next-auth": "^4.20.1",
"react": "18.2.0",
```

### Expected behavior

**http://localhost:3000/api/auth/signup 404 (Not Found)**
This in App level directory

**Comment by erwinagpasa** [comment] 2023-03-31 10:37
btw I've change the [...nextauth].tsx to **[...nextauth].ts**

**Comment by balazsorban44** [comment] 2023-03-31 14:06
Duplicate of #6752. You cannot use regular API Route syntax in the App Router, but we are working on supporting the new syntax. See #6777

**Closed by balazsorban44** 2023-03-31 14:06 UTC
Labels: triage
