### ISSUE TITLE
DynamoDB Adapter Type Script Error

### ISSUE THREAD

**Issue by pdomala** [nextauthjs/next-auth#7847] opened 2023-06-21 11:00 UTC
### Adapter type

@auth/dynamodb-adapter

### Environment

System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 209.95 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.5

Package Versions

"next": "13.4.3",
"next-auth": "^4.22.1",
"@auth/dynamodb-adapter": "^1.0.0",

### Reproduction URL

Next Auth Adapter Example at https://authjs.dev/reference/adapter/dynamodb

### Describe the issue

Follwing official documentation at https://authjs.dev/reference/adapter/dynamodb to add DynamoDB Adapter.
After Adding the code from the doco receiving below type script error

`Type 'Adapter' is not assignable to type 'Adapter | undefined'.
  Type 'Adapter' is not assignable to type 'DefaultAdapter & { createVerificationToken: (verificationToken: VerificationToken) => Awaitable<VerificationToken | null | undefined>; useVerificationToken: (params: { ...; }) => Awaitable<...>; }'.
    Type 'Adapter' is not assignable to type 'DefaultAdapter'.
      Types of property 'createUser' are incompatible.
        Type '((user: Omit<AdapterUser, "id">) => Awaitable<AdapterUser>) | undefined' is not assignable to type '(user: Omit<AdapterUser, "id">) => Awaitable<AdapterUser>'.
          Type 'undefined' is not assignable to type '(user: Omit<AdapterUser, "id">) => Awaitable<AdapterUser>'.ts(2322)
types.d.ts(106, 5): The expected type comes from property 'adapter' which is declared here on type 'AuthOptions'`

### How to reproduce

Add the code from the example into nextAuth route.tsx

### Expected behavior

No typescript error

**Comment by rtman** [comment] 2023-06-22 00:09
Getting the same thing with the supabase adapter

```
Type 'Adapter' is not assignable to type 'Adapter<boolean> | undefined'.
  Type 'Adapter' is not assignable to type 'DefaultAdapter & { createVerificationToken: (verificationToken: VerificationToken) => Awaitable<VerificationToken | null | undefined>; useVerificationToken: (params: { ...; }) => Awaitable<...>; }'.
    Type 'Adapter' is not assignable to type 'DefaultAdapter'.
      Types of property 'createUser' are incompatible.
        Type '((user: Omit<AdapterUser, "id">) => Awaitable<AdapterUser>) | undefined' is not assignable to type '(user: Omit<AdapterUser, "id">) => Awaitable<AdapterUser>'.
          Type 'undefined' is not assignable to type '(user: Omit<AdapterUser, "id">) => Awaitable<AdapterUser>'.ts(2322)
 ```

**Comment by balazsorban44** [comment] 2023-06-24 08:28
Duplicate of #7727. see an explanation here https://github.com/nextauthjs/next-auth/issues/7727#issuecomment-1577107093

**Closed by balazsorban44** 2023-06-24 08:28 UTC
Labels: adapters, dynamodb, triage
