### ISSUE TITLE
useSession/Provider does not update when a new session is created until page reload.

### ISSUE THREAD

**Issue by paul-vd** [nextauthjs/next-auth#2208] opened 2021-06-17 16:17 UTC
## Description 🐜

When a page is not reloaded after login, the useSession/Provider is never updated, even after calling getSession.

## How to reproduce ☕️

1. Here is a [reproduction ](https://github.com/PaulPCIO/next-auth-session) of the issue.
2. I have set up a modal based login using a security code, for this example, I have [hardcoded ](https://github.com/PaulPCIO/next-auth-session/blob/434b417d24e3ae1d4b1190db2a97fb6da169c296/pages/api/auth/%5B...nextauth%5D.js#L14) the security code to `TEST`
3. When you log in successfully, the [callpack API](https://github.com/PaulPCIO/next-auth-session/blob/434b417d24e3ae1d4b1190db2a97fb6da169c296/components/login-view.js#L95-L97) triggers an additional [getSession](https://github.com/PaulPCIO/next-auth-session/blob/434b417d24e3ae1d4b1190db2a97fb6da169c296/components/login-view.js#L99).
4. At this stage the cookies are created and the session should be there, but the provider does not update until you refresh the page.

## Screenshots / Logs 📽

![example](https://user-images.githubusercontent.com/39598117/122434876-04067a00-cf87-11eb-8f04-a039edb819b2.gif)

## Environment 🖥

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 11.23 GB / 24.97 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
```

**Comment by balazsorban44** [comment] 2021-06-17 16:31
Hi, your reproduction is unfortunately unavailable, maybe it's private? Could you make sure it's available?

**Comment by PaulPCIO** [comment] 2021-06-17 16:53
Sorry yea it was on private, I made it public now.

**Comment by ielijose** [comment] 2021-06-17 23:20
I have the same issue :(

**Comment by Gabsys** [comment] 2021-07-07 05:20
Having the same issue as well when using `redirect:false` with signIn()

**Comment by AlaaZorkane** [comment] 2021-07-08 16:16
Having same issue with `signOut` and `redirect: false`

**Comment by VibingCreator** [comment] 2022-01-03 19:12
Same issue, also from time to time I have got to sign-in twice for some reason.

**Comment by vatsal-s** [comment] 2022-01-04 13:39
Facing the same issue

**Comment by balazsorban44** [comment] 2022-01-05 03:21
Please stop commenting "same issue", it's not helpful.

**Comment by ThangHuuVu** [comment] 2023-03-25 11:47
Hi all, let's continue the discussion here: https://github.com/nextauthjs/next-auth/discussions/3941#discussioncomment-5426142 I'm closing this issue.

**Closed by ThangHuuVu** 2023-03-25 11:47 UTC
Labels: bug

**Comment by estani** [comment] 2025-01-14 16:03
Am I missing something? #3941 is about updating the session, not reacting to session updates.

I have something like:
```js
function UserNameWrapped() {
  const { data: session } = useSession();
  const [userName, setUserName] = React.useState("");
  useEffect(() => {
    if (!session) return;
    setUserName(session.user.name + ' (user)');
  }, [session?.user.name]);
  return <div>dev</div>
}
export default function UserName() {
  return (
    <SessionProvider>
      <UserNameWrapped />
    </SessionProvider>
  )
}
```

I'm changing the session in some other component. My expectation was that the name would be updated, but is not.
Is this because I use a different Session provider? Even if it is the same session, this are not shared between different SessionProviders?
Reloading sorts everything out, as mentioned in the tittle of this 5 years old ticket (I presume next-js changed a lot in this time...).
