### ISSUE TITLE
Cancelling OAuth flow crashes the server

### ISSUE THREAD

**Issue by zaidhuda** [nextauthjs/next-auth#2806] opened 2021-09-21 02:29 UTC
### Description 🐜

The OAuth flow works fine except when it's cancelled while running on production build. Although it logs the same error on development (ERR_HTTP_HEADERS_SENT), the server itself is not terminated.

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Part of the config. I don't think the other configurations are relevant.
```
export default NextAuth({
  ...,
  providers: [
    {
      id: 'esri',
      name: 'Esri',
      type: 'oauth',
      version: '2.0',
      authorizationUrl: `${process.env.ESRI_PORTAL}/oauth2/authorize?response_type=code`,
      accessTokenUrl: `${process.env.ESRI_PORTAL}/oauth2/token?grant_type=authorization_code&client_id=${process.env.ARCGIS_CLIENT_ID}`,
      profileUrl: `${process.env.ESRI_PORTAL}/oauth2/token?grant_type=authorization_code&client_id=${process.env.ARCGIS_CLIENT_ID}`,
      clientId: process.env.ARCGIS_CLIENT_ID,
      clientSecret: process.env.ARCGIS_CLIENT_SECRET,
      profile: async (_profile, tokens) => {
        ...
      },
    },
  ],
  pages: {
    signIn: '/auth/login',
  },
  callbacks: {
    redirect: async (url, baseUrl) => {
      return url.startsWith(baseUrl) ? url : `${baseUrl}${url}`;
    },
  },
});
```

### Screenshots / Logs 📽

```
[next-auth][error][state_error] 
https://next-auth.js.org/errors#state_error OAuthCallbackError: Invalid state returned from OAuth provider
    at Object.handleCallback (./node_modules/next-auth/dist/server/lib/oauth/state-handler.js:42:13)
    at ./node_modules/next-auth/dist/server/index.js:186:29
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
[next-auth][error][oauth_get_access_token_error] 
https://next-auth.js.org/errors#oauth_get_access_token_error {
  statusCode: 401,
  data: ''
} esri undefined
[next-auth][error][oauth_callback_error] 
https://next-auth.js.org/errors#oauth_callback_error {
  statusCode: 401,
  data: ''
}
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:329:5)
    at ServerResponse.setHeader (node:_http_outgoing:579:11)
    at ServerResponse.res.redirect (./node_modules/next-auth/dist/server/lib/extend-res.js:39:21)
    at Object.callback (./node_modules/next-auth/dist/server/routes/callback.js:156:18)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
error Command failed with exit code 1.
```

### Environment 🖥

```
  System:
    OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 15.01 GB / 25.02 GB
    Container: Yes
    Shell: 3.2.2 - /usr/bin/fish
  Binaries:
    Node: 15.14.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.23.0 - /usr/bin/npm
  npmPackages:
    next: 11.1.2 => 11.1.2 
    next-auth: ^3.28.0 => 3.28.0 
    react: 17.0.2 => 17.0.2
```

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by balazsorban44** [comment] 2021-09-21 07:54
By crashing you mean you end up on a Next.js 500 page, or that the user simply isn't logged in, and maybe redirected back to the login page with an error code in the URL?

**Comment by zaidhuda** [comment] 2021-09-23 03:44
By crashing I mean the server node process is terminated. I'll need to restart the server.

![image](https://user-images.githubusercontent.com/3919103/134451554-1ac7af04-ba51-4485-8aed-b81afd3ff3e4.png)

This is the OAuth page, clicking Cancel redirect the user back to my app with `state_error`, which is expected. The unexpected part is the `ERR_HTTP_HEADERS_SENT`.

**Comment by balazsorban44** [comment] 2021-09-23 23:04
So when hitting cancel, to which URL is the user redirected back to?

**Comment by zaidhuda** [comment] 2021-09-24 02:13
The login page
```
http://localhost:3000/auth/login?callbackUrl=http://localhost:3000/auth/login&error=OAuthCallback
```
Do you think this happens because I don't have `error` page set?
```
  pages: {
    signIn: '/auth/login',
  },
```

**Comment by zaidhuda** [comment] 2021-09-24 06:37
I've tried removing the `pages` options altogether and used the default sign in page but the server still crashes after clicking cancel on the OAuth page.

**Comment by balazsorban44** [comment] 2021-09-24 10:12
I was able to reproduce this (or something similar) with IdentityServer4, although it did not crash the page.

We have a "Back to app" button in our provider's login screen, which is basically the same as the cancel button in your case.

The issue is that it redirects to `http://example.com/api/auth/callback/your-provider` and that endpoint does not handle cancellations.

The tricky part is that at least in our case when the user cancels the login, the provider does not give any query params or indication in the body when calling the callback endpoint.

**Comment by zaidhuda** [comment] 2021-09-24 11:15
Here's the redirect flow after clicking cancel:

1. baseUrl/api/auth/callback/esri?error=access_denied&error_description=The%20user%20denied%20your%20request.
2. baseUrl/api/auth/error?error=OAuthCallback
3. baseUrl/api/auth/signin?error=OAuthCallback
4. baseUrl/auth/login?callbackUrl=baseUrl/auth/login&error=OAuthCallback

> Other than that, it would be worth checking if you can configure where the cancel button should redirect to.

I'll look into it. Is there anything else I can do on my side for now?

**Comment by balazsorban44** [comment] 2021-09-24 11:31
Thanks! So this is very similar to #1820! I will look more into it. As you show in step 1., there is an actual error returned, so could handle it. as in #1820, we currently don't do it with `GET` requests.

I'll look into this!

I still don't see the reason for a crash though.

I think this is the relevant redirect after an error:
https://github.com/nextauthjs/next-auth/blob/e8a58a01b6b8c456268771f9b382fa300ccab8ac/src/server/routes/callback.js#L174

I see that we don't `await` the redirect, because usually, it's not a Promise. not sure why the docs recommend it... Could you try removing `async` on your `redirect` callback config?

Not sure about 3, and 4. :thinking:

**Comment by zaidhuda** [comment] 2021-09-24 12:10
Oh no. It is in GET 😭 

Is there anything I can do while waiting for the fix to be accepted?

Removing `async` from `redirect` don't seem to do anything.

**Comment by balazsorban44** [comment] 2021-09-24 12:18
As said, I'm not sure why it would result in a crash. 🙄   could you create a proper reproduction so I could debug locally?

**Comment by zaidhuda** [comment] 2021-09-24 12:52
I created [an app with similar setup](https://github.com/zaidhuda/next-auth-esri) and it gives 2 different results based on the OAuth server.

1. With the real ArcGIS OAuth, the failure callback includes `state` param and the server doesn't crash.
2. Using custom ArcGIS OAuth provided by our client, the failure callback doesn't include `state` param and it crashes the server.

**Comment by balazsorban44** [comment] 2021-09-24 12:59
thanks , I'll have a look!

**Comment by balazsorban44** [comment] 2021-09-25 12:35
After some local testing, and reading their docs, I can see that ArcGIS is OIDC compliant, which is much better supported in our v4 version.

Your config would become much simpler as well:

```js
{
  id: 'esri',
  name: 'Esri',
  type: 'oauth',
  wellKnown: "https:/[IdPdomain]/.well-known/openid-configuration"
  clientId: process.env.ARCGIS_CLIENT_ID,
  clientSecret: process.env.ARCGIS_CLIENT_SECRET,
  async profile(_profile, tokens) {
    ...
  },
}
```

https://doc.arcgis.com/en/arcgis-online/administer/openid-connect-logins.htm

I would try to see if migrating would solve the problem for you.

https://next-auth.js.org/getting-started/upgrade-v4

**Comment by zaidhuda** [comment] 2021-09-25 13:12
I did try upgrading before, but the database changes made it hard. I'll try again if that's my only option now.

Thank you for looking into this.

**Comment by balazsorban44** [comment] 2021-09-25 13:20
I tried reproducing the problem with v3 as well, but I didn't manage to crash the server, like you mentioned. :sweat_smile:

We should still work out #1820 to handle errors on GET requests, but this should be resulting in a server crash.

In any way, that bugfix will probably be added in v4 as well, not in v3. I stopped working on v3 to be able to focus on the new version.

If you had problems with the migration to v4, just open an issue/discussion in https://github.com/nextauthjs/adapters

Since the described problem could not be reproduced, I'll close this.

**Closed by balazsorban44** 2021-09-25 13:20 UTC
Labels: bug
