### ISSUE TITLE
Middleware redirect not working with Next 12.2.2

### ISSUE THREAD

**Issue by thejessewinton** [nextauthjs/next-auth#4999] opened 2022-07-22 16:33 UTC
### Question 💬

I'm trying to get `withAuth` working correctly with my middleware. Using the boilerplate withAuth is redirecting to the correct path:

```
import { withAuth } from 'next-auth/middleware';

const middleware = withAuth({
  pages: {
    signIn: '/sign-in',
  },
});

export default middleware;
```

When I'm not signed in it redirects to `/sign-in`, but the page is blank, and the console is showing this error:

```
react-refresh.js:1 Uncaught SyntaxError: Unexpected token '<'
webpack.js:1 Uncaught SyntaxError: Unexpected token '<'
main.js:1 Uncaught SyntaxError: Unexpected token '<'
_app.js:1 Uncaught SyntaxError: Unexpected token '<'
sign-in.js:1 Uncaught SyntaxError: Unexpected token '<'
_buildManifest.js:1 Uncaught SyntaxError: Unexpected token '<'
_ssgManifest.js:1 Uncaught SyntaxError: Unexpected token '<'
```

If I visit `/sign-in` directly, without being redirected there from middleware it renders the page correctly. 

### How to reproduce ☕️

This is my `middleware.ts` that sits next to my `pages` directory, following the new syntax for middleware outlined in the documentation for middleware with Next 12.

```
import { withAuth } from 'next-auth/middleware';

const middleware = withAuth({
  pages: {
    signIn: '/sign-in',
  },
});

export default middleware;
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment] 2022-07-22 17:33
duplicate of #4848

**Closed by balazsorban44** 2022-07-22 17:33 UTC
Labels: question
