### ISSUE TITLE
Supabase Adapter type mismatch

### ISSUE THREAD

**Issue by rtman** [nextauthjs/next-auth#7862] opened 2023-06-22 16:46 UTC
### Adapter type

@auth/supabase-adapter

### Environment

  System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M2
    Memory: 133.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 3.3.1 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 113.1.51.114
    Chrome: 114.0.5735.133
    Safari: 15.6
    
    "@auth/supabase-adapter": "0.1.2",
    "next": "13.1.1",
    "next-auth": "4.22.1",

### Reproduction URL

N/A

### Describe the issue

```
export const authOptions: AuthOptions = {
  adapter: SupabaseAdapter({
    secret: appConfig.SUPABASE_SERVICE_KEY,
    url: appConfig.SUPABASE_URL,
  }),
  providers: [
    GoogleProvider({
      clientId: appConfig.GOOGLE_CLIENT_ID,
      clientSecret: appConfig.GOOGLE_CLIENT_SECRET,
    }),
  ],
};


export default NextAuth(authOptions);
```

```
Type 'Adapter' is not assignable to type 'Adapter<boolean> | undefined'.
  Type 'Adapter' is not assignable to type 'DefaultAdapter & { createVerificationToken: (verificationToken: VerificationToken) => Awaitable<VerificationToken | null | undefined>; useVerificationToken: (params: { ...; }) => Awaitable<...>; }'.
    Type 'Adapter' is not assignable to type 'DefaultAdapter'.
      Types of property 'createUser' are incompatible.
        Type '((user: Omit<AdapterUser, "id">) => Awaitable<AdapterUser>) | undefined' is not assignable to type '(user: Omit<AdapterUser, "id">) => Awaitable<AdapterUser>'.
          Type 'undefined' is not assignable to type '(user: Omit<AdapterUser, "id">) => Awaitable<AdapterUser>'.ts(2322)
types.d.ts(106, 5): The expected type comes from property 'adapter' which is declared here on type 'AuthOptions'
```

### How to reproduce

Try to use supabase adapter as shown above and see the type error.

### Expected behavior

There should be no type issue when defining the adapter

**Comment by balazsorban44** [comment] 2023-06-24 08:28
Duplicate of #7727. see an explanation here https://github.com/nextauthjs/next-auth/issues/7727#issuecomment-1577107093

**Closed by balazsorban44** 2023-06-24 08:28 UTC
Labels: adapters, triage, supabase
