### ISSUE TITLE
Search result not showing anything

### ISSUE THREAD

**Issue by Himasnhu-AT** [nextauthjs/next-auth#7998] opened 2023-07-10 05:40 UTC
### Environment

System:
OS: Macbook Air, 13.4.1 (22F82)
CPU: M1 chip
Memory: 2.3 GB / 7.8 GB

Binaries:
Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
pnpm: 7.23.0 - ~/.nvm/versions/node/v18.12.0/bin/pnpm

Browsers:
Brave Browser: v1.52.130

### Reproduction URL

https://authjs.dev/search/

### Describe the issue

The search on `search bar` in Nav-Bar of all pages show **x search results**. when you click on it, you are redirected to [https://authjs.dev/](https://authjs.dev/), which shows 0 results present.

### How to reproduce

On [home page](https://authjs.dev/), go to NAV-BAR's search, their type anything, lets say 'encrypt', at bottom it'll show you `**28 search results**`. Click on it.

You are redirected to [https://authjs.dev/search?q=encrypt](https://authjs.dev/search?q=encrypt), where their it shows no result present.

### Expected behavior

It should show the 28 results present.

**Comment by Himasnhu-AT** [comment] 2023-07-10 05:42
If possible, i would like to work on this issue. According to me, the third party integration of ALGOLIA is not setup'ed properly

**Comment by balazsorban44** [comment] 2023-07-10 19:52
duplicate of #7282

**Closed by balazsorban44** 2023-07-10 19:52 UTC
Labels: triage
