### ISSUE TITLE
Module parse failed: Identifier 'NextResponse' has already been declared (3:6)

### ISSUE THREAD

**Issue by bartheexplorer** [nextauthjs/next-auth#7660] opened 2023-05-27 08:59 UTC
### Question 💬

Error in nextjs 13.4.4

### How to reproduce ☕️

Module parse failed: Identifier 'NextResponse' has already been declared (3:6)
| "use strict";
| const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;
> const NextResponse = require("next/dist/server/web/spec-extension/response").NextResponse;

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by rahmat-dev** [comment] 2023-05-28 04:28
I have the same issue, I use the 13.4.2 version with T3 Stack.

**Comment by codinesh** [comment] 2023-05-29 05:24
I am facing this issue too. Is there any workaround to fix this?

**Comment by rafanami** [comment] 2023-05-29 11:12
Same issue here. Is there a workaround for the issue?

**Comment by jerodfritz** [comment] 2023-05-29 18:09
I have this error in next 13.4.4 but not in 13.4.3 my middleware.ts file is the following:

```typescript
export { default } from "next-auth/middleware"

export const config = {
  matcher: [
    "/account",
    "/account/:path*",
    "/dashboard",
    "/dashboard/:path*",
    "/play",
    "/play/:path*",
    "/profile",
    "/settings",
  ],
}
```

**Comment by balazsorban44** [comment] 2023-05-29 18:54
Duplicate of #7659

**Closed by balazsorban44** 2023-05-29 18:54 UTC
Labels: question, incomplete

**Comment by anik-hossain** [comment] 2023-06-01 09:23
@jerodfritz thanks man

**Comment by anik-hossain** [comment] 2023-06-01 09:24
> I have this error in next 13.4.4 but not in 13.4.3 my middleware.ts file is the following:
> 
> ```ts
> export { default } from "next-auth/middleware"
> 
> export const config = {
>   matcher: [
>     "/account",
>     "/account/:path*",
>     "/dashboard",
>     "/dashboard/:path*",
>     "/play",
>     "/play/:path*",
>     "/profile",
>     "/settings",
>   ],
> }
> ```

thanks

**Comment by lucasfranzolin** [comment] 2023-06-17 20:15
> I have this error in next 13.4.4 but not in 13.4.3 my middleware.ts file is the following:
> 
> ```ts
> export { default } from "next-auth/middleware"
> 
> export const config = {
>   matcher: [
>     "/account",
>     "/account/:path*",
>     "/dashboard",
>     "/dashboard/:path*",
>     "/play",
>     "/play/:path*",
>     "/profile",
>     "/settings",
>   ],
> }
> ```

same issue here

**Comment by huyc27** [comment] 2023-06-21 04:08
> I have this error in next 13.4.4 but not in 13.4.3 my middleware.ts file is the following:
> 
> ```ts
> export { default } from "next-auth/middleware"
> 
> export const config = {
>   matcher: [
>     "/account",
>     "/account/:path*",
>     "/dashboard",
>     "/dashboard/:path*",
>     "/play",
>     "/play/:path*",
>     "/profile",
>     "/settings",
>   ],
> }
> ```

+1 same

**Comment by BHuamanCallupe** [comment] 2023-07-04 06:13
solution: back to next version 13.4.3 works for me.

**Comment by samieteq** [comment] 2023-07-04 09:48
I encounter same issues too, I just have to install the previous of nextjs (next@13.4.3), and it work.
