### ISSUE TITLE
Custom Login Page Error Handling?

### ISSUE THREAD

**Issue by Lightgaming** [nextauthjs/next-auth#1192] opened 2021-01-24 22:22 UTC
I have a **custom login page** that uses the signIn method (LDAP Credential Provider) which works perfectly. 
**When the wrong credentials are entered the user is redirected to an Error page, which I don't want.**
I don't want this error redirect.
![image](https://user-images.githubusercontent.com/18364007/105645239-a8820580-5e9a-11eb-872d-b662eeb269b0.png)

Is there a way to use the signIn method like this?:

![image](https://user-images.githubusercontent.com/18364007/105645166-2d205400-5e9a-11eb-8582-a3956d20408b.png)

Or maybe something similar, so I can handle the error myself?

**Comment by balazsorban44** [comment] 2021-01-24 22:33
You could try creating a custom error page as well? you will receive the type of error as a query parameter to handle the different cases

**Comment by Lightgaming** [comment] 2021-01-25 07:32
I could do that, this would solve my redirect problem since it's just a route, but how would I get the error message back in my React Login component? 

I want it that way: When the user clicks login and the creds are wrong I get the error in my React Logic and show some nicely formatted error message in the form, so the user knows what's wrong

**Comment by balazsorban44** [comment] 2021-01-25 23:02
Duplicate of #989

**Closed** 2021-01-25 23:02 UTC
Labels: duplicate, help wanted, question

**Comment by balazsorban44** [comment] 2021-01-31 00:57
@Lightgaming follow #1219 :wink:

**Comment by Taha-mlaiki** [comment] 2024-05-11 11:44
@Lightgaming  did you resolve your problem , because I'm facing it to right now
??

**Comment by Lightgaming** [comment] 2024-05-11 11:48
@Taha-mlaiki unfortunately I don't really know. It was a school project and I don't have access to the code anymore
