### ISSUE TITLE
Firebase Adapter not working

### ISSUE THREAD

**Issue by ifeoluwaayo** [nextauthjs/next-auth#5029] opened 2022-07-26 14:51 UTC
### Adapter type

@next-auth/firebase-adapter

### Environment

Chrome browser, Windows, Node > 14

### Reproduction URL

https://github.com/ifeoluwaayo/culrica

### Describe the issue

![Screenshot (52)](https://user-images.githubusercontent.com/79877061/181037544-c6da5a5f-c92b-4dd6-b817-11b35d6c97b5.png)

FirebaseError: Firebase: Firebase App named '[DEFAULT]' already exists with different options or config (app/duplicate-app).

Despite following all that's said in the documentation I still have this error

### How to reproduce

clone my repo or just follow along with the documentation

### Expected behavior

It should show me my providers but I get an error message instead

**Comment by ifeoluwaayo** [comment] 2022-07-26 14:51
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz
    Memory: 1.79 GB / 7.93 GB
  Binaries:
    Node: 16.14.0 - c:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\node_modules\.bin\yarn.CMD
    npm: 8.5.5 - c:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.71)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    next: 12.2.2 => 12.2.2
    next-auth: ^4.10.2 => 4.10.2
    react: 18.2.0 => 18.2.0


  npmPackages:
    @next-auth/firebase-adapter: ^1.0.1 => 1.0.1

**Comment by balazsorban44** [comment] 2022-07-26 22:57
Duplicate of #4927

**Closed by balazsorban44** 2022-07-26 22:57 UTC
Labels: adapters, firebase, triage
