### ISSUE TITLE
Typing error | NextAuth

### ISSUE THREAD

**Issue by Pedromdsn** [nextauthjs/next-auth#8080] opened 2023-07-18 16:53 UTC
### Environment

  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600 6-Core Processor
    Memory: 11.51 GB / 15.57 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.16.0 - /run/user/1000/fnm_multishells/15482_1689699113742/bin/node
    Yarn: 1.22.19 - /run/user/1000/fnm_multishells/15482_1689699113742/bin/yarn
    npm: 9.5.1 - /run/user/1000/fnm_multishells/15482_1689699113742/bin/npm

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

The typings are not available even in the official repository
![image](https://github.com/nextauthjs/next-auth/assets/57453260/e36d271a-a196-4b2c-8149-3957a48f8c35)

### How to reproduce

Download the repository, and install the dependencies

### Expected behavior

It should not give a typing error.

**Comment by xterikatx** [comment] 2023-07-18 17:17
same error here.

**Comment by ricardobelfort** [comment] 2023-07-18 17:33
Same error here.

![image](https://github.com/nextauthjs/next-auth/assets/16720770/2f0f99f6-233a-44d3-8615-3834adbbb63b)

Is there any solution?

**Comment by RamonCP** [comment] 2023-07-18 19:40
same error here

**Comment by kriswill** [comment] 2023-07-18 19:50
This seems to be broken as of `v4.22.2` where `v4.22.1` was working.  from my `yarn.lock`:
```
next-auth@^4.22.1:
  version "4.22.1"
  resolved "https://registry.yarnpkg.com/next-auth/-/next-auth-4.22.1.tgz#1ea5084e38867966dc6492a71c6729c8f5cfa96b"
  integrity sha512-NTR3f6W7/AWXKw8GSsgSyQcDW6jkslZLH8AiZa5PQ09w1kR8uHtR9rez/E9gAq/o17+p0JYHE8QjF3RoniiObA==
  dependencies:
    "@babel/runtime" "^7.20.13"
    "@panva/hkdf" "^1.0.2"
    cookie "^0.5.0"
    jose "^4.11.4"
    oauth "^0.9.15"
    openid-client "^5.4.0"
    preact "^10.6.3"
    preact-render-to-string "^5.1.19"
    uuid "^8.3.2"
```

**Comment by YannisHaismann** [comment] 2023-07-18 20:24
Same here

**Comment by balazsorban44** [comment] 2023-07-18 20:47
duplicate of #8078

**Closed by balazsorban44** 2023-07-18 20:47 UTC
Labels: triage
