### ISSUE TITLE
NextAuth Google signin redirects to localhost on vercel deployment when "Automatically expose System Environment Variables" is checked

### ISSUE THREAD

**Issue by kirtan-desai** [nextauthjs/next-auth#7289] opened 2023-04-17 16:50 UTC
### Environment

"next": "13.3.0"
 "next-auth": "4.22.0"

### Reproduction URL

Private repo

### Describe the issue

I tried setting and unsetting `NEXTAUTH_URL` environment variable but still it was redirecting to localhost. Finally, I unchecked `Automatically expose System Environment Variables` option on Vercel and set `NEXTAUTH_URL` environment variable and it started working correctly.

### How to reproduce

NextAuth code:
```js
import { signIn } from "next-auth/react";

export default function Login() {
    return <button onClick={() => signIn("google")}>Login</button>;
}
```

Deploy to Vercel

Make sure `Automatically expose System Environment Variables` is set

Try setting `NEXTAUTH_URL` and also unsetting `NEXTAUTH_URL`. NextAuth will redirect to localhost for both.

### Expected behavior

NextAuth should redirect to `NEXTAUTH_URL` env variable domain or to domain given by vercel if `NEXTAUTH_URL` is not set. It shouldnt redirect to localhost.

**Comment by mateussmohamed** [comment] 2023-04-17 19:59
Same behavior here with Github signin

**Comment by balazsorban44** [comment] 2023-04-17 20:00
Likely a duplicate https://github.com/nextauthjs/next-auth/issues/7229 hard to tell without a reproduction.

**Comment by mateussmohamed** [comment] 2023-04-17 20:12
@kirtan-desai I disabled the **Automatically expose [System Environment Variables](https://vercel.com/docs/environment-variables#system-environment-variables)** option on **Environment Variables** and manually set the `VERCEL_ENV` and `NEXTAUTH_UR` on my project and worked.

I used: Next@13.3.0 with app dir and route handlers, and next-auth@4.22.0

**Comment by balazsorban44** [comment] 2023-04-18 08:31
@mateussmohamed based on that info, it's indeed a duplicate of #7229, so closing.

**Closed by balazsorban44** 2023-04-18 08:31 UTC
Labels: incomplete, triage

**Comment by dipayanmaji** [comment] 2024-06-23 04:38
previously I written this at .env file:
AUTH_SECRET = ...
AUTH_URL = ...

but after getting error I changed this:
NEXTAUTH_SECRET = ...
NEXTAUTH_URL = ...


and its works fine :)
