### ISSUE TITLE
Possibility to pass state to OAuth provider and get it back from the callback URL

### ISSUE THREAD

**Issue by wowczarczyk** [nextauthjs/next-auth#7190] opened 2023-04-07 17:40 UTC
### Description 📓

According to the OpenID spec:

https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.1

it should be possible to pass custom state when calling the `authorize` endpoint and get this state back in the callback URL.

I think this is planned per this comment in the [check.ts](https://github.com/nextauthjs/next-auth/blob/6c07331cc53abe45c644308af6b6f2de29fdae2e/packages/core/src/lib/oauth/checks.ts#L82) 

### How to reproduce ☕️

<not needed>

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by wowczarczyk** [comment] 2023-04-07 17:44
Hmm, I think this is managed here already:

https://github.com/nextauthjs/next-auth/issues/5727
https://github.com/nextauthjs/next-auth/pull/6726

**Comment by balazsorban44** [comment] 2023-04-13 12:27
Indeed, duplicate of #5727, so closing in favor.

**Closed by balazsorban44** 2023-04-13 12:27 UTC
Labels: enhancement, triage
