### ISSUE TITLE
Wrong `reqWithEnvUrl` wrapper from `NextRequest` to `Request` missed `cookies` of NextRequest.

### ISSUE THREAD

**Issue by hyperse-net** [nextauthjs/next-auth#9237] opened 2023-11-25 01:24 UTC
### Environment

next-auth/src/lib/env.ts

```ts

/** If `NEXTAUTH_URL` or `AUTH_URL` is defined, override the request's URL. */
export function reqWithEnvUrl(req: NextRequest): NextRequest {
  const url = process.env.AUTH_URL ?? process.env.NEXTAUTH_URL
  if (!url) return req
  const nonBase = req.nextUrl.href.replace(req.nextUrl.origin, "")
  const base = new URL(url).origin
  // REVIEW: Bug in Next.js?: TypeError: next_dist_server_web_exports_next_request__WEBPACK_IMPORTED_MODULE_0__ is not a constructor
  // return new NextRequest(new URL(nonBase, base), req)
  const _url = new URL(nonBase, base)
  const _req = new Request(_url, req) as any
  _req.nextUrl = _url
  return _req
}


```

while we use `auth` as middleware it will lose `cookies` after transform via above `reqWithEnvUrl`

```ts
async function handleAuth(
  args: Parameters<NextMiddleware | AppRouteHandlerFn>,
  config: NextAuthConfig,
  userMiddlewareOrRoute?: NextAuthMiddleware | AppRouteHandlerFn
) {
  // this line will lose `cookies` from next request.
  const request = reqWithEnvUrl(args[0])
  const sessionResponse = await getSession(request.headers, config)
  const auth = await sessionResponse.json()

```

```

  const _req = new Request(_url, req) as any 
 this line will lose `cookies`
```

if we use `next-auth` as next middleware this will break other middlewares if they depenpends `req.cookies`

### Reproduction URL

https://github.com/hyperse-io/next-trpc/tree/main/packages/next-demo

### Describe the issue

next-auth/src/lib/env.ts

```ts

/** If `NEXTAUTH_URL` or `AUTH_URL` is defined, override the request's URL. */
export function reqWithEnvUrl(req: NextRequest): NextRequest {
  const url = process.env.AUTH_URL ?? process.env.NEXTAUTH_URL
  if (!url) return req
  const nonBase = req.nextUrl.href.replace(req.nextUrl.origin, "")
  const base = new URL(url).origin
  // REVIEW: Bug in Next.js?: TypeError: next_dist_server_web_exports_next_request__WEBPACK_IMPORTED_MODULE_0__ is not a constructor
  // return new NextRequest(new URL(nonBase, base), req)
  const _url = new URL(nonBase, base)
  const _req = new Request(_url, req) as any
  _req.nextUrl = _url
  return _req
}


```

while we use `auth` as middleware it will lose `cookies` after transform via above `reqWithEnvUrl`

```ts
async function handleAuth(
  args: Parameters<NextMiddleware | AppRouteHandlerFn>,
  config: NextAuthConfig,
  userMiddlewareOrRoute?: NextAuthMiddleware | AppRouteHandlerFn
) {
  // this line will lose `cookies` from next request.
  const request = reqWithEnvUrl(args[0])
  const sessionResponse = await getSession(request.headers, config)
  const auth = await sessionResponse.json()

```
if we use `next-auth` as next middleware this will break other middlewares if they depenpends `req.cookies`

### How to reproduce

see issue description please

### Expected behavior

```
async function handleAuth(
  args: Parameters<NextMiddleware | AppRouteHandlerFn>,
  config: NextAuthConfig,
  userMiddlewareOrRoute?: NextAuthMiddleware | AppRouteHandlerFn
) {
  const request = reqWithEnvUrl(args[0])
```

the `request` is a standard `next request ` rather than a `Reuqest`

**Comment by balazsorban44** [comment] 2024-01-25 03:25
duplicate of #9045

**Closed by balazsorban44** 2024-01-25 03:25 UTC
Labels: bug, triage
