### ISSUE TITLE
Facebook returns { message: 'expected 200 OK, got: 400 Bad Request' }

### ISSUE THREAD

**Issue by pooriyapfn** [nextauthjs/next-auth#4694] opened 2022-06-09 09:27 UTC
### Question 💬

After returning the page from Facebook, it shows this error.
It's very interesting that it works properly in development mode and on localhost, but it shows this message when its live.

`
[next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error expected 200 OK , got: 400 Bad Request {
 error: {
 message: 'expected 200 OK, got: 400 Bad Request',
stack: 'OPError: expected 200 OK, got: 400 Bad Request\n' + ....
`

I would be very grateful if you could tell where the problem comes from.

### How to reproduce ☕️

`
FacebookProvider({
        clientId: process.env.FACEBOOK_CLIENT_ID,
        clientSecret: process.env.FACEBOOK_CLIENT_SECRET,
      }),
`

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment] 2022-06-10 13:50
This seems to be a recurring issue with Facebook, which seems to be fixed over time. :shrug: 

Duplicate of: https://github.com/nextauthjs/next-auth/issues/3711

**Closed by balazsorban44** 2022-06-10 13:50 UTC
Labels: question
