### ISSUE TITLE
Impossible to get Auth State on route handler when fetching from server component

### ISSUE THREAD

**Issue by Serpentarius13** [nextauthjs/next-auth#7545] opened 2023-05-14 01:25 UTC
### Environment

 System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 5.44 GB / 15.95 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.42)    
    Internet Explorer: 11.0.19041.1566

### Reproduction URL

no url

### Describe the issue

When fetching data from route handler in server component in app directory, neither `getServerSession` or `getToken` work and always result as null. 

### How to reproduce

My code: 
route.ts

```
export async function GET(request: Request | any) {
  try {
    const session = await getServerSession(authOptions);
    // null

    const tokenSession = await getToken({ req: request, raw: true });
    // null

    if (!session) return makeUnauthorizedError();
    const notes = await getAllNotes(session.user.id);

    return NextResponse.json(notes);  }
catch (error) {
    console.log(error);
    return makeBadRequestError("Error getting notes");
}
```

  
page.tsx

 ```
async function getNotes(): Promise<NoteType[] | undefined> {
  try {
    const { data } = await axios.get(`${baseUrl}/api/note`);

    console.log(data);

    return data;
  } catch (error) {

    console.log(error)
  }
}

export default async function Notes() {
  const notes = await getNotes();
  if (!notes) {
    //...
  }
  return (
    <MainLayout title="Notes">
      <ul className="grid w-full grid-cols-3 gap-[2rem]">
        {notes?.map((note) => (
          <Note key={note.id} {...note} />
        ))}
        <AddNote />
      </ul>
    </MainLayout>
  );
}
```

### Expected behavior

either getServerSession(authOptions) or getToken() should provide auth state in route handler

**Comment by balazsorban44** [comment] 2023-05-14 10:57
Duplicate of https://github.com/nextauthjs/next-auth/issues/7423#issuecomment-1531064680

**Closed by balazsorban44** 2023-05-14 10:57 UTC
Labels: triage
