### ISSUE TITLE
Provider SVG Image Links Broken

### ISSUE THREAD

**Issue by nofurtherinformation** [nextauthjs/next-auth#6341] opened 2023-01-09 19:15 UTC
### Provider type

Facebook, Google

### Environment

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 56.36 GB / 58.86 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.3.1 - ~/github/osl-hub/node_modules/.bin/yarn
    npm: 9.1.2 - ~/.nvm/versions/node/v18.12.1/bin/npm

### Reproduction URL

https://sveltekit-auth-example.vercel.app/auth/signin

### Describe the issue

The current latest release links to SVGs in root > packages > next-auth > provider-logos > {provider}.svg (eg. `https://raw.githubusercontent.com/nextauthjs/next-auth/main/packages/next-auth/provider-logos/google.svg`), but this is no longer the correct path on main.

Sign in page appears like this:
![image](https://user-images.githubusercontent.com/10041771/211388988-3327936f-5ad8-4b03-bdcc-03c562440bef.png)

### How to reproduce

Run nextauth examples with Svelte on latest, or any legacy application.

### Expected behavior

SVG images pulled from `https://raw.githubusercontent.com/nextauthjs/next-auth/main/packages/next-auth/provider-logos/{provider}.svg` appear.

**Comment by balazsorban44** [comment] 2023-01-09 22:33
Duplicate of #6313. I'll create a release this week and the issue should be fixed. 🙏 Workaround is to manually pass the full logo URL to the provider's configuration under `style.logo`

example: https://authjs.dev/img/providers/facebook.svg

**Closed by balazsorban44** 2023-01-09 22:33 UTC
Labels: providers, triage

**Comment by nofurtherinformation** [comment] 2023-01-09 23:09
Thanks @balazsorban44 !
