### ISSUE TITLE
typeorm : MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by satishSKY** [nextauthjs/next-auth#3992] opened 2022-02-17 09:11 UTC
### Environment

Getting error in `"next-auth": "^3.23.1"`

### Reproduction URL

I am using `"next-auth": "^3.23.1"` version and suddenly it stop working after deployment

### Describe the issue

Error: Cannot find module '/home/user/Documents/projects/web.app/node_modules/typeorm/util/StringUtils'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
    at resolveExports (node:internal/modules/cjs/loader:482:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.mod._resolveFilename (/home/gwl/Documents/galaxy/gwl-projects/web.amplify/node_modules/next/dist/build/webpack/require-hook.js:4:1784)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/user/Documents/user/projects/web.app/node_modules/next-auth/node_modules/@next-auth/typeorm-legacy-adapter/dist/lib/naming-strategies.js:10:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/gwl/Documents/user/projects/web.app/node_modules/typeorm/package.json'

### How to reproduce

I am using `"next-auth": "^3.23.1"` version and suddenly it stops working after deployment

### Expected behavior

I am using `"next-auth": "^3.23.1"` version and suddenly it stop working after deployment

**Comment by satishSKY** [comment] 2022-02-17 09:15
Anyone can help, how I can resolve this?

**Comment by mike-webdev** [comment] 2022-02-17 09:50
I'm also having this problem.

**Comment by Gawdfrey** [comment] 2022-02-17 09:50
I am also facing this issue. It seems to be introduced after bumping follow-redirects from 1.14.7 to 1.14.8. I am using next-auth: 3.27.1. It works locally but when deploying it fails.

**Comment by wazcov** [comment] 2022-02-17 09:52
We just got this, this morning

**Comment by JAWorsfold** [comment] 2022-02-17 09:57
Ditto

**Comment by wazcov** [comment] 2022-02-17 10:10
Can anyone else with this issue post logs? See if it's the same as ours

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './util/StringUtils' is not defined by "exports" in /var/app/current/node_modules/typeorm/package.json`

`at Object.<anonymous> (/var/app/current/node_modules/@next-auth/typeorm-legacy-adapter/dist/lib/naming-strategies.js:10:20)`

**Comment by satishSKY** [comment] 2022-02-17 10:10
> We just got this, this morning

Yes, same here

**Comment by XerxesAkaEnno** [comment] 2022-02-17 10:36
Yes, I also can confirm I get this error on every Version 3.

**Comment by Gawdfrey** [comment] 2022-02-17 10:39
Our errors
`
}
--
  |   | path: '/usr/src/app/node_modules/typeorm/package.json'
  |   | code: 'MODULE_NOT_FOUND',
  |   | at Object.<anonymous> (/usr/src/app/node_modules/@next-auth/typeorm-legacy-adapter/dist/lib/naming-strategies.js:10:20) {
  |   | at require (node:internal/modules/cjs/helpers:102:18)
  |   | at Module.require (node:internal/modules/cjs/loader:1005:19)
  |   | at Function.Module._load (node:internal/modules/cjs/loader:778:27)
  |   | at Function.mod._resolveFilename (/usr/src/app/node_modules/next/dist/build/webpack/require-hook.js:96:28)
  |   | at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
  |   | at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
  |   | at resolveExports (node:internal/modules/cjs/loader:482:14)
  |   | at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
  |   | at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
  |   | Error: Cannot find module '/usr/src/app/node_modules/typeorm/util/StringUtils'
`

**Comment by satishSKY** [comment] 2022-02-17 11:01
When I have used the previous `package-lock.json` file it was worked.

But after deleting the old one it is not working get the same error

**Comment by XerxesAkaEnno** [comment] 2022-02-17 11:21
Hey guy,

I fixed the issue by doing the following:



1. clearing up all modules (`rm -rf node_modules/`)
2. run `npm install`
3. run `npm remove typeorm`
4. run `npm install typeorm@0.2.41`

**Comment by matha-io** [comment] 2022-02-17 11:27
I also have this issue, and I don't use `typeorm` so cannot remove / update it ! Should it be fixed using `peerDependencies` ?

**Comment by XerxesAkaEnno** [comment] 2022-02-17 11:39
Hey @matha-io ,

I also don't have it directly implemented. In my case it was an dependency of next-auth (this GitHub repo).
But the solution which I provided worked for that. It removed the downloaded dependency of next-auth and replaced it with the new version. Did you gave it a try?

**Comment by matha-io** [comment] 2022-02-17 11:53
Nah it doesn't work for me, `yarn remove typeorm` returns `This module isn't specified in a package.json file.`
I will try other workaround ^^'

**Comment by XerxesAkaEnno** [comment] 2022-02-17 12:00
Hey @matha-io,

I checked up again.

What you can also try is following:

1. Add to the package.json following: `"typeorm": "^0.2.42",`
The package wouldn't be downloaded again because an dependency already had it.

2. After that try to do steps 3 & 4.

Would like to hear back if this works.

**Comment by XerxesAkaEnno** [comment] 2022-02-17 12:10
Add:

The last extra steps a provided works also on my pipeline. So this should be the workaround.

**Comment by matha-io** [comment] 2022-02-17 12:16
Thanks @XerxesAkaEnno I tried this with no luck.
The thing is, I use yarn & workspaces ! Finally managed to force versioning with : 

```
  "resolutions": {
    "typeorm": "0.2.41"
  }
```

In the workspace `package.json` !

**Comment by XerxesAkaEnno** [comment] 2022-02-17 12:21
@matha-io Perfect. So we provided two options as workaround as long as they take to fix this problem.
Good job :)

**Comment by XerxesAkaEnno** [comment] 2022-02-17 12:23
@satishSKY can you rename the Issue please, so everyone could easily see this post. 😄 And its not related to api/auth/session, its related to typeorm.

**Comment by kmokrzycki** [comment] 2022-02-17 12:47
This fixed our issue to 👍

**Comment by Gawdfrey** [comment] 2022-02-17 12:49
> Thanks @XerxesAkaEnno I tried this with no luck. The thing is, I use yarn & workspaces ! Finally managed to force versioning with :
> 
> ```
>   "resolutions": {
>     "typeorm": "0.2.41"
>   }
> ```
> 
> In the workspace `package.json` !

Thanks for the fix @matha-io and @XerxesAkaEnno !

**Comment by satishSKY** [comment] 2022-02-17 13:19
> Thanks @XerxesAkaEnno I tried this with no luck. The thing is, I use yarn & workspaces ! Finally managed to force versioning with :
> 
> ```
>   "resolutions": {
>     "typeorm": "0.2.41"
>   }
> ```
> 
> In the workspace `package.json` !

Thanks @XerxesAkaEnno

**Comment by balazsorban44** [comment] 2022-02-17 14:18
Hi everyone, v3 is an unmaintained version of NextAuth.js,

(First element in the docs when you try to see v3:
![image](https://user-images.githubusercontent.com/18369201/154499388-bef6f29e-2e3a-48a0-8095-bb7c5dd0b252.png)
)


First of all, please [upgrade to v4](https://next-auth.js.org/getting-started/upgrade-v4)! The issue seems to be that TypeORM recently released a new version, which broke in v3: https://github.com/typeorm/typeorm/releases

You can use the above-mentioned techniques to lock down the version to `0.2.41`, which is the version that seems to be working.

This definitely won't be an issue for those using v4 with no or a different adapter, since v4 is modular and requires you to explicitly install an adapter and its ORM. See https://next-auth.js.org/adapters/typeorm#usage. When using v4 and TypeORM we will check if v4 is affected and will push out a patch release if necessary. cc @ndom91 @ThangHuuVu

Also as the adapter name in the docs and other places suggests (`typeorm-legacy`), our TypeORM adapter was less likely to be dealt with since it showed signs of becoming unmaintained for a very long time. See this post from the maintainer: [**Future of TypeORM #3267**](https://github.com/typeorm/typeorm/issues/3267).

This is **not** pick on the TypeORM author. Maintaining a popular project, especially with no or little help is hard and can burn a developer out.

> We are working full-time on TypeORM for almost three years. That’s why we have such a powerful and really amazing ORM. And this time wasn't funded or sponsored by anybody except our core developers.

They wrote this *4 years ago*! I only hope the situation has changed, and that if people/businesses are actively relying on it they decide to fund [their project](https://opencollective.com/typeorm)

I have to express my own concerns here that besides many people jumping on this thread immediately with "same here", *nobody* decided to create a reproduction, which would have made tracking down the issue much harder, and will naturally result in a slower response if we did not know what the issue was. :disappointed:

**Comment by XerxesAkaEnno** [comment] 2022-02-17 14:21
@balazsorban44 I would update to V4, but it seems like I can't do it from now. Using extra parameters for authorizations and tokens seems always to fail or not to be pass correctly. With V3 I have no issues.

**Comment by balazsorban44** [comment] 2022-02-17 14:26
@XerxesAkaEnno If you don't know how to upgrade because of documentation issues or a likely bug that you could confirm, you can open a bug report/docs issue about it. If it's specific to your own project, open a question in the discussions instead.

We are very responsive to new issues. :+1:

> Using extra parameters for authorizations 

But this should explain it: https://next-auth.js.org/getting-started/upgrade-v4#providers

**Comment by ThangHuuVu** [comment] 2022-02-18 04:11
Hello all, I'm going to close this issue since `typeorm` closed [their related issue](https://github.com/typeorm/typeorm/issues/8656) (thank you @XerxesAkaEnno for initiating) and released [a new version](https://github.com/typeorm/typeorm/releases/tag/0.2.43) on their end. We suggest you re-install your dependencies to pull their latest version which contains the fix.
cc @balazsorban44

**Closed by ThangHuuVu** 2022-02-18 04:11 UTC
Labels: adapters, typeorm-legacy

**Comment by balazsorban44** [comment] 2022-02-19 00:11
@pleerock Thanks for the confirmation @pleerock, I guess what threw me off last time I researched this was the still open, pinned issue https://github.com/typeorm/typeorm/issues/3267. (Suggestion, either close or update for clarity)

I admittedly did not go deep into all the comments there though, so thank you for re-affirming here that the project is well, and I would like to apologize!

I wish you and your co-maintainers the best, you are doing a great job! :green_heart:
