### ISSUE TITLE
Error while logging in with Azure AD

### ISSUE THREAD

**Issue by Rodeveer** [nextauthjs/next-auth#3627] opened 2022-01-14 09:57 UTC
### Description 🐜

Since today I'm experiencing some issues with the AzureAD provider. The implementation has worked before but suddenly it stopped working and is giving me an error:

```
[next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error id_token not present in TokenSet
```

I've tried to set the `idToken` to `false`. It solves the error but it doesn't fix it, it still doesn't log me in.

### Is this a bug in your own project?

No

### How to reproduce ☕️

Install a new version of the typescript example; Install the Azure AD provider and try to log in.

### Screenshots / Logs 📽

[next-auth][error][OAUTH_CALLBACK_ERROR]
https://next-auth.js.org/errors#oauth_callback_error id_token not present in TokenSet {
  error: {
    message: 'id_token not present in TokenSet',
    stack: 'TypeError: id_token not present in TokenSet\n' +
      '    at Client.validateIdToken (xxx\\next-auth-typescript-example\\node_modules\\openid-client\\lib\\client.js:757:15)\n' +
      '    at Client.callback (xxx\\next-auth-typescript-example\\node_modules\\openid-client\\lib\\client.js:486:18)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
      '    at async oAuthCallback (xxx\\next-auth-typescript-example\\node_modules\\next-auth\\core\\lib\\oauth\\callback.js:112:16)\n' +  
      '    at async Object.callback (xxx\\next-auth-typescript-example\\node_modules\\next-auth\\core\\routes\\callback.js:50:11)\n' +     
      '    at async NextAuthHandler (xxx\\next-auth-typescript-example\\node_modules\\next-auth\\core\\index.js:133:28)\n' +
      '    at async NextAuthNextHandler (xxx\\next-auth-typescript-example\\node_modules\\next-auth\\next\\index.js:20:19)\n' +
      '    at async xxx\\next-auth-typescript-example\\node_modules\\next-auth\\next\\index.js:56:32\n' +
      '    at async Object.apiResolver (xxx\\next-auth-typescript-example\\node_modules\\next\\dist\\server\\api-utils.js:101:9)\n' +      
      '    at async DevServer.handleApiRequest (xxx\\next-auth-typescript-example\\node_modules\\next\\dist\\server\\next-server.js:775:9)'
,
    name: 'TypeError'
  },
  providerId: 'azure-ad',
  message: 'id_token not present in TokenSet'
}

### Environment 🖥

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 18.05 GB / 31.88 GB
  Binaries:
    Node: 14.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.71
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.55)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    next: ^11.0.0 => 11.1.3
    next-auth: ^4.1.0 => 4.1.0
    react: ^17.0.2 => 17.0.2

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by davidchalifoux** [comment] 2022-01-14 14:48
I also just ran into this issue.

**Comment by crhampton1** [comment] 2022-01-14 16:01
Also running into this issue. Can confirm that rolling back to 4.0.6 as @davidchalifoux did resolve the issue and we can log in using Azure AD.

**Comment by balazsorban44** [comment] 2022-01-15 03:15
Azure AD is an OIDC compliant provider, so it should return an id_token. I believe this is a misconfiguration.

Try searching through issues/PRs, this has been asked before, I believe.

**Comment by davidchalifoux** [comment] 2022-01-16 03:13
I just replaced it with a custom provider that's working:
```javascript
{
  id: "azure-ad",
  name: "Azure AD",
  type: "oauth",
  clientId: process.env.AZURE_AD_CLIENT_ID,
  clientSecret: process.env.AZURE_AD_CLIENT_SECRET,
  wellKnown: `https://login.microsoftonline.com/${process.env.AZURE_AD_TENANT_ID}/v2.0/.well-known/openid-configuration`,
  authorization: {
    params: {
      scope: "openid profile email",
    },
  },
  idToken: true,
  async profile(profile, tokens) {
    const profileObject = {
      id: profile.sub,
      name: profile.name,
      email: profile.email,
      image: "",
    };
    // https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0#examples
    const profilePicture = await fetch(
      `https://graph.microsoft.com/v1.0/me/photos/120x120/$value`,
      {
        headers: {
          Authorization: `Bearer ${tokens.access_token}`,
        },
      }
    );
    if (profilePicture.ok) {
      const pictureBuffer = await profilePicture.arrayBuffer();
      const pictureBase64 = Buffer.from(pictureBuffer).toString("base64");
      profileObject.image = `data:image/jpeg;base64, ${pictureBase64}`;
    }

    return profileObject;
  },
},
```

I'll probably send a PR for this once I test it with other users on Monday.
Another issue I ran into with this provider is that it doesn't handle cases when people don't have a profile photo set. I'm working on a fix now.

**Comment by balazsorban44** [comment] 2022-01-16 23:57
I see! So the issue is that we don't include the `openid` scope by default, which I was sure we did :facepalm:

Changing the scope should be enough, `idToken: true` will be inferred when `openid` is present.

**Comment by davidchalifoux** [comment] 2022-01-17 00:34
> I see! So the issue is that we don't include the `openid` scope by default, which I was sure we did 🤦
> 
> Changing the scope should be enough, `idToken: true` will be inferred when `openid` is present.

You're right, it still works. Want me to submit a PR?

**Comment by balazsorban44** [comment] 2022-01-17 00:42
Please do! :pray:

**Closed** 2022-01-17 03:28 UTC
Labels: bug, providers, good first issue
