### ISSUE TITLE
@next-auth/prisma-adapter npm package broken (missing dist directory)

### ISSUE THREAD

**Issue by callumgare** [nextauthjs/next-auth#2290] opened 2021-07-01 03:57 UTC
The latest @next-auth/prisma-adapter package published to NPM (0.5.1) is missing the `dist` directly and thus is completely inoperable. You can check this using unpkg https://unpkg.com/browse/@next-auth/prisma-adapter@0.5.1/ (or by downloading the tarball directly and taking a look inside: https://registry.npmjs.org/@next-auth/prisma-adapter/-/prisma-adapter-0.5.1.tgz)

It looks like this has happened before: https://github.com/nextauthjs/next-auth/issues/1243
Maybe some automated checks should be put in place to stop this from being possible?

**Comment by balazsorban44** [comment] 2021-07-01 17:31
Duplicate of https://github.com/nextauthjs/adapters/issues/159

Please report adapter related issues on the other repo 🙏

**Closed by balazsorban44** 2021-07-01 17:31 UTC
Labels: bug
