### ISSUE TITLE
Email provider on demo app results in an infinite verification in loop on some pages

### ISSUE THREAD

**Issue by DoctorateFR** [nextauthjs/next-auth#6114] opened 2022-12-18 13:45 UTC
### Environment

I would rather not dox myself that specifically sorry
Node 19.3
Latest chrome and firefox tested without any kind of extensions

### Reproduction URL

https://github.com/nextauthjs/next-auth-example

### Describe the issue

Using email provider does not seem to work properly with the next-auth-example.

I have disabled every other provider and simply kept email.

I use a local mailhog server (just a simple smtp testing server) and the emails are sent and received succesfully, the links in them work, but clicking the link that was created by `/signin?callbackUrl=%2Fme` when you click on the `Admin` or `Me` page will just send the email and the link in that email will redirect after verification to the exact same page asking your email to sign in `/signin?callbackUrl=%2Fme`

`/api/auth/callback/email?callbackUrl=http%3A%2F%2Flocalhost%3A3000%2Fme&token=7ce8899c469d5c4937aae30e5b721d9c04ea106988de27e8a95d9110aed9ed07&email=a%40a.a`

### How to reproduce

Run demo app you provide.
Enable email. Disable all others. Database is postgres with prisma with copy pasted everything from your docs, all of this works fine.
Sign in, it "somewhat" works on the home page. (it shows you are signed in and your email address)

**Go to `Admin` and `Me` pages will just ask you to sign in again (even if the home page detects you logged in already) and when you click the verification link in the email you are redirected to the sign in page (infinite loop).**

Also on the `API` tab of the demo the JSON Web Token seems to return `null` which is probably linked.

### Expected behavior

Email provider should behave like all the others.

**Comment by balazsorban44** [comment] 2022-12-18 16:52
Do you have custom pages enabled? please link to a reproduction

**Comment by balazsorban44** [comment] 2022-12-18 16:54
We cannot recreate the issue with the provided information. **Please add a reproduction in order for us to be able to investigate.**

### **Why was this issue marked with the `incomplete` label?**

To be able to investigate, we need access to a reproduction to identify what triggered the issue. We prefer a link to a public GitHub repository ([template](https://github.com/nextauthjs/next-auth-example)), but you can also use a tool like [CodeSandbox](https://codesandbox.io/s/github/nextauthjs/next-auth-example/tree/main) or [StackBlitz](https://stackblitz.com/fork/github/nextauthjs/next-auth-example).

To make sure the issue is resolved as quickly as possible, please make sure that the reproduction is as **minimal** as possible. This means that you should **remove unnecessary code, files, and dependencies** that do not contribute to the issue.

Please test your reproduction against the latest version of NextAuth.js (`next-auth@latest`) to make sure your issue has not already been fixed.

### **I added a link, why was it still marked?**

Ensure the link is pointing to a codebase that is accessible (e.g. not a private repository). "[example.com](http://example.com/)", "n/a", "will add later", etc. are not acceptable links -- we need to see a public codebase. See the above section for accepted links.

### **What happens if I don't provide a sufficient minimal reproduction?**

Issues with the `incomplete` label that receives no meaningful activity (e.g. new comments with a reproduction link) are automatically closed and locked after 30 days.

If your issue has _not_ been resolved in that time and it has been closed/locked, please open a new issue with the required reproduction.

### **I did not open this issue, but it is relevant to me, what can I do to help?**

Anyone experiencing the same issue is welcome to provide a minimal reproduction following the above steps. Furthermore, you can upvote the issue using the :+1: reaction on the topmost comment (please **do not** comment "I have the same issue" without repro steps). Then, we can sort issues by votes to prioritize.

### **I think my reproduction is good enough, why aren't you looking into it quicker?**

We look into every NextAuth.js issue and constantly monitor open issues for new comments.

However, sometimes we might miss one or two. We apologize, and kindly ask you to refrain from tagging core maintainers, as that will usually not result in increased priority.

Upvoting issues to show your interest will help us prioritize and address them as quickly as possible. That said, every issue is important to us, and if an issue gets closed by accident, we encourage you to open a new one linking to the old issue and we will look into it.

### **Useful Resources**

- [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
- [Reporting a NextAuth.js bug](https://github.com/nextauthjs/next-auth/blob/main/.github/ISSUE_TEMPLATE/1_bug_framework.yml)
- [How to Contribute to Open Source (Next.js)](https://www.youtube.com/watch?v=cuoNzXFLitc)

**Comment by codadrop** [comment] 2022-12-20 01:59
@DoctorateFR @balazsorban44 
I believe the example is working as intended. I have set it up just like your description.

On this [page](https://next-auth.js.org/configuration/options#session), you'll notice the docs say: 

> // The default is `"jwt"`, an encrypted JWT (JWE) stored in the session cookie.
>  // If you use an `adapter` however, we default it to `"database"` instead.

This is just saying that because you are using Prisma (an adapter), a database session is being used instead of a JWT. Since the middleware in `middleware.ts` `authorized` function takes a JWT, those pages are not accessible.

**Comment by balazsorban44** [comment] 2022-12-24 15:38
Closing as per the above comment. If you disagree, please open a new issue with a proper reproduction.

**Closed by balazsorban44** 2022-12-24 15:38 UTC
Labels: incomplete, triage

**Comment by reddiedev** [comment] 2022-12-24 15:54
Hello, I am experiencing the same problem. I am trying to create the middleware that protects my routes but I am using a GoogleProvider and PrismaAdapter. The token is indeed null even after sign in, leading to redirect loops. 

Can you recommend a good way to do the authentication? Currently I am looking at `unstable_getServerSession()` and `getToken()` but I am not sure if they are great ideas

**Comment by reddiedev** [comment] 2022-12-24 16:18
Never mind, after some more reading, I got more context on the current status regarding supporting the database strategy for next-auth middleware.
