### ISSUE TITLE
JWT options type definition vs documentation

### ISSUE THREAD

**Issue by Mosquid** [nextauthjs/next-auth#2824] opened 2021-09-23 09:24 UTC
### Description 🐜

JWT options in the documentation (v4) and a corresponding type definition are largely mismatches.

`encryptionKey: Type '{ kty: string; kid: string; alg: string; k: string; }' is not assignable to type 'string'.ts`

`decryptionOptions: 'decryptionOptions' does not exist in type 'Partial<JWTOptions>`

### Is this a bug in your own project?

Yes

### How to reproduce ☕️

Take the code snippet from the docs https://next-auth.js.org/configuration/options#options and paste it into your jwt options section (next-auth@beta)

### Environment 🖥

```
 System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 583.41 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.4 - ~/.npm-global/bin/npm
  Browsers:
    Brave Browser: 92.1.27.108
    Chrome: 93.0.4577.82
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    next: 11.1.2 => 11.1.2 
    next-auth: ^4.0.0-beta.2 => 4.0.0-beta.2 
    react: 17.0.2 => 17.0.2 

```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment] 2021-09-23 09:56
Duplicate of https://github.com/nextauthjs/docs/issues/5

**Closed by balazsorban44** 2021-09-23 09:56 UTC
Labels: bug
