### ISSUE TITLE
How to update session with updated user schema

### ISSUE THREAD

**Issue by killjoy2013** [nextauthjs/next-auth#11431] opened 2024-07-23 13:25 UTC
### What is the improvement or update you wish to see?

I'm trying to add `role` to user in the Session;

```ts
import { getUserByEmail } from "@/src/data-access/get-user-by-role.persistence";
import { db } from "@/src/db";
import { DrizzleAdapter } from "@auth/drizzle-adapter";
import NextAuth, { DefaultSession } from "next-auth";
import EmailProvider from "next-auth/providers/nodemailer";

declare module "next-auth" {
  interface Session extends DefaultSession {
    user: {
      role: string;
    } & DefaultSession["user"];
  }
  interface User {
    role: string;
  }
}

export const { handlers, signIn, signOut, auth } = NextAuth({
  adapter: DrizzleAdapter(db),
  providers: [
    EmailProvider({
      server: {
        host: process.env.EMAIL_SERVER_HOST,
        port: parseInt(process.env.EMAIL_SERVER_PORT as string, 10),
        auth: {
          user: process.env.EMAIL_SERVER_USER,
          pass: process.env.EMAIL_SERVER_PASSWORD,
        },
        tls: {
          // Allow self-signed certificates
          rejectUnauthorized: false,
        },
      },
      from: process.env.EMAIL_FROM,
    }),
  ],
  secret: process.env.NEXTAUTH_SECRET,
  debug: true, // Enable debug to see detailed logs
  trustHost: true, // Add this line to trust localhost during development
  callbacks: {
    async signIn({ user, account, profile, email, credentials }) {
      try {
        if (user.email) {
          const foundUsers = await getUserByEmail(user.email);
          return foundUsers.length > 0;
        }
        return false;
      } catch (error) {
        console.error("Error in signIn callback:", error);
        return false;
      }
    },

    async session({ session, token }) {
      if (session.user?.email) {
        const userFromDb = await getUserByEmail(session.user.email);

        if (userFromDb && userFromDb.length > 0) {
          session.user.role = userFromDb[0].role as string;
        }
      }

      return session;
    },
  },
});
```

compiler is yelling here;
`adapter: DrizzleAdapter(db),` saying
Types of property 'createUser' are incompatible.

I'm sure this is a pretty common requirement. However, the docs only mentions adding id to seesion [https://authjs.dev/guides/extending-the-session](https://authjs.dev/guides/extending-the-session) which is not enough.

How to solve this? shall we override createUser somehow?. 
If there's already some docs I missed,  pls guide me there. 
What would you recommend in this case?

Thanks

### Is there any context that might help us understand?

I need to update the User in Session. I made the change in db schema. Now what to do?

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/extending-the-session

**Comment by TauanAlmeida** [comment] 2024-07-31 02:05
in your next-auth config change your callbacks for:
```
async jwt({ token, user }) {
      if (user) {
        token.user = user //omit the user password
      }
      return token;
    }
  }
```

```
async session({ session, token }) {
      if (token.user) {
        return {
          ...session,
          user: {
            ...session.user,
            ...token.user,
          },
        };
      }
      return session;
    }
```

**Comment by balazsorban44** [comment] 2024-08-10 16:30
Likely a duplicate of https://github.com/nextauthjs/next-auth/issues/9493#issuecomment-2282200662

Otherwise you might need to tweak

```diff
+ import { User as DefaultUser } from "next-auth" 
- interface User {
+ interface User extends DefaultUser {
  role: string;
}
```

If you need more help, please open a new issue with a reproduction. 🙏

**Closed by balazsorban44** 2024-08-10 16:30 UTC
Labels: documentation, triage
