### ISSUE TITLE
redirect false not working when authenticated - signIn('credentials', { redirect: false, password: data.password, email: data.email })

### ISSUE THREAD

**Issue by mikloshumli** [nextauthjs/next-auth#6016] opened 2022-12-10 11:56 UTC
### Question 💬

if call signIn function and my server unauthorized then redirect false working fine.
But if res ok=== true (authorized) then redirect home page.
Is this normal operation?
signIn('credentials', { redirect: false, password: data.password, email: data.email })
I want play animate and send message to user before redirect.

**NetAuth: 4.17.x or 4.18.x**
**Nextjs 13.0.6**

Can anybody help me?

### How to reproduce ☕️

signIn('credentials', { redirect: false, password: data.password, email: data.email })

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment] 2022-12-10 18:10
Please read open issues before opening a new one (without a reproduction). It's the last issue opened before this one. Duplicate of https://github.com/nextauthjs/next-auth/issues/6001

**Closed by balazsorban44** 2022-12-10 18:10 UTC
Labels: question
