### ISSUE TITLE
Next-auth doesn't work on IE11 without transpiling

### ISSUE THREAD

**Issue by TeosVerdi** [nextauthjs/next-auth#2359] opened 2021-07-12 19:23 UTC
This issue is a follow-up to #2358 

I have noticed next-auth doesn't translate well to IE11 without `next-transpile-modules`, even though the NA's build configuration suggests it does. With the package the project doesn't build, as shown in the beforementioned issue.

IE11 Error: `SCRIPT1006: Expected ')'`
Lines this refers to: 
```
function setLogger(newLogger = {}) {
  if (newLogger.error) _logger.error = newLogger.error;
  if (newLogger.warn) _logger.warn = newLogger.warn;
  if (newLogger.debug) _logger.debug = newLogger.debug;
}

var _default = _logger;
exports.default = _default;
```

next.config.js: 
```
/* eslint-disable @typescript-eslint/no-var-requires */
const path = require('path');
const { i18n } = require('./next-i18next.config');

// FIXME: NextAuth doesn't build without database

module.exports = {
  productionBrowserSourceMaps: true,
  i18n,
  webpack: (config, { isServer }) => {
    config.module.rules.push({
      test: /\.svg$/,
      use: ['@svgr/webpack'],
    });

    if (!isServer) {
      config.resolve.alias['@sentry/node'] = '@sentry/browser';
      // IEKILL
      config.resolve.alias['react-hook-form'] =
        'react-hook-form/dist/index.ie11';
    }
    return config;
  },
  sassOptions: {
    includePaths: [path.join(__dirname, 'src/styles')],
    prependData: `@use "sass:math"; @import "global/variables.scss";`,
  },
};
```

tsconfig.json:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "jsx": "preserve",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "lib": [
      "dom",
      "dom.iterable",
      "es6"
    ],
    "allowJs": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "src/*"
      ],
      "public/*": [
        "public/*"
      ]
    },
    "isolatedModules": true,
    "experimentalDecorators": true,
    "moduleResolution": "node"
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ],
}
```

Related: I'm using `pnp` module packaging from `yarn@2`. I also do not use the `database` option in `[...nextauth].ts` 

Environment:
OS: Windows 10 / Internet Explorer 11
Next: 11.0.1
Next-Auth: ^3.27.1

**Comment by balazsorban44** [comment] 2021-07-12 19:28
could please try something else than yarn 2 PnP? it has historically been proven to go a different path than others and caused headaches.

#2147 #1034 #1306 https://github.com/vercel/next.js/issues/20955

if you can prove that the problem is still present when using something else than yarn 2 PnP, I might be able to look more into this.

**Comment by TeosVerdi** [comment] 2021-07-13 08:49
@balazsorban44 
Disabling `pnp` helped. Can we expect next-auth to support it in the future releases?

**Comment by balazsorban44** [comment] 2021-07-13 08:53
In that case, I am inclined to close this. Unfortunatelly, I don't have the time/knowledge to debug their solution. Pretty much everyone else's setup should just work. See the previous conversations I linked to here: https://github.com/nextauthjs/next-auth/issues/2359#issuecomment-878536676

That said, if we are required to do some **reasonable** changes in our packaging to get it to work, I might be OK with it, but someone from the community will have to step in to do the research and open a PR.

**Closed by balazsorban44** 2021-07-13 08:53 UTC
