### ISSUE TITLE
Theme options not applied to default signin page

### ISSUE THREAD

**Issue by sepehrfakour** [nextauthjs/next-auth#7687] opened 2023-05-31 02:27 UTC
### Question 💬

Theme options `theme.brandColor` and `theme.buttonText` are not applied on the default signin page, while the `theme.colorScheme` and `theme.logo` are successfully applied. All options are correctly applied on the default signout page.

As described [here](https://next-auth.js.org/configuration/options#theme), my theme object in `/app/api/auth/[...nextauth]/route.ts` looks like this:

```ts
theme: {
  colorScheme: 'auto',
  brandColor: '#000000',
  logo: '/logo.svg',
  buttonText: '#FFF'
},
```

I am using Next.js app router. All testing has been in development environment. No console errors or warnings, either client or server side.

next-auth version: `4.22.1`
next version: `13.4.3`
node version: `19.2.0`

Have I misconfigured something, or is this potentially a bug?

### How to reproduce ☕️

Using the same `node`, `next`, and `next-auth` versions and the same `theme` options as mentioned, navigate to [http://localhost:3000/api/auth/signin](http://localhost:3000/api/auth/signin) in your Next.js app that uses app router and nextAuth, and note the button background and text colors.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by muhaimincs** [comment] 2023-07-30 06:35
yes. `brandColor` does not apply anywhere on the default sign in page

**Comment by ThangHuuVu** [comment] 2023-08-01 04:46
The `brandColor` will affect the button background and border color of the Email Sign In button. Are these not working for you? 
I'm closing this since I am not able to reproduce it locally on our dev app 🙏 Feel free to reopen it if you still see the issue, and please remember to attach a minimal reproduction in the new issue.

**Closed by ThangHuuVu** 2023-08-01 04:46 UTC
Labels: question

**Comment by sepehrfakour** [comment] 2023-08-01 05:29
Hey @ThangHuuVu, thanks for the reply and for looking into this, I appreciate the help.

> The brandColor will affect the button background and border color of the Email Sign In button. Are these not working for you?

Correct, that is the button in question. Currently neither `brandColor` nor `buttonText` are being applied in my app. I am now using next-auth `4.22.1` and next `13.4.9`.

How can I best help to reproduce on your side? What's the best way to create + attach a minimal reproduction?

**Comment by ThangHuuVu** [comment] 2023-08-01 05:52
@sepehrfakour you can deploy a simple next app with said version and paste the GitHub & Vercel link here, I'd be happy to reopen if we can see the issue 🙏 You can clone our example project at https://github.com/nextauthjs/next-auth-example and add the theme option with the email provider
Make sure to strip all the unnecessary parts from your reproduction.

Ref: https://stackoverflow.com/help/minimal-reproducible-example
