### ISSUE TITLE
Error: This action with HTTP GET is not supported by NextAuth.js

### ISSUE THREAD

**Issue by fasilminale** [nextauthjs/next-auth#6045] opened 2022-12-14 09:47 UTC
### Question 💬

Unable to authenticate my Next.js app with credentials. Error: This action with HTTP GET is not supported by NextAuth.js

As far as I know everything is correct according to the doc. and it was working too. it suddenly start returning this error.

```json
{
  "name": "materio-mui-react-nextjs-admin-template-free",
  "description": "Most Powerful & Comprehensive Free MUI React NextJS Admin Dashboard Template built for developers! 🚀",
  "license": "MIT",
  "version": "1.0.0",
  "author": {
    "name": "IWorkplc",
    "url": "https://iworkplc.com/"
  },
  "bugs": {
    "url": "https://github.com/themeselection/materio-mui-react-nextjs-admin-template-free/issues"
  },
  "private": false,
  "repository": {
    "type": "git",
    "url": "https://github.com/themeselection/materio-mui-react-nextjs-admin-template-free.git"
  },
  "homepage": "https://themeselection.com/products/materio-free-mui-react-nextjs-admin-template/",
  "keywords": [
    "react",
    "javascript",
  ],
  "scripts": {
    "info": "next info",
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "export": "next export",
    "lint": "eslint --fix \"src/**/*.{js,jsx}\"",
    "format": "prettier --write \"src/**/*.{js,jsx}\"",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@emotion/cache": "^11.6.0",
    "@emotion/react": "^11.7.0",
    "@emotion/server": "^11.4.0",
    "@emotion/styled": "^11.6.0",
    "@iconify/react": "^4.0.0",
    "@material-ui/icons": "^4.11.3",
    "@mui/icons-material": "^5.10.15",
    "@mui/lab": "^5.0.0-alpha.70",
    "@mui/material": "^5.4.3",
    "@popperjs/core": "^2.11.2",
    "@react-oauth/google": "^0.5.0",
    "@reduxjs/toolkit": "^1.9.0",
    "apexcharts-clevision": "3.28.5",
    "axios": "^1.2.0",
    "apisauce": "^2.1.6",
    "babel-eslint": "^10.1.0",
    "clsx": "^1.1.1",
    "formik": "^2.2.9",
    "mdi-material-ui": "^7.1.0",
    "moment": "^2.29.4",
    "next": "12.3.1",
    "next-auth": "^4.14.0",
    "nprogress": "^0.2.0",
    "react": "17.0.2",
    "react-apexcharts": "^1.3.9",
    "react-datepicker": "^4.5.0",
    "react-dom": "17.0.2",
    "react-perfect-scrollbar": "^1.5.8",
    "react-popper": "^2.2.5",
    "react-redux": "^8.0.5",
    "react-toastify": "^9.1.1",
    "react-use-websocket": "^4.2.0",
    "redux-logger": "^3.0.6",
    "socket.io-client": "^4.5.4",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "eslint": "^7.32.0",
    "eslint-config-next": "12.0.4",
    "eslint-config-prettier": "^8.3.0",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-import-resolver-typescript": "^2.5.0",
    "eslint-plugin-import": "^2.25.4",
    "next-transpile-modules": "^9.0.0",
    "patch-package": "^6.5.0",
    "postinstall-postinstall": "^2.1.0",
    "prettier": "2.5.1"
  }
}
```

```javascript
import NextAuth from 'next-auth'
import GoogleProvider from 'next-auth/providers/google'
import { getToken } from 'next-auth/jwt'

export const authOptions = {
  // Configure one or more authentication providers
  // debug: true,
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      authorization: {
        params: {
          scope:
            'openid email profile https://www.googleapis.com/auth/gmail.compose https://www.googleapis.com/auth/gmail.modify'
        }
      },
      idToken: true
    }),
    {
      clientId: process.env.QUICK_BOOKS_CLIENT_ID,
      clientSecret: process.env.QUICK_BOOKS_CLIENT_SECRET,
      id: 'quickbooks',
      name: 'QuickBooks',
      type: 'oauth',
      wellKnown: 'https://developer.api.intuit.com/.well-known/openid_sandbox_configuration',
      authorization: { params: { scope: 'com.intuit.quickbooks.accounting openid profile email phone address' } },
      userinfo: {
        async request(context) {
          return await context.client.userinfo(context.tokens.access_token)
        }
      },

      idToken: true,
      checks: ['pkce', 'state'],
      profile(profile) {
        return {
          id: profile.sub,
          name: profile.name,
          email: profile.email,
          image: profile.picture
        }
      }
    },
    // ...add more providers here
    {
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      id: 'googledrive',
      name: 'Google Drive',
      type: 'oauth',
      wellKnown: 'https://accounts.google.com/.well-known/openid-configuration',
      authorization: {
        params: {
          scope:
            'openid email profile https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/drive.resource'
        }
      },
      idToken: true,
      checks: ['pkce', 'state'],

      profile(profile) {
        return {
          id: profile.sub,
          name: profile.name,
          email: profile.email,
          image: profile.picture
        }
      }
    }
  ],
  callbacks: {
    async session({ session, token, user }) {
      session.user.id = token?.id
      session.accessToken = token?.accessToken
      session.provider = token?.account?.provider
      return session
    },
    async jwt({ token, user, account, profile, isNewUser }) {
      if (user) {
        token.user = user
      }
      if (account) {
        token.account = account
      }
      return token
    }
  }
}

export default NextAuth(authOptions)
```

[...nextauth].js is inside pages/api/auth 

this is the url: http://localhost:3000/api/auth/callback/google/?state="" ....

### How to reproduce ☕️

.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by yuvrajmahalle** [comment] 2022-12-14 11:46
@fasilminale I've got the same configuration, it's working for me on `4.18.0` but failing on `4.18.1` and above.

**Comment by IceToast** [comment] 2022-12-14 11:53
I'm facing the same issue since 4.18.1. SignIn Callbacks are not reachable because of the described Error.

**Comment by fasilminale** [comment] 2022-12-14 11:59
@yuvrajmahalle what's your nextjs vertion?

**Comment by yuvrajmahalle** [comment] 2022-12-14 12:02
@fasilminale 
it's `12.2.5`

**Comment by fasilminale** [comment] 2022-12-14 12:04
mine nextjs version is 12.3.1, i'll downgrade it to 12.2.5. i even upgrade next-auth version to 4.18.0 but i'm getting the same error.

**Comment by yuvrajmahalle** [comment] 2022-12-14 12:07
Are you in an organisation proxy network?
could you please post a snapshot of the error?

**Comment by fasilminale** [comment] 2022-12-14 12:13
when i sign in it redirect me to this url and then the error will be returned.

http://localhost:3000/api/auth/callback/google/?state="..."&code="..."&scope=email%20profile%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.compose%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.modify&authuser=0&prompt=consent

**Comment by fasilminale** [comment] 2022-12-14 12:17
<img width="1237" alt="Screen Shot 2022-12-14 at 3 17 02 PM" src="https://user-images.githubusercontent.com/30689833/207593143-f234efa8-c8f6-437b-a964-fe17f5531757.png">

**Comment by yuvrajmahalle** [comment] 2022-12-14 12:18
Not sure, give it a try by upgrading your auth-next version to the latest.

**Comment by fasilminale** [comment] 2022-12-14 12:19
i tried that too. but it didn't fix it.

**Comment by IceToast** [comment] 2022-12-14 12:20
> Not sure, give it a try by upgrading your auth-next version to the latest.

Won't change alot. I'm on Next 13.0.6 and next-auth 4.18.6. Same Error

**Comment by fasilminale** [comment] 2022-12-14 12:21
@balazsorban44 Could you please assist us? I've been stuck with this problem for three days now.

**Comment by yuvrajmahalle** [comment] 2022-12-14 12:22
> > Not sure, give it a try by upgrading your auth-next version to the latest.
> 
> Won't change alot. I'm on Next 13.0.6 and next-auth 4.18.6. Same Error

Same, Situation 
Minor release like `4.18.1` is breaking stuff 😞

**Comment by balazsorban44** [comment] 2022-12-14 12:54
Need a **minimal** reproduction. Should be fixed already on `4.18.6`.

**Comment by yuvrajmahalle** [comment] 2022-12-14 12:57
@balazsorban44, that issue is fixed in the new version but, throwing a different error of `maximum redirects`.

**Comment by balazsorban44** [comment] 2022-12-14 12:59
Repro.

**Comment by IceToast** [comment] 2022-12-14 13:53
> We cannot recreate the issue with the provided information. **Please add a reproduction in order for us to be able to investigate.**
> 

I've created a small repo that has the same issue as described here. I removed all code that is not really necessary but still maintain a rather realistic app base.
It's using NextJS 13.0.6 and Next-Auth 4.18.6.

Repro Steps:
- Clone Repo
- Fill necessary environment variables (use the .env.example file)
- Run `prisma db push`
- Start the NextJS development server
- Go to `http://localhost:3000`
- Try to login via the google OAuth Button (You may add any other Provider)

If there is anything you need, please let me know

**Comment by nkkky** [comment] 2022-12-14 17:18
Same problem here... i am on NextJS 13.0.6 and Next-Auth 4.18.6. as well. - I am also using the latest Turborepo version where the .env variables need to be declared as globalDependencies. - The OAuth2 callback isn't working for me. I've tried signing in with Twitter, Google, Gitlab, Github-OAuth2. Nothing worked. [Screenshot](https://media.discordapp.net/attachments/1028961678269874257/1052610297631867040/image.png)

**Comment by balazsorban44** [comment] 2022-12-15 11:17
@IceToast so first of all, directly modifying the session token might have unforeseen consequences, https://github.com/IceToast/next-auth-issue/blob/9152da4aff2e02c16e6f28c9bf360e8ba83c6316/src/pages/api/auth/%5B...nextauth%5D.js#L128

like you totally ignore the prefixing for increased security: https://github.com/nextauthjs/next-auth/blob/875f79d11e781a6cff21afa45e2211f602bc23a8/packages/next-auth/src/core/lib/cookie.ts#L61

(There is a reason that messing with the cookies and using the credentials provider with a database is not recommended.)

The "minimal" reproduction was also very bloated, looks like you just linked to your full project. Keep in mind that it increases the time for triaging.

Anyway, I created my own reproduction and could not find an issue: https://github.com/balazsorban44/next-auth-6045

**Comment by IceToast** [comment] 2022-12-15 11:58
> s

Thanks for looking into it. Yes i'm aware that messing with the session token does have its consequences, however it has nothing to do with what this bug is about.

The reproduction is indeed a copy of a project of mine with all not necessary code removed. I will gladly make it more minimalistic if you wish. I will edit this post when it's done.

**Comment by IceToast** [comment] 2022-12-16 12:08
> Anyway, I created my own reproduction and could not find an issue: https://github.com/balazsorban44/next-auth-6045
> 
@balazsorban44 
I've tried your reproduction on my local and a dedicated remote machine (for science) with the github and google provider. I've also tried my repro, that is using a database session with the prisma adapter, with the google and github providers. Same issue. I double checked that my package managers do not use a local cache of a broken version. 
I hope that information may help you a little bit.

Have a nice weekend!

**Comment by hvitis** [comment] 2022-12-20 00:09
I'm having a similar issue, so far half of the problem was caching cookies on vercel. When it comes to the second part, I'm still investigating it but the bug is on vercels production which doesn't give much debugging insights.

**Comment by quanglam2807** [comment] 2022-12-21 05:06
@balazsorban44 I confirm. I fixed the issue for me (upgraded from 4.18.6)

**Comment by IceToast** [comment] 2022-12-21 15:50
@balazsorban44 I can also confirm that this fix works!

**Comment by balazsorban44** [comment] 2022-12-21 20:21
New stable release will come out soon with this. Thanks for confirming.

**Comment by IceToast** [comment] 2022-12-21 22:00
> New stable release will come out soon with this. Thanks for confirming.
> 
> We will have to add proper fully covering tests at some point. 🙃
Thanks for your time to investigate and fix!

**Comment by balazsorban44** [comment] 2022-12-22 00:00
`4.18.7` is out with this fixed.

**Closed by balazsorban44** 2022-12-22 00:00 UTC
Labels: triage

**Comment by JadYaghi** [comment] 2023-02-14 21:41
I have gotten this problem in V4.19.2

**Comment by ks-krimi** [comment] 2023-03-09 13:56
> I have gotten this problem in V4.19.2

@JadYaghi  make sure you typed the correct link
for example: http://localhost:3000/api/auth/signin

I use __"next-auth": "^4.20.1"__ and it works perfectly

**Comment by wfischer42** [comment] 2023-03-13 17:25
I'm getting this in `"next-auth": "^4.20.1"`

**Comment by hifilorau** [comment] 2023-05-30 17:51
Im getting this error now, but only in production using next-auth 4.22.1 it happens with both my GoogleProvider and also when doing a custom credentials provider. But both work fine in dev but are breaking in production. Am using next 13 but have all my auth running through pages router and not app router.

**Comment by zarif-al** [comment] 2023-06-04 08:56
> Im getting this error now, but only in production using next-auth 4.22.1 it happens with both my GoogleProvider and also when doing a custom credentials provider. But both work fine in dev but are breaking in production. Am using next 13 but have all my auth running through pages router and not app router.

I'm facing the same issue. Using
-  "next": "13.4.3",
-  "next-auth": "^4.22.1",

**Comment by Got-crypto** [comment] 2023-06-30 21:15
I just came across this error. At first, I thought It was because my environment variables were not loaded since I forgot to add them in next.config.js file, but the error persisted. I checked the URL on which the error was and Immediately noticed that the URLs I provided in Google Cloud and in which my server was running on were not matching. I provided "http://localhost:3000" and my next.js server was running on "http://localhost:3001". After fixing that, everything worked fine.

**Comment by tittobreno** [comment] 2025-03-13 22:57
> Im getting this error now, but only in production using next-auth 4.22.1 it happens with both my GoogleProvider and also when doing a custom credentials provider. But both work fine in dev but are breaking in production. Am using next 13 but have all my auth running through pages router and not app router.

I have the same problem
