### ISSUE TITLE
example-nextjs broken (due to @babel/runtime): Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime 

### ISSUE THREAD

**Issue by nolanholden** [nextauthjs/next-auth#6028] opened 2022-12-12 10:54 UTC
### Environment

clean repo build on next-auth/apps/example-nextjs is broken

```
(venv3) $ npm run build

> build
> next build

info  - Loaded env from [REDACTED]
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

./node_modules/@babel/runtime/regenerator/index.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime 
Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation

Import trace for requested module:
./node_modules/@babel/runtime/regenerator/index.js
./node_modules/next-auth/core/errors.js
./node_modules/next-auth/utils/web.js
./node_modules/next-auth/next/middleware.js
./node_modules/next-auth/middleware.js


> Build failed because of webpack errors
```

I am skirting the issue using `npx patch-package @babel/runtime` with this diff:

(Really not sure how wise it is...)

```diff
diff --git a/node_modules/@babel/runtime/regenerator/index.js b/node_modules/@babel/runtime/regenerator/index.js
index 5881357..4dfc2ae 100644
--- a/node_modules/@babel/runtime/regenerator/index.js
+++ b/node_modules/@babel/runtime/regenerator/index.js
@@ -10,6 +10,7 @@ try {
   if (typeof globalThis === "object") {
     globalThis.regeneratorRuntime = runtime;
   } else {
-    Function("r", "regeneratorRuntime = r")(runtime);
+    console.error(accidentalStrictMode)
+    // Function("r", "regeneratorRuntime = r")(runtime);
   }
 }
```

### Reproduction URL

google.com

### Describe the issue

build is broken

### How to reproduce

```sh
git clone https://github.com/nextauthjs/next-auth.git
cd next-auth/apps/example-nextjs
npm run build
```

### Expected behavior

build should succeed

**Comment by balazsorban44** [comment] 2022-12-12 11:00
Duplicate of #6025. Please read through open issues before opening a new one. :pray:

**Closed by balazsorban44** 2022-12-12 11:00 UTC
Labels: triage

**Comment by AVDAIN** [comment] 2023-08-25 17:23
I am experiencing the same error, unfortunately I haven't found a solution for it yet. I have read through the proposed problem and have not found a valid solution.



**Build Error** ↓
```
./node_modules/@babel/runtime/regenerator/index.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime
Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation
```

**Comment by faizan-glowlogix** [comment] 2023-11-15 06:02
@AVDAIN i am struck at this issue. Can you please share how to resolve it?

**Comment by kris-amerman** [comment] 2024-02-19 17:25
Is there any update on this? Using v4.24.6 and still encountering this issue.

**Comment by maximus-lynn** [comment] 2024-03-01 16:23
+ 1

**Comment by a-meicy** [comment] 2024-03-18 09:43
is there any update on this issue? trying to build prod and countered this issue.

**Comment by phillmorgan28** [comment] 2024-08-21 21:16
Same issue

**Comment by mmmoli** [comment] 2024-11-09 21:34
Same with 4.24.10
