### ISSUE TITLE
Custom field input before signIn

### ISSUE THREAD

**Issue by cloudagon** [nextauthjs/next-auth#2149] opened 2021-06-09 03:49 UTC
## Question 💬

How do I provide a custom field before `signIn`? I want all my users to have unique usernames so they can easily be identified, but this is not possible with the current information. I want them to input a username before clicking signIn, but I'm not sure what to do from there. How do I get it into my database? I'm using the [Prisma adapter](https://www.npmjs.com/package/@next-auth/prisma-adapter) if it matters.

**Comment by balazsorban44** [comment] 2021-06-09 09:57
Possible duplicate of #1069

**Closed by balazsorban44** 2021-06-09 09:57 UTC
Labels: question
