### ISSUE TITLE
Error: [next-auth]: `useSession` must be wrapped in a <SessionProvider />

### ISSUE THREAD

**Issue by mehtab1998** [nextauthjs/next-auth#5052] opened 2022-07-30 20:24 UTC
### Environment

Vanilla Next.js application 

Dependency Command: 
 npm i next-auth @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion^6 react-icons nanoid 

### Reproduction URL

 next-auth-example

### Describe the issue

I decided to move the 'pages' directory into the src directory &  now even with the most simple example it is not working!

### How to reproduce

1) I decided to move the 'pages' directory into the src directory &  now even with the most simple example it is not working!
2) here is my **/src/pages/index.js:**
```
import React from 'react'
import { Heading, Button } from '@chakra-ui/react'
//hook to check if auth session exist 
import { useSession, signIn } from 'next-auth/react'

const Home = () => {
  const {data: session, status} = useSession()
  return (
    <> 
     <h1> {session ? 'session dne': 'session does exisit'}</h1> 
    {/* <Button>Sign In</Button> */}
    </>
  )
}

export default Home
```

3) here is my **/src/pages/_app.js:**
```

import {SessionProvider} from 'next-auth/react'
import {ChakraProvider} from '@chakra-ui/react'


function MyApp({ Component, pageProps }) {
  return (
    <SessionProvider session={pageProps.session}> 
         <ChakraProvider> 
              <Component {...pageProps} />
        <ChakraProvider/> 
    </SessionProvider>
  )
}
export default MyApp

```

### Expected behavior

just want to be able to get this error to go away :)

**Comment by ThangHuuVu** [comment] 2022-07-31 06:43
Hi @mehtab1998 👋 I cannot reproduce this issue you're facing. I'll close this one for now, but I will gladly take a closer look if you could provide a minimal reproduction 🙌

**Closed by ThangHuuVu** 2022-07-31 06:43 UTC
Labels: incomplete

**Comment by mehtab1998** [comment] 2022-08-01 15:53
@ThangHuuVu, I figured it out! I had to delete my .next folder and everything started working
