### ISSUE TITLE
Refresh token example with database sessions

### ISSUE THREAD

**Issue by Seth-McKilla** [nextauthjs/next-auth#4662] opened 2022-06-01 14:46 UTC
### What is the improvement or update you wish to see?

The next-auth examples could use a refresh token rotation example using database sessions.

### Is there any context that might help us understand?

I've successfully implemented this on a project I'm working on that uses prisma, planetscale, and GitHub OAuth and am more than happy to extract the fundamental logic into a sample repo and write documentation for this. I think this would be a valuable resource for developers since there's a lot of questions regarding this topic and it can be a bit tricky to implement. I don't believe there's an existing issue for this that is open, but apologies if I missed it!

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/guides/fullstack

**Comment by Seth-McKilla** [comment] 2022-06-01 19:14
> @Seth-McKilla , Greetings.
> 
> I am trying to do the same thing. I am using ` "next": "12.1.4", "next-auth": "^4.3.4",` . I am using Github's OAuth and using Prisma adapter to save the session to a Sqlite DB. I am also using Next's middleware to verify the session when the user tries to visit a protected route.
> 
> However, when I try to access the session in my middleware its failing to get the session. The session is being written to the adapter, that I can confirm . Without caching the session to the DB everything works fine.
> 
> Have you faced this issue as well ? If you were , can you please let me know how you were able to resolve this issue please ?
> 
> Thanks, Gagan

Hey @gj1118 👋

Yep I ran into that issue too, unfortunately due to current maturity of databases at the Edge, middleware is only available with the jwt session strategy: https://next-auth.js.org/configuration/nextjs#caveats

As for how I'm handling it (which I'm not sure is the best way to go about doing it), is as follows. Apologies in advance for the incoming wall of code, but want to share the entirety of my api/auth/[...nextauth].ts file. However, I've jinxed myself as it was working well for most of the day but have been running into "bad refresh token" like this: https://github.community/t/bad-refresh-token-when-refreshing-an-user-to-server-token/126700/15


```js
import NextAuth from "next-auth";
import GithubProvider from "next-auth/providers/github";
import { PrismaAdapter } from "@next-auth/prisma-adapter";
import { prisma, stripe } from "lib";
import { getStripeSubTier } from "utils";

export default NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [
    GithubProvider({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
      profile(profile) {
        return {
          id: profile.id,
          name: profile.name,
          email: profile.email,
          image: profile.avatar_url,
          username: profile.login,
        };
      },
    }),
  ],
  secret: process.env.NEXTAUTH_SECRET,
  pages: {
    signIn: "/signin",
    signOut: "/",
    newUser: "/profile/signup",
  },
  callbacks: {
    async session({ session, user }) {
      const stripeSubTier = getStripeSubTier(user.stripeSubId as string);

      session.user!.id = user.id;
      session.user!.username = user.username as string;
      session.user!.stripeCustomerId = user.stripeCustomerId as string;
      session.user!.stripeSubTier = stripeSubTier as string;

      if (!session.accessTokenExpires) {
        const userAccount = await prisma.account.findFirst({
          where: {
            userId: user.id,
            provider: "github",
          },
        });

        const accessTokenExpires = userAccount!.expires_at!; // seconds

        // convert to milliseconds for check
        if (Date.now() < accessTokenExpires * 1000) {
          const accessTokenExpires = await refreshGitHubAccessToken(
            user.id,
            userAccount!.refresh_token!
          );

          session.accessTokenExpires = accessTokenExpires; // seconds
        }

        session.accessTokenExpires = userAccount!.expires_at!; // seconds
      }

      return session;
    },
  },
  events: {
    createUser: async ({ user }) => {
      const customer = await stripe.customers.create({
        email: user.email!,
        name: user.name!,
      });

      await prisma.user.update({
        where: { id: user.id! },
        data: {
          stripeCustomerId: customer.id,
        },
      });
    },
  },
});

const refreshGitHubAccessToken = async (
  userId: string,
  refresh_token: string
) => {
  const params = new URLSearchParams({
    refresh_token,
    grant_type: "refresh_token",
    client_id: process.env.GITHUB_ID!,
    client_secret: process.env.GITHUB_SECRET!,
  });
  try {
    const response = await fetch(
      `https://github.com/login/oauth/access_token?${params}`,
      {
        headers: {
          Accept: "application/json",
        },
        method: "POST",
      }
    );

    const data = await response.json();

    if (!!data.error) {
      throw new Error(data.error_description);
    }

    const accessTokenExpires = Date.now() / 1000 + data.expires_in; // seconds

    await prisma.account.updateMany({
      where: {
        userId,
      },
      data: {
        access_token: data.access_token,
        refresh_token: data.refresh_token,
        refresh_token_expires_in: data.refresh_token_expires_in,
        expires_at: accessTokenExpires,
        token_type: data.token_type,
        scope: data.scope,
      },
    });

    return accessTokenExpires;
  } catch (error: any) {
    console.error(error);
    throw new Error(error?.message);
  }
};
```

Curious your thoughts / feedback on my implementation method, hopefully we can wrestle a successful refresh token rotate together!

**Comment by gj1118** [comment] 2022-06-01 22:00
Thanks @Seth-McKilla . I dont know what I would have done without your link. My sincerest gratitudes. Thank you soo much., but now I am stuck in the same boat as yourself.  Please update this thread, If you come across a solution that fixes it. I will post as well, if I manage to fix it. 

Thanks,
Gagan

**Comment by balazsorban44** [comment] 2022-06-02 10:30
Duplicate of #3809

**Closed by balazsorban44** 2022-06-02 10:30 UTC
Labels: documentation, triage
