### ISSUE TITLE
User object is empty

### ISSUE THREAD

**Issue by choutkamartin** [nextauthjs/next-auth#2757] opened 2021-09-14 22:33 UTC
### Question 💬

Hi,
I don't know what I'm doing wrong.

I use 4.0.0-beta.2 version, credentials login, MongoDB for storing users and JWT.

The problem is that, right now, I can log in without a problem, log out, but the session object contains an empty user object - so I can't render users username and so on. Did someone have a similar problem? My previous apps that ran v3 worked flawlessly. I inserted a few code snippets below, that should explain my code a little bit

Thanks in advance 🙂 

### How to reproduce ☕️

**Session object**
```json
{
    "user": {},
    "expires": "2021-10-14T22:04:10.401Z"
}
```

**Page dashboard.jsx**
```js
import { useSession } from "next-auth/react";

const Dashboard = () => {
  const { data: session, status } = useSession();
  const logSession = () => {
    console.log(session, status);
  };
};

export default Dashboard;

```
**[..nextauth.js]**
```js
import NextAuth from "next-auth";
import CredentialsProvider from "next-auth/providers/credentials";

export default NextAuth({
  pages: {
    signIn: "/auth/login",
    signOut: "/auth/logout",
    error: "/auth/error",
    verifyRequest: "/auth/verify-request",
  },
  debug: true,
  providers: [
    CredentialsProvider({
      async authorize(credentials) {
        const res = await fetch("http://localhost:3000/api/auth/login", {
          method: "POST",
          body: JSON.stringify(credentials),
          headers: { "Content-Type": "application/json" },
        });
        const user = await res.json();
        if (res.ok && user) {
          console.log(user);
          // {
          //   _id: '612b4646c41e9e9f5068727a',
          //   password: 'Test123456789',
          //   username: 'admin'
          // }
          return user;
        } else {
          return null;
        }
      },
    }),
  ],
  session: {
    jwt: true,
    maxAge: 30 * 24 * 60 * 60,
  },
  jwt: {
    signingKey: process.env.JWT_SIGNING_PRIVATE_KEY,
  },
});

```

**_app.jsx**
```js
import "../index.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { appWithTranslation } from "next-i18next";
import { BoxedLayout } from "components/layouts/Boxed/Layout";
import { AdminLayout } from "components/layouts/Admin/Layout";
import { SessionProvider } from "next-auth/react";
import Auth from "components/Auth";

const layouts = {
  L1: BoxedLayout,
  L3: AdminLayout,
};

const MyApp = ({ Component, pageProps: { session, ...pageProps } }) => {
  const Layout = layouts[Component.layout] || ((children) => <>{children}</>);
  return (
    <SessionProvider session={session}>
      {Component.auth ? (
        <Auth>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </Auth>
      ) : (
        <Layout>
          <Component {...pageProps} />
        </Layout>
      )}
    </SessionProvider>
  );
};

export default appWithTranslation(MyApp);
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment] 2021-09-14 22:47
you mention mongodb, but we intentionally don't support databases with the credentials provider, so I assume it's something custom, I guess?

not necessarily the issue, but I  your authorize callback, you should rather import the logic to `login` than do a fetch call, it might be faster.

Could you provide a runnable reproduction so I could test it out?

**Comment by AydinChavez** [comment] 2021-09-15 10:00
I've experienced same issue with v4-beta2 (reported here https://github.com/nextauthjs/adapters/issues/219#issuecomment-919016150) and here same issue was reported as well: https://github.com/nextauthjs/next-auth/issues/2746 - don't get why his issue was closed but anyway. 
I feel like this project has a need for automated tests, due to its flexibility (e.g. supporting lot of identity providers, some adapters, jwt and/or database support, ..). The v4-beta2 behaves more like alpha or even experimental currently.

**Comment by balazsorban44** [comment] 2021-09-15 11:00
@AydinChavez your issues seem to be unrelated, I am still waiting for a proper reproduction for https://github.com/nextauthjs/adapters/issues/219#issuecomment-919016150 that I can have a look at on my computer.

#2746 didn't have a reproduction and wasn't closed per se, but converted to a discussion since it was labeled as a question, which we have a note about in the question issue form when filling out:
[![](https://i.imgur.com/4gekP4L.png)](https://github.com/nextauthjs/next-auth/issues/new?assignees=&labels=question&template=question.yaml)

(It's actually *this* issue that I just forgot to convert yet)

Remember that without a reproduction, it is not easier for us to debug a problem than for anyone else. :shrug: 

**Regarding testing:**

We have already introduced client-side tests: #1992 #2295  and we are in the works of testing as many providers as we possibly can, see #2524, but we rely on our community here, as we have a high number of things to support due to being flexible, as you say.

ALL merged Adapters are going through the same test suite introduced in https://github.com/nextauthjs/adapters/pull/171

The core has recently been refactored to TypeScript to catch a bunch of things build-time #2552.
Arguably we still have work to do testing the core, but this is not as easy as it sounds. Regardless, we are working on it.

I would say we have come a long way in terms of testing, in comparison v3 had no tests whatsoever.

If you have any suggestions or would like to contribute to improving testing, we welcome any help! :pray:

**Regarding the state of the beta release:**

We could argue about terms of alpha, beta, or experimental, but at the end of the day, when installing a `beta` release, you acknowledge that there might be edge-cases that might require YOU to have a closer look at things and don't expect everything to work perfectly. The reason for this beta release is exactly to get USEFUL feedback from those who are willing to help. I understand that problems might be frustrating in such a phase, but you can go back to v3 instead at any time. In my experience, the problem is usually not with a certain version but a user misconfiguration somewhere. (Not to say, there certainly **can be** issues in the lib as well, but they tend to be fewer than assumed, I think)

To make this more constructive, you can help advance things the most if you provide as much info as possible from the get-go, and help out others who have problems (remember we have to everyone's questions at the same time, and not everyone has a related issue to yours). The general feedback to v4 has been mixed, but I also got feedback that said migrating was a breeze. :shrug:

**Closed** 2021-09-15 11:36 UTC
Labels: question, incomplete
