### ISSUE TITLE
Intermittent FetchError: socket hang up

### ISSUE THREAD

**Issue by stevenspads** [nextauthjs/next-auth#4584] opened 2022-05-19 02:27 UTC
### Environment

```
System:
    OS: Windows 10 10.0.19041
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 43.56 GB / 63.93 GB
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 101.0.4951.54
    Edge: Spartan (44.19041.423.0), Chromium (101.0.1210.47)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    next: 12.0.10 => 12.0.10
    next-auth: ^4.3.4 => 4.3.4
    react: 17.0.2 => 17.0.2
```

### Reproduction URL

`http://localhost:3000/api/auth/session`

### Describe the issue

My NextJS app with NextAuth is failing intermittently on the following endpoint: `http://localhost:3000/api/auth/session`. The error reason is `socket hang up`. It's intermittent and difficult to debug.

```
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error request to http://localhost:3000/api/auth/session failed, reason: socket hang up {
  error: {
    message: 'request to http://localhost:3000/api/auth/session failed, reason: socket hang up',
    stack: 'FetchError: request to http://localhost:3000/api/auth/session failed, reason: socket hang up\n' +    
      '    at ClientRequest.<anonymous> 
```

### How to reproduce

Intermittent and difficult to reproduce. Run NextJS + NextAuth locally and navigate to routes that use the `useSession()` hook. The error will show up every few minutes, especially when the local server is under heavier load.

### Expected behavior

No FetchError should occur.

**Comment by khesayed** [comment] 2022-05-29 21:04
Facing same issue and as per documentation https://next-auth.js.org/getting-started/client#usesession

`useSession() returns an object containing two values: data and status:

    data: This can be three values: [Session](https://github.com/nextauthjs/next-auth/blob/8ff4b260143458c5d8a16b80b11d1b93baa0690f/types/index.d.ts#L437-L444) / undefined / null.
        when the session hasn't been fetched yet, data will undefined
        in case it failed to retrieve the session, data will be null
        in case of success, data will be [Session](https://github.com/nextauthjs/next-auth/blob/8ff4b260143458c5d8a16b80b11d1b93baa0690f/types/index.d.ts#L437-L444).
    status: enum mapping to three possible session states: "loading" | "authenticated" | "unauthenticated"`


So instead of checking for status and session you can only check for status and then render session data if authenticated.

**Comment by balazsorban44** [comment] 2022-05-31 14:53
Duplicate of https://github.com/nextauthjs/next-auth/issues/4553

**Closed by balazsorban44** 2022-05-31 14:53 UTC
Labels: triage

**Comment by stevenspads** [comment] 2022-06-02 23:45
> Facing same issue and as per documentation https://next-auth.js.org/getting-started/client#usesession
> 
> `useSession() returns an object containing two values: data and status:` `data: This can be three values: Session / undefined / null.` ` when the session hasn't been fetched yet, data will undefined` `in case it failed to retrieve the session, data will be null` `in case of success, data will be Session`
> 
> So instead of checking for status and session you can only check for status and then render session data if authenticated.

@khesayed Has this helped you with solving the issue?
