### ISSUE TITLE
Page with list of built-in providers does not exists

### ISSUE THREAD

**Issue by nrsimha** [nextauthjs/next-auth#8705] opened 2023-09-24 09:27 UTC
### What is the improvement or update you wish to see?

I would like to see linked page exists.

### Is there any context that might help us understand?

In `docs/docs/getting-started/oauth-tutorial.mdx` there is link to `/reference/providers/oauth-builtin` which doesn't exists.

**Comment by balazsorban44** [comment] 2023-09-25 09:57
Thanks! Seems like a duplicate of https://github.com/nextauthjs/next-auth/issues/8703, I added my comment there! :pray:

**Closed by balazsorban44** 2023-09-25 09:57 UTC
Labels: documentation, triage

**Comment by nrsimha** [comment] 2023-09-25 10:03
Yes, I have opened second one after bit closed issue I opened, but bot closed second one too.

**Comment by balazsorban44** [comment] 2023-09-26 00:08
sorry about that, the bot was a bit too aggressive, now it only checks for reproduction links on bug reports. 🙏
