### ISSUE TITLE
Discord invite is invalid

### ISSUE THREAD

**Issue by Skiuileuf** [nextauthjs/next-auth#11264] opened 2024-06-26 11:24 UTC
### What is the improvement or update you wish to see?

The discord community link that's written in the documentation is invalid.

### Is there any context that might help us understand?

Links I've tried:
https://discord.com/invite/nwgKuTPJmj
https://discord.authjs.dev/

**Comment by k-taro56** [comment] 2024-06-26 11:28
Hi,

Thank you for your cooperation.

I have created a new invitation link, please use this it.
https://discord.gg/V7X2RRxrKS

Thank you.

**Comment by k-taro56** [comment] 2024-06-26 11:28
Duplicate of #11250

**Comment by balazsorban44** [comment] 2024-07-02 23:25
discord.authjs.dev should be fixed now: https://github.com/nextauthjs/next-auth/discussions/11250#discussioncomment-9912740

**Closed by balazsorban44** 2024-07-02 23:25 UTC
Labels: documentation, triage
