### ISSUE TITLE
Spotify Provider scope isn't being applied, out of date documentation

### ISSUE THREAD

**Issue by dbeaudway** [nextauthjs/next-auth#3108] opened 2021-11-04 04:41 UTC
### Description 🐜

Using `next-auth 4.0.0-beta.6` I have been trying to use the Spotify Provider to retrieve a users recently played songs. If you modify the `scope` attribute, none of the values are applied. Instead, the app authorization only requests the Spotify Provider defaults.

### Is this a bug in your own project?

No

### How to reproduce ☕️

Example, if you modify the scope to request the following permissions none of them are applied except the default `user-read-email`:
```
# /api/auth/[...nextauth.js]
  providers: [
    SpotifyProvider({
      clientId: process.env.SPOTIFY_CLIENT_ID,
      clientSecret: process.env.SPOTIFY_CLIENT_SECRET,
      scope: "user-read-currently-playing user-read-recently-played user-top-read user-read-email"
    })
  ]
```

[Following this explanation](https://daily-dev-tips.com/posts/retrieving-a-persons-spotify-playlist-in-nextjs/), I was able to request the proper scopes by passing the values into the `authorization` option:
```
# /api/auth/[...nextauth.js]
  providers: [
    SpotifyProvider({
      clientId: process.env.SPOTIFY_CLIENT_ID,
      clientSecret: process.env.SPOTIFY_CLIENT_SECRET,
      authorization: "https://accounts.spotify.com/authorize?scope=user-read-currently-playing,user-read-recently-played,user-top-read,user-read-email"
    })
  ]
```

### Environment 🖥

npmPackages:
next: ^12.0.2 => 12.0.2 
next-auth: ^4.0.0-beta.6 => 4.0.0-beta.6 
react: ^17.0.2 => 17.0.2

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment] 2021-11-04 07:13
duplicate of #3017

**Closed by balazsorban44** 2021-11-04 07:13 UTC
Labels: bug
